import { prisma } from './prisma'

// ── Event CRUD ──────────────────────────────────────────────────────────────

export async function createEvent(data: {
  title: string
  description?: string
  eventType: string
  dueDate: string
  createdBy: string
  metadata?: unknown
}) {
  return prisma.complianceCalendarEvent.create({
    data: {
      title: data.title,
      description: data.description,
      eventType: data.eventType,
      dueDate: new Date(data.dueDate),
      createdBy: data.createdBy,
      metadata: data.metadata as never,
    },
    include: { creator: { select: { id: true, name: true, email: true } } },
  })
}

export async function updateEvent(
  id: string,
  data: Partial<{
    title: string
    description: string
    eventType: string
    dueDate: string
    metadata: unknown
  }>,
) {
  const update: Record<string, unknown> = {}
  if (data.title !== undefined) update.title = data.title
  if (data.description !== undefined) update.description = data.description
  if (data.eventType !== undefined) update.eventType = data.eventType
  if (data.dueDate !== undefined) update.dueDate = new Date(data.dueDate)
  if (data.metadata !== undefined) update.metadata = data.metadata as never

  return prisma.complianceCalendarEvent.update({
    where: { id },
    data: update,
    include: { creator: { select: { id: true, name: true, email: true } } },
  })
}

export async function deleteEvent(id: string) {
  return prisma.complianceCalendarEvent.delete({ where: { id } })
}

export async function markComplete(id: string) {
  return prisma.complianceCalendarEvent.update({
    where: { id },
    data: { completed: true, completedAt: new Date() },
  })
}

// ── Queries ─────────────────────────────────────────────────────────────────

export async function listEvents(filters?: {
  month?: number // 1-12
  year?: number
  eventType?: string
}) {
  const where: Record<string, unknown> = {}

  if (filters?.eventType) {
    where.eventType = filters.eventType
  }

  if (filters?.month && filters?.year) {
    const start = new Date(filters.year, filters.month - 1, 1)
    const end = new Date(filters.year, filters.month, 1)
    where.dueDate = { gte: start, lt: end }
  } else if (filters?.year) {
    const start = new Date(filters.year, 0, 1)
    const end = new Date(filters.year + 1, 0, 1)
    where.dueDate = { gte: start, lt: end }
  }

  return prisma.complianceCalendarEvent.findMany({
    where,
    orderBy: { dueDate: 'asc' },
    include: { creator: { select: { id: true, name: true, email: true } } },
  })
}

export async function getUpcomingEvents(days = 30) {
  const now = new Date()
  const future = new Date(now.getTime() + days * 24 * 60 * 60 * 1000)

  return prisma.complianceCalendarEvent.findMany({
    where: {
      dueDate: { gte: now, lte: future },
      completed: false,
    },
    orderBy: { dueDate: 'asc' },
    include: { creator: { select: { id: true, name: true, email: true } } },
  })
}

// ── Auto-generated events ───────────────────────────────────────────────────
// Reads DPAs and ComplianceDocuments expiring within 90 days, returns synthetic
// entries without persisting them.

export async function getAutoGeneratedEvents() {
  const now = new Date()
  const ninetyDays = new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000)

  const [expiringDPAs, expiringDocs] = await Promise.all([
    prisma.dataProcessingAgreement.findMany({
      where: { expiresAt: { gte: now, lte: ninetyDays }, active: true },
      select: { id: true, vendorName: true, expiresAt: true },
    }),
    prisma.complianceDocument.findMany({
      where: { expiresAt: { gte: now, lte: ninetyDays } },
      select: { id: true, title: true, type: true, expiresAt: true },
    }),
  ])

  const synthetic: Array<{
    id: string
    title: string
    description: string
    eventType: string
    dueDate: Date
    completed: boolean
    isAutoGenerated: true
  }> = []

  for (const dpa of expiringDPAs) {
    synthetic.push({
      id: `auto-dpa-${dpa.id}`,
      title: `DPA Expiry: ${dpa.vendorName}`,
      description: `Data Processing Agreement with ${dpa.vendorName} expires on ${dpa.expiresAt.toISOString().split('T')[0]}`,
      eventType: 'dpa-expiry',
      dueDate: dpa.expiresAt,
      completed: false,
      isAutoGenerated: true,
    })
  }

  for (const doc of expiringDocs) {
    if (!doc.expiresAt) continue
    synthetic.push({
      id: `auto-doc-${doc.id}`,
      title: `Document Expiry: ${doc.title}`,
      description: `${doc.type} document "${doc.title}" expires on ${doc.expiresAt.toISOString().split('T')[0]}`,
      eventType: 'policy-review',
      dueDate: doc.expiresAt,
      completed: false,
      isAutoGenerated: true,
    })
  }

  return synthetic.sort((a, b) => a.dueDate.getTime() - b.dueDate.getTime())
}
