/**
 * file-cleaner-service.ts
 *
 * Analyzes messy file/folder names and generates rename maps with
 * duplicate detection. Outputs rename scripts (PowerShell/bash).
 */

export type NamingPreset = 'date-first' | 'project-based' | 'department-archive' | 'custom'

export interface FileCleanerAnalyzeRequest {
  fileList: string
  preset: NamingPreset
  customPattern?: string
  department?: string
}

export interface RenameEntry {
  original: string
  proposed: string
  flags: ('duplicate' | 'too-long' | 'special-chars' | 'no-date')[]
}

export interface DuplicateCandidate {
  files: string[]
  similarity: number
}

export interface FileCleanerResult {
  renames: RenameEntry[]
  duplicates: DuplicateCandidate[]
  summary: string
  powershellScript: string
  bashScript: string
  convention: string
}

export function getFileCleanerSystemPrompt(req: FileCleanerAnalyzeRequest): string {
  const presetDescriptions: Record<NamingPreset, string> = {
    'date-first': 'YYYY-MM-DD_department_description (e.g., 2026-03-24_execcomms_ocr-response-draft)',
    'project-based': 'project_type_version (e.g., shared-governance_minutes_v2)',
    'department-archive': 'dept_year_category_name (e.g., execcomms_2026_policy_ferpa-update)',
    'custom': req.customPattern ?? 'user-defined pattern',
  }

  return `You are Sandy, a file organization expert. Analyze these file/folder names and generate a rename map.

## Naming Convention
Preset: ${req.preset}
Pattern: ${presetDescriptions[req.preset]}
${req.department ? `Department: ${req.department}` : ''}

## File List
${req.fileList}

## Instructions
Analyze each file name and generate a JSON response with this EXACT structure:

\`\`\`json
{
  "renames": [
    {
      "original": "Final_FINAL_v3_TianaEdits_03242026 (1).docx",
      "proposed": "2026-03-24_execcomms_ocr-response-draft.docx",
      "flags": ["duplicate"]
    }
  ],
  "duplicates": [
    {
      "files": ["Final_FINAL_v3.docx", "Final_v3_TianaEdits.docx"],
      "similarity": 0.85
    }
  ],
  "summary": "47 files renamed, 3 duplicates flagged, 12 dates normalized",
  "convention": "date-first: YYYY-MM-DD_department_description"
}
\`\`\`

Rules:
- Preserve file extensions
- Convert dates to ISO format (YYYY-MM-DD) when detected in any format
- Use kebab-case (hyphens, not underscores within words)
- Remove redundant words: "final", "copy", "v1/v2/v3" (keep latest version only)
- Remove "(1)", "(2)" copy indicators
- Flag files with names > 100 chars as "too-long"
- Flag files with special characters (!@#$%^&) as "special-chars"
- Flag files with no discernible date as "no-date"
- Detect potential duplicates by comparing normalized names (strip version numbers, "final", dates)
- Output ONLY the JSON block — no commentary`
}

/**
 * Escape a string for safe use as a single-quoted shell argument.
 * Handles single quotes, newlines, carriage returns, and null bytes.
 */
function escapeShellArg(s: string): string {
  // Strip null bytes and control characters that can break out of quoting
  const sanitized = s.replace(/[\0\r\n]/g, '')
  return sanitized.replace(/'/g, "'\\''")
}

function escapePowershellArg(s: string): string {
  const sanitized = s.replace(/[\0\r\n]/g, '')
  return sanitized.replace(/`/g, '``').replace(/"/g, '`"').replace(/\$/g, '`$')
}

/**
 * Generate rename scripts from the analysis result.
 */
export function generateScripts(renames: RenameEntry[]): { powershell: string; bash: string } {
  const filtered = renames.filter(r => r.original !== r.proposed)

  const ps = filtered
    .map(r => `Rename-Item -LiteralPath "${escapePowershellArg(r.original)}" -NewName "${escapePowershellArg(r.proposed)}"`)
    .join('\n')

  const bash = filtered
    .map(r => `mv -- '${escapeShellArg(r.original)}' '${escapeShellArg(r.proposed)}'`)
    .join('\n')

  return {
    powershell: `# File Rename Script (PowerShell)\n# Generated by the University of Kentucky File Cleaner\n# Review before running!\n\n${ps}`,
    bash: `#!/bin/bash\n# File Rename Script\n# Generated by the University of Kentucky File Cleaner\n# Review before running!\n\n${bash}`,
  }
}

/**
 * Parse Sandy's JSON response into a structured result.
 */
export function parseCleanerResponse(response: string): Omit<FileCleanerResult, 'powershellScript' | 'bashScript'> | null {
  try {
    // Extract JSON from response (may be wrapped in markdown code block)
    const jsonMatch = response.match(/```json\s*([\s\S]*?)```/) ?? response.match(/\{[\s\S]*?\}/)
    if (!jsonMatch) return null

    const json = jsonMatch[1] ?? jsonMatch[0]
    const parsed = JSON.parse(json)
    if (!Array.isArray(parsed.renames)) return null

    return {
      renames: parsed.renames ?? [],
      duplicates: parsed.duplicates ?? [],
      summary: parsed.summary ?? '',
      convention: parsed.convention ?? '',
    }
  } catch {
    return null
  }
}
