/**
 * English (US) string catalog for the Course Map page.
 * Organized by section: courseMap.toolbar.*, courseMap.export.*, etc.
 * Uses ICU MessageFormat for plurals: {count, plural, one {# node} other {# nodes}}
 */
export const enUS: Record<string, string> = {
  // ── Toolbar ────────────────────────────────────────────────────────────
  'courseMap.toolbar.select': 'Select',
  'courseMap.toolbar.connect': 'Connect',
  'courseMap.toolbar.selectMode': 'Select mode',
  'courseMap.toolbar.connectMode': 'Connect mode',
  'courseMap.toolbar.connectHintSource': 'Click a source node to start connecting',
  'courseMap.toolbar.connectHintTarget': 'Click a target node to create an edge, or press Escape to cancel',
  'courseMap.toolbar.saveSnapshot': 'Save Snapshot',
  'courseMap.toolbar.snapshots': 'Snapshots',
  'courseMap.toolbar.snapshotPlaceholder': 'Snapshot name...',
  'courseMap.toolbar.gapAnalysis': 'Gap Analysis',
  'courseMap.toolbar.analyzing': 'Analyzing...',
  'courseMap.toolbar.suggestEdges': 'Suggest Edges',
  'courseMap.toolbar.suggesting': 'Suggesting...',
  'courseMap.toolbar.validatePrerequisites': 'Validate Prerequisites',
  'courseMap.toolbar.validating': 'Validating...',
  'courseMap.toolbar.compareCourses': 'Compare Courses',
  'courseMap.toolbar.syncLmsLinks': 'Sync LMS Links',

  // ── Export ─────────────────────────────────────────────────────────────
  'courseMap.export.title': 'Export',
  'courseMap.export.png': 'Export as PNG',
  'courseMap.export.svg': 'Export as SVG',
  'courseMap.export.csv': 'Export as CSV',
  'courseMap.export.json': 'Export as JSON',
  'courseMap.export.pdf': 'Export as PDF',
  'courseMap.export.print': 'Print',
  'courseMap.export.generateReport': 'Generate Report',
  'courseMap.export.started': 'Export started...',
  'courseMap.export.complete': 'Export complete',

  // ── Print ──────────────────────────────────────────────────────────────
  'courseMap.print.header': 'Course Map',
  'courseMap.print.stats': '{nodeCount, plural, one {# node} other {# nodes}} · {edgeCount, plural, one {# connection} other {# connections}} · {unitCount, plural, one {# unit} other {# units}}',
  'courseMap.print.generatedAt': 'Generated {date} at {time}',
  'courseMap.print.unitsAndNodes': 'Units & Nodes',
  'courseMap.print.connections': 'Connections',
  'courseMap.print.legend': 'Legend',
  'courseMap.print.nodeTypes': 'Node Types',
  'courseMap.print.edgeTypes': 'Edge Types',
  'courseMap.print.footer': 'Generated by CATS-AI · University of Kentucky',

  // ── Nodes ──────────────────────────────────────────────────────────────
  'courseMap.nodes.nodeLabel': '{label}, {type} node, {connectionCount, plural, one {# connection} other {# connections}}',
  'courseMap.nodes.noMap': 'No course map yet',
  'courseMap.nodes.noMapStudent': "Your instructor hasn't uploaded a syllabus for this course yet.",
  'courseMap.nodes.noMapEducator': 'Upload a syllabus to generate a prerequisite graph for your course.',
  'courseMap.nodes.importSyllabus': 'Import Syllabus',
  'courseMap.nodes.reImportSyllabus': 'Re-import Syllabus',

  // ── Edges ──────────────────────────────────────────────────────────────
  'courseMap.edges.prerequisite': 'Prerequisite',
  'courseMap.edges.sequence': 'Sequence',
  'courseMap.edges.concurrent': 'Concurrent',
  'courseMap.edges.deleteConfirmTitle': 'Delete connection?',
  'courseMap.edges.deleteConfirmMessage': 'Remove this {edgeType} connection between "{fromNode}" and "{toNode}"?',
  'courseMap.edges.deleteButton': 'Delete',
  'courseMap.edges.cancelButton': 'Cancel',
  'courseMap.edges.edgeLabel': '{edgeType} connection from {fromNode} to {toNode}',
  'courseMap.edges.deleteEdgeLabel': 'Delete connection from {fromNode} to {toNode}',

  // ── Errors ─────────────────────────────────────────────────────────────
  'courseMap.errors.loadFailed': 'Failed to load course map',
  'courseMap.errors.saveFailed': 'Failed to save changes',
  'courseMap.errors.exportFailed': 'Export failed',
  'courseMap.errors.unauthorized': 'You do not have permission to perform this action',

  // ── Accessibility ──────────────────────────────────────────────────────
  'courseMap.a11y.graphLabel': 'Course map graph. Use arrow keys to navigate between nodes, Enter to open details, E to connect, Escape to cancel.',
  'courseMap.a11y.skipLink': 'Skip to course map graph',
  'courseMap.a11y.toolbarLabel': 'Course map toolbar',
  'courseMap.a11y.toastRegion': 'Notifications',
  'courseMap.a11y.edgesLabel': 'Course map connections diagram',
  'courseMap.a11y.skipToToolbar': 'Skip to toolbar',
  'courseMap.a11y.skipToPanel': 'Skip to active panel',
  'courseMap.a11y.highContrastOn': 'High contrast mode enabled',
  'courseMap.a11y.highContrastOff': 'High contrast mode disabled',
  'courseMap.a11y.keyboardShortcuts': 'Keyboard Shortcuts',
  'courseMap.a11y.closeShortcuts': 'Close keyboard shortcuts',
  'courseMap.a11y.highContrastToggle': 'Toggle high contrast mode',

  // ── Locale ──────────────────────────────────────────────────────────
  'courseMap.locale.label': 'Language',
  'courseMap.locale.en': 'English',
  'courseMap.locale.es': 'Español',

  // ── Status / offline ──────────────────────────────────────────────────
  'courseMap.status.offline': "You're offline — edits are queued locally",
  'courseMap.status.pending': '{count} pending',
  'courseMap.status.syncing': 'Syncing queued edits ({completed}/{total})...',
  'courseMap.status.synced': 'All queued edits synced successfully',
  'courseMap.status.syncError': "Some edits failed to sync — they'll be retried next time you're online",

  // ── Navigation ────────────────────────────────────────────────────────
  'courseMap.nav.backToCourse': 'Back to course',
  'courseMap.nav.title': 'Course Map',
  'courseMap.nav.subtitleStudent': 'Your progress through the course',
  'courseMap.nav.subtitleEducator': 'Prerequisite and sequence graph from your syllabus',

  // ── Progress ──────────────────────────────────────────────────────────
  'courseMap.progress.label': 'Progress:',
  'courseMap.progress.completed': 'Completed',
  'courseMap.progress.inProgress': 'In Progress',
  'courseMap.progress.notStarted': 'Not Started',
  'courseMap.progress.learningPath': 'Learning Path',
  'courseMap.progress.myPlan': 'My Plan',
  'courseMap.progress.classProgress': 'Class Progress',
  'courseMap.progress.sandySuggests': 'Sandy Suggests',
  'courseMap.progress.studyGroups': 'Study Groups',

  // ── Validation ────────────────────────────────────────────────────────
  'courseMap.validation.allPassed': 'All validation checks passed.',
  'courseMap.validation.blocked': 'Validation blocked — issues must be resolved',
  'courseMap.validation.warnings': 'Validation passed with warnings',
}
