'use client'

import { useState } from 'react'
import { Copy, Download, Rocket, Check } from 'lucide-react'
import { BuilderSpec, BuilderDocument } from '../lib/types'

interface CodePanelProps {
  spec: BuilderSpec
  documents: BuilderDocument[]
  onBuildRequest?: () => void
}

function generateCode(spec: BuilderSpec, documents: BuilderDocument[]): string {
  const docs = documents.map(d => `"${d.filename}"`).join(', ')
  const starters = (spec.starterQuestions || []).map(q => `    "${q}"`).join(',\n')
  const objectives = (spec.learningObjectives || []).map(o => `  "${o}"`).join(',\n')
  const prompt = (spec.systemPrompt || '...').replace(/`/g, "'")

  const personaBlock = spec.persona?.name
    ? `  persona: {
    name: "${spec.persona.name}",
    role: "${spec.persona.role || ''}",
  },
`
    : ''

  return `import { createSandboxTool } from "@the-sandbox/sdk"

/**
 * ${spec.name || 'Untitled Tool'}
 * Type: ${spec.toolType || 'CHATBOT'}
 * Category: ${spec.category || '...'}
 * Generated by The Sandbox Builder
 */
const experience = createSandboxTool({
  type: "${spec.toolType || 'CHATBOT'}",
  name: "${spec.name || '...'}",
  category: "${spec.category || '...'}",
  difficulty: "${spec.difficultyLevel || 'Introductory'}",
  audience: "${spec.intendedAudience || '...'}",
${personaBlock}  knowledge: [${docs || '/* upload PDFs in the Files tab */'}],

  systemPrompt: \`
${prompt}
  \`,

  experience: {
    welcomeMessage: \`${(spec.welcomeMessage || '...').replace(/`/g, "'")}\`,
    starterQuestions: [
${starters || '    /* questions will appear here */'}
    ],
  },

  learningObjectives: [
${objectives || '  /* objectives will appear here */'}
  ],

  gamification: {
    xpPerExchange: 5,
    completionBadge: "Experience Complete",
  },
})

export default experience`
}

function colorize(code: string): React.ReactNode[] {
  const lines = code.split('\n')
  return lines.map((line, i) => {
    const colored = line
      .replace(
        /(import|export|const|from|default)/g,
        '<span class="text-purple-400">$1</span>'
      )
      .replace(
        /("(?:[^"\\]|\\.)*")/g,
        '<span class="text-green-400">$1</span>'
      )
      .replace(
        /`[^`\n]*`/g,
        (m) => `<span class="text-yellow-300">${m}</span>`
      )
      .replace(
        /(\/\*[\s\S]*?\*\/|\/\/.*)/g,
        '<span class="text-gray-500 italic">$1</span>'
      )
      .replace(
        /\b(type|name|category|difficulty|audience|persona|role|knowledge|systemPrompt|experience|welcomeMessage|starterQuestions|learningObjectives|gamification|xpPerExchange|completionBadge):/g,
        '<span class="text-blue-300">$1</span>:'
      )
      .replace(
        /\b(createSandboxTool)\b/g,
        '<span class="text-yellow-400">$1</span>'
      )

    return (
      <div key={i} className="leading-6" dangerouslySetInnerHTML={{ __html: colored || '&nbsp;' }} />
    )
  })
}

export default function CodePanel({ spec, documents, onBuildRequest }: CodePanelProps) {
  const [copied, setCopied] = useState(false)
  const code = generateCode(spec, documents)
  const hasContent = !!(spec.name || spec.toolType !== 'CHATBOT' || spec.systemPrompt)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const filename = (spec.name || 'experience').toLowerCase().replace(/\s+/g, '-') + '.ts'
    const blob = new Blob([code], { type: 'text/typescript' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  if (!hasContent) {
    return (
      <div className="h-full flex items-center justify-center bg-[#1e1e2e] rounded-xl">
        <div className="text-center px-8">
          <div className="text-4xl mb-4 text-gray-600">{'</>'}</div>
          <p className="text-gray-400 text-sm">Your tool&apos;s source code will appear here as you build it.</p>
          <p className="text-gray-600 text-xs mt-2">This is what your tool specification looks like under the hood.</p>
        </div>
      </div>
    )
  }

  return (
    <div className="h-full flex flex-col bg-[#1e1e2e] rounded-xl overflow-hidden font-mono text-sm">
      {/* Editor header bar */}
      <div className="flex items-center gap-2 px-4 py-2 bg-[#2d2d3e] border-b border-gray-700 flex-shrink-0">
        <div className="flex gap-1.5">
          <div className="w-3 h-3 rounded-full bg-red-500/60" />
          <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
          <div className="w-3 h-3 rounded-full bg-green-500/60" />
        </div>
        <span className="text-gray-400 text-xs ml-2">experience.ts</span>

        {/* Action buttons */}
        <div className="ml-auto flex items-center gap-2">
          <button
            onClick={handleCopy}
            title="Copy to clipboard"
            className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-white bg-white/5 hover:bg-white/10 px-2.5 py-1 rounded-lg transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
          <button
            onClick={handleDownload}
            title="Download .ts file"
            className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-white bg-white/5 hover:bg-white/10 px-2.5 py-1 rounded-lg transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            Download
          </button>
          {onBuildRequest && spec.ready && (
            <button
              onClick={onBuildRequest}
              className="flex items-center gap-1.5 text-xs font-semibold text-white bg-gradient-to-r from-[#0033A0] to-purple-700 hover:opacity-90 px-3 py-1 rounded-lg transition-opacity"
            >
              <Rocket className="w-3.5 h-3.5" />
              Deploy
            </button>
          )}
        </div>
      </div>

      {/* Line numbers + code */}
      <div className="flex-1 overflow-y-auto">
        <div className="flex">
          <div className="select-none text-gray-600 text-right pr-4 pl-3 pt-4 pb-4 border-r border-gray-700/50 min-w-[3rem] bg-[#1a1a2a]">
            {code.split('\n').map((_, i) => (
              <div key={i} className="leading-6 text-xs">{i + 1}</div>
            ))}
          </div>
          <div className="flex-1 pl-4 pr-4 pt-4 pb-4 text-gray-300 overflow-x-auto">
            {colorize(code)}
          </div>
        </div>
      </div>
    </div>
  )
}
