import { NextRequest, NextResponse } from 'next/server'
import { withErrorHandling } from '../../../lib/api-utils'
import { requireAdminUser, isAuthFailure, parseRequestBody } from '../../../lib/server-auth'
import { listEvents, createEvent, getAutoGeneratedEvents } from '../../../lib/compliance-calendar-service'

export const GET = withErrorHandling(async (request: NextRequest) => {
  const auth = await requireAdminUser(request)
  if (isAuthFailure(auth)) return auth.response

  const month = request.nextUrl.searchParams.get('month')
  const year = request.nextUrl.searchParams.get('year')
  const eventType = request.nextUrl.searchParams.get('eventType') || undefined
  const includeAuto = request.nextUrl.searchParams.get('includeAuto') === 'true'

    const [events, autoEvents] = await Promise.all([
      listEvents({
        month: month ? parseInt(month, 10) : undefined,
        year: year ? parseInt(year, 10) : undefined,
        eventType,
      }),
      includeAuto ? getAutoGeneratedEvents() : Promise.resolve([]),
    ])
    return NextResponse.json({ events, autoEvents }, {
      headers: { 'Cache-Control': 'public, max-age=300, s-maxage=600, stale-while-revalidate=3600' },
    })

})

export const POST = withErrorHandling(async (request: NextRequest) => {
  const auth = await requireAdminUser(request)
  if (isAuthFailure(auth)) return auth.response

  const body = await parseRequestBody<{
    title: string
    description?: string
    eventType: string
    dueDate: string
    metadata?: unknown
  }>(request)
  if ('error' in body) return body.error

  const { title, eventType, dueDate } = body.data
  if (!title || !eventType || !dueDate) {
    return NextResponse.json({ error: 'title, eventType, and dueDate are required' }, { status: 400 })
  }

    const event = await createEvent({ ...body.data, createdBy: auth.user.id })
    return NextResponse.json({ event }, { status: 201 })

})
