/**
 * Scenario: Coordinated Anti-DEI Astroturfing Campaign
 *
 * 5-day window (Mar 20 – Mar 24, 2026). A network of ~15 bot accounts target
 * UK's diversity/equity/inclusion programs with coordinated posts demanding
 * defunding. Mixed with ~13 genuine organic negative posts from real people
 * with legitimate concerns about budget allocation and program effectiveness.
 * Plus positive defenders and neutral news coverage.
 *
 * 50 posts total:
 *   ~10 positive (students/faculty defending DEI programs)
 *   ~28 negative (15 AI/bot + 13 organic with legitimate concerns)
 *   ~12 neutral (news, official statements)
 *
 * ID prefixes:
 *   cc-p-XXX  — positive
 *   cc-n-XXX  — organic negative
 *   cc-ai-XXX — bot/AI-generated negative
 *   cc-u-XXX  — neutral
 */

import type {
  SocialPost,
  SentimentResult,
  ThemeCluster,
  AIDetectionResult,
  CrisisIntelligenceBrief,
} from '../types'

const DAY_0 = '2026-03-20T06:00:00Z'

function t(hoursAfter: number): string {
  return new Date(new Date(DAY_0).getTime() + hoursAfter * 3_600_000).toISOString()
}

let sproutSeq = 700000

function spr(): string {
  return `spr_${++sproutSeq}`
}

// ─── POSITIVE POSTS (10) — Defenders of DEI ──────────────────────────────

const POSITIVE: SocialPost[] = [
  {
    id: 'cc-p-001', sproutId: spr(),
    authorHandle: '@MarcusJr_UK26', authorDisplayName: 'Marcus Johnson Jr.',
    accountAgeDays: 1120, followerCount: 412, followingCount: 380, totalPostCount: 2100,
    hasProfilePhoto: true, bioKeywords: ['UK senior', 'first-gen', 'political science', 'BBN'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'The MLK Center mentorship program literally changed my trajectory at UK. First-gen student who almost dropped out freshman year — now I\'m heading to law school. DEI isn\'t a buzzword, it\'s the reason I\'m still here. #WeAreUK #DEIMatters',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(4), isReply: false, replyToId: null,
    hashtags: ['#WeAreUK', '#DEIMatters'],
    likes: 1890, shares: 456, replies: 134, quoteShares: 89,
  },
  {
    id: 'cc-p-002', sproutId: spr(),
    authorHandle: '@DrPatelUK', authorDisplayName: 'Dr. Anita Patel',
    accountAgeDays: 2800, followerCount: 3200, followingCount: 490, totalPostCount: 1850,
    hasProfilePhoto: true, bioKeywords: ['Associate Professor', 'English', 'UK', 'equity pedagogy'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'I\'ve been faculty at UK for 12 years. Our DEI programs have measurably improved retention for underrepresented students — 18% increase since 2019. The data is public. The people attacking these programs are not citing data. They\'re citing fear.',
    mediaType: 'link', mediaDescription: 'Link to UK Office of Institutional Research retention data',
    timestamp: t(8), isReply: false, replyToId: null,
    hashtags: [],
    likes: 2340, shares: 678, replies: 201, quoteShares: 145,
  },
  {
    id: 'cc-p-003', sproutId: spr(),
    authorHandle: 'u/wildcat_dei_ally', authorDisplayName: 'wildcat_dei_ally',
    accountAgeDays: 890, followerCount: 0, followingCount: 0, totalPostCount: 234,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false, locationHint: null,
    platform: 'reddit',
    text: 'Has anyone else noticed the flood of brand-new Twitter accounts suddenly very concerned about UK\'s DEI budget? 15 accounts created in the last month all posting nearly identical talking points. Something feels coordinated here. I archived some screenshots.',
    mediaType: 'image', mediaDescription: 'Screenshot collage of similar bot account profiles',
    timestamp: t(20), isReply: false, replyToId: null,
    hashtags: [],
    likes: 567, shares: 0, replies: 89, quoteShares: 0,
  },
  {
    id: 'cc-p-004', sproutId: spr(),
    authorHandle: '@TaylorUKGrad', authorDisplayName: 'Taylor Washington',
    accountAgeDays: 1560, followerCount: 289, followingCount: 410, totalPostCount: 1780,
    hasProfilePhoto: true, bioKeywords: ['UK alum', 'social work', 'MSW 2024', 'community organizer'],
    platformVerified: false, locationHint: 'Louisville, KY',
    platform: 'twitter',
    text: 'As a UK alum who benefited directly from the Office of Institutional Diversity — full stop, I would not have my MSW without the support structures DEI funding provides. These bot accounts can miss me with the "taxpayer" concern trolling.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(28), isReply: false, replyToId: null,
    hashtags: [],
    likes: 945, shares: 234, replies: 67, quoteShares: 34,
  },
  {
    id: 'cc-p-005', sproutId: spr(),
    authorHandle: '@UKStudentGov', authorDisplayName: 'UK Student Government',
    accountAgeDays: 4200, followerCount: 8900, followingCount: 320, totalPostCount: 5600,
    hasProfilePhoto: true, bioKeywords: ['Student Government Association', 'University of Kentucky'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'SGA stands firmly in support of UK\'s diversity, equity, and inclusion programs. These initiatives are not abstract — they are tutoring, mentorship, scholarships, and cultural programming that serve thousands of students. We will continue advocating for full funding.',
    mediaType: 'link', mediaDescription: 'Link to SGA resolution in support of DEI programs',
    timestamp: t(40), isReply: false, replyToId: null,
    hashtags: ['#UKSGA', '#ProtectDEI'],
    likes: 3100, shares: 890, replies: 312, quoteShares: 156,
  },
  {
    id: 'cc-p-006', sproutId: spr(),
    authorHandle: '@ProfsForEquityUK', authorDisplayName: 'UK Faculty for Equity',
    accountAgeDays: 1100, followerCount: 1450, followingCount: 230, totalPostCount: 420,
    hasProfilePhoto: true, bioKeywords: ['faculty coalition', 'equity', 'inclusion', 'UK'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'Our coalition of 140+ faculty members has signed an open letter to the Provost reaffirming our support for DEI infrastructure at UK. Defunding these programs would harm the students who need them most and undermine our research mission. Full letter: ',
    mediaType: 'link', mediaDescription: 'Link to faculty open letter PDF',
    timestamp: t(52), isReply: false, replyToId: null,
    hashtags: ['#UKFaculty', '#DEIMatters'],
    likes: 1780, shares: 534, replies: 178, quoteShares: 98,
  },
  {
    id: 'cc-p-007', sproutId: spr(),
    authorHandle: '@NatalieUK28', authorDisplayName: 'Natalie Chen',
    accountAgeDays: 670, followerCount: 156, followingCount: 290, totalPostCount: 890,
    hasProfilePhoto: true, bioKeywords: ['UK sophomore', 'pre-med', 'first-gen Asian American'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'The AAPI student center helped me find community when I felt completely invisible on a campus where I\'m 3% of the population. To the fake accounts saying DEI is wasteful: you have no idea what it\'s like to be the only one in the room.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(64), isReply: false, replyToId: null,
    hashtags: ['#AAPIatUK'],
    likes: 1234, shares: 345, replies: 89, quoteShares: 56,
  },
  {
    id: 'cc-p-008', sproutId: spr(),
    authorHandle: '@CoachDiversityUK', authorDisplayName: 'Dr. James Worthington',
    accountAgeDays: 3400, followerCount: 2100, followingCount: 560, totalPostCount: 3400,
    hasProfilePhoto: true, bioKeywords: ['VP for Institutional Diversity', 'University of Kentucky'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'facebook',
    text: 'I want to address the coordinated misinformation circulating about our programs. UK\'s Office of Institutional Diversity operates on less than 0.4% of the university\'s total budget while serving over 8,000 students annually. Our outcomes — graduation rates, career placement, student satisfaction — are documented and publicly available. We welcome genuine inquiry. We will not be distracted by manufactured outrage.',
    mediaType: 'link', mediaDescription: 'Link to OID annual impact report',
    timestamp: t(76), isReply: false, replyToId: null,
    hashtags: [],
    likes: 2890, shares: 1200, replies: 456, quoteShares: 0,
  },
  {
    id: 'cc-p-009', sproutId: spr(),
    authorHandle: '@LexHeraldLeader', authorDisplayName: 'Lexington Herald-Leader',
    accountAgeDays: 5200, followerCount: 89000, followingCount: 1200, totalPostCount: 45000,
    hasProfilePhoto: true, bioKeywords: ['news', 'Lexington', 'Kentucky', 'journalism'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'OPINION | UK\'s DEI programs deserve defense, not defunding — a guest column by 12 university deans. "These programs represent our institutional commitment to every student we admit." Read: ',
    mediaType: 'link', mediaDescription: 'Link to Herald-Leader opinion column',
    timestamp: t(88), isReply: false, replyToId: null,
    hashtags: [],
    likes: 1560, shares: 789, replies: 345, quoteShares: 123,
  },
  {
    id: 'cc-p-010', sproutId: spr(),
    authorHandle: '@JamalUKLaw', authorDisplayName: 'Jamal Robinson',
    accountAgeDays: 2100, followerCount: 678, followingCount: 345, totalPostCount: 1200,
    hasProfilePhoto: true, bioKeywords: ['UK Law 3L', 'BLSA president', 'first-gen'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'The Black Law Students Association at UK exists because of DEI funding. We run LSAT prep workshops, 1L mentoring, and bar exam study groups. Every year we help 30+ students who look like me get through law school. Try telling any of us this is a waste.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(92), isReply: false, replyToId: null,
    hashtags: ['#BLSA', '#DEIWorks'],
    likes: 1890, shares: 567, replies: 145, quoteShares: 78,
  },
]

// ─── BOT / AI-GENERATED NEGATIVE POSTS (15) ─────────────────────────────
// Account patterns: 7-30 day old accounts, <50 followers, no photos,
// 1-5 following, 3-15 total posts, generic bios, formal register,
// clustered timestamps (bursts at t(12), t(36), t(60), t(84))

const BOT_NEGATIVE: SocialPost[] = [
  {
    id: 'cc-ai-001', sproutId: spr(),
    authorHandle: '@ConcernedKYTaxpayer1', authorDisplayName: 'Concerned KY Taxpayer',
    accountAgeDays: 12, followerCount: 8, followingCount: 2, totalPostCount: 5,
    hasProfilePhoto: false, bioKeywords: ['concerned', 'taxpayer', 'accountability', 'Kentucky'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'It is important to note that the University of Kentucky allocates significant taxpayer resources to DEI programs with limited measurable outcomes. Furthermore, one must consider whether these funds could be better directed toward core academic infrastructure and student financial aid.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(12), isReply: false, replyToId: null,
    hashtags: ['#DefundDEI', '#UKAccountability'],
    likes: 14, shares: 8, replies: 3, quoteShares: 2,
  },
  {
    id: 'cc-ai-002', sproutId: spr(),
    authorHandle: '@KYParentVoice22', authorDisplayName: 'Kentucky Parent Voice',
    accountAgeDays: 18, followerCount: 15, followingCount: 3, totalPostCount: 7,
    hasProfilePhoto: false, bioKeywords: ['parent', 'concerned', 'education', 'Kentucky values'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'As a concerned parent, it is deeply troubling to see the University of Kentucky prioritize divisive DEI programming over the fundamental educational needs of our children. One must consider the opportunity cost of these expenditures in light of rising tuition.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(12.3), isReply: false, replyToId: null,
    hashtags: ['#DefundDEI', '#ParentsForAccountability'],
    likes: 11, shares: 6, replies: 2, quoteShares: 1,
  },
  {
    id: 'cc-ai-003', sproutId: spr(),
    authorHandle: '@FiscalWatchKY', authorDisplayName: 'KY Fiscal Watch',
    accountAgeDays: 9, followerCount: 22, followingCount: 1, totalPostCount: 4,
    hasProfilePhoto: false, bioKeywords: ['fiscal responsibility', 'taxpayer', 'accountability'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'Furthermore, a careful examination of the University of Kentucky\'s budget reveals that DEI administrative costs have increased substantially while student-facing services remain underfunded. It is imperative that university leadership conduct a comprehensive review of these allocations.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(12.5), isReply: false, replyToId: null,
    hashtags: ['#UKBudget', '#DefundDEI'],
    likes: 9, shares: 5, replies: 1, quoteShares: 0,
  },
  {
    id: 'cc-ai-004', sproutId: spr(),
    authorHandle: '@TruthInEdKY', authorDisplayName: 'Truth in Education KY',
    accountAgeDays: 21, followerCount: 31, followingCount: 4, totalPostCount: 9,
    hasProfilePhoto: false, bioKeywords: ['truth', 'education', 'accountability', 'merit'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'It is important to note that merit-based admissions and hiring practices produce the strongest outcomes for all students. The University of Kentucky\'s investment in DEI bureaucracy raises serious questions about whether the institution prioritizes ideology over academic excellence.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(12.8), isReply: false, replyToId: null,
    hashtags: ['#MeritMatters', '#DefundDEI'],
    likes: 18, shares: 7, replies: 4, quoteShares: 1,
  },
  {
    id: 'cc-ai-005', sproutId: spr(),
    authorHandle: '@AccountabilityNowKY', authorDisplayName: 'Accountability Now KY',
    accountAgeDays: 14, followerCount: 19, followingCount: 2, totalPostCount: 6,
    hasProfilePhoto: false, bioKeywords: ['accountability', 'taxpayer', 'transparency'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'One must consider the broader implications of DEI mandates at the University of Kentucky. Furthermore, it is deeply concerning that these programs operate without meaningful performance metrics or independent oversight. Taxpayers deserve full transparency regarding the return on this investment.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(36), isReply: false, replyToId: null,
    hashtags: ['#TransparencyNow', '#DefundDEI'],
    likes: 12, shares: 4, replies: 2, quoteShares: 0,
  },
  {
    id: 'cc-ai-006', sproutId: spr(),
    authorHandle: '@KYMeritFirst', authorDisplayName: 'Merit First Kentucky',
    accountAgeDays: 16, followerCount: 27, followingCount: 3, totalPostCount: 8,
    hasProfilePhoto: false, bioKeywords: ['merit', 'excellence', 'Kentucky', 'education reform'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'It is important to recognize that diversity of thought is best achieved through academic rigor, not through administrative programs. The University of Kentucky should redirect DEI funding toward scholarships and laboratory equipment that benefit all students equally.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(36.4), isReply: false, replyToId: null,
    hashtags: ['#MeritFirst', '#UKReform'],
    likes: 16, shares: 9, replies: 3, quoteShares: 2,
  },
  {
    id: 'cc-ai-007', sproutId: spr(),
    authorHandle: '@CommonSenseKY_', authorDisplayName: 'Common Sense Kentucky',
    accountAgeDays: 10, followerCount: 11, followingCount: 1, totalPostCount: 3,
    hasProfilePhoto: false, bioKeywords: ['common sense', 'taxpayer', 'reform'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'Furthermore, one must ask whether the University of Kentucky\'s DEI apparatus serves the interests of students or the interests of a growing administrative class. It is essential that we demand accountability and measurable outcomes from every dollar of public funding.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(36.7), isReply: false, replyToId: null,
    hashtags: ['#DefundDEI', '#CommonSense'],
    likes: 7, shares: 3, replies: 1, quoteShares: 0,
  },
  {
    id: 'cc-ai-008', sproutId: spr(),
    authorHandle: '@EduReformKY2026', authorDisplayName: 'Education Reform KY',
    accountAgeDays: 25, followerCount: 42, followingCount: 5, totalPostCount: 12,
    hasProfilePhoto: true, bioKeywords: ['education reform', 'standards', 'accountability', 'parents'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'It is deeply concerning that the University of Kentucky continues to expand DEI programming while STEM lab capacity remains at 2019 levels. One must consider whether ideological commitments are driving resource allocation at the expense of workforce-relevant education.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(60), isReply: false, replyToId: null,
    hashtags: ['#STEMFirst', '#DefundDEI'],
    likes: 23, shares: 11, replies: 5, quoteShares: 3,
  },
  {
    id: 'cc-ai-009', sproutId: spr(),
    authorHandle: '@KYTaxpayerAlert', authorDisplayName: 'KY Taxpayer Alert',
    accountAgeDays: 8, followerCount: 6, followingCount: 1, totalPostCount: 3,
    hasProfilePhoto: false, bioKeywords: ['taxpayer', 'alert', 'government waste'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'It is important to note that peer institutions with comparable student populations have achieved similar or superior diversity outcomes with significantly lower DEI administrative costs. The University of Kentucky must benchmark its spending against evidence-based practices.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(60.3), isReply: false, replyToId: null,
    hashtags: ['#DefundDEI', '#Benchmarking'],
    likes: 8, shares: 2, replies: 1, quoteShares: 0,
  },
  {
    id: 'cc-ai-010', sproutId: spr(),
    authorHandle: '@PatriotParentKY', authorDisplayName: 'Patriot Parent KY',
    accountAgeDays: 20, followerCount: 34, followingCount: 4, totalPostCount: 10,
    hasProfilePhoto: false, bioKeywords: ['parent', 'patriot', 'freedom', 'education'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'Furthermore, it is essential to acknowledge that many students and families at the University of Kentucky do not share the ideological premises underlying DEI programming. One must consider whether mandatory diversity requirements represent an appropriate use of institutional authority.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(60.6), isReply: false, replyToId: null,
    hashtags: ['#ParentalRights', '#DefundDEI'],
    likes: 19, shares: 8, replies: 4, quoteShares: 1,
  },
  {
    id: 'cc-ai-011', sproutId: spr(),
    authorHandle: '@FreedomEduKY', authorDisplayName: 'Freedom in Education KY',
    accountAgeDays: 7, followerCount: 9, followingCount: 2, totalPostCount: 4,
    hasProfilePhoto: false, bioKeywords: ['freedom', 'education', 'reform', 'Kentucky'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'It is important to note that academic freedom requires protecting diverse viewpoints, not institutionalizing a single perspective through DEI mandates. The University of Kentucky should foster open intellectual inquiry rather than administrative orthodoxy.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(84), isReply: false, replyToId: null,
    hashtags: ['#AcademicFreedom', '#DefundDEI'],
    likes: 13, shares: 6, replies: 2, quoteShares: 1,
  },
  {
    id: 'cc-ai-012', sproutId: spr(),
    authorHandle: '@KYValuesMatter', authorDisplayName: 'Kentucky Values Matter',
    accountAgeDays: 15, followerCount: 28, followingCount: 3, totalPostCount: 11,
    hasProfilePhoto: false, bioKeywords: ['values', 'Kentucky', 'tradition', 'accountability'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'One must consider that the University of Kentucky\'s DEI expenditures represent a significant allocation of resources that could otherwise fund need-based financial aid. It is imperative that the institution demonstrate how these programs serve the concrete needs of Kentucky families.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(84.3), isReply: false, replyToId: null,
    hashtags: ['#KYValues', '#DefundDEI'],
    likes: 15, shares: 7, replies: 3, quoteShares: 0,
  },
  {
    id: 'cc-ai-013', sproutId: spr(),
    authorHandle: '@TransparencyKY1', authorDisplayName: 'Transparency KY',
    accountAgeDays: 11, followerCount: 13, followingCount: 2, totalPostCount: 5,
    hasProfilePhoto: false, bioKeywords: ['transparency', 'government', 'accountability'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'Furthermore, it is deeply troubling that the University of Kentucky has not published an independent audit of DEI program effectiveness. One must ask why an institution committed to evidence-based research exempts its own administrative programs from rigorous evaluation.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(84.6), isReply: false, replyToId: null,
    hashtags: ['#AuditDEI', '#DefundDEI'],
    likes: 10, shares: 4, replies: 2, quoteShares: 0,
  },
  {
    id: 'cc-ai-014', sproutId: spr(),
    authorHandle: '@RealTalkKYEdu', authorDisplayName: 'Real Talk KY Education',
    accountAgeDays: 28, followerCount: 45, followingCount: 5, totalPostCount: 15,
    hasProfilePhoto: true, bioKeywords: ['education', 'real talk', 'reform', 'parents'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'It is important to note that several Kentucky legislators have raised legitimate questions about DEI spending at state universities. The University of Kentucky should proactively engage with these concerns rather than dismiss them as politically motivated.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(84.9), isReply: false, replyToId: null,
    hashtags: ['#KYLegislature', '#DEIReform'],
    likes: 27, shares: 12, replies: 6, quoteShares: 2,
  },
  {
    id: 'cc-ai-015', sproutId: spr(),
    authorHandle: '@KYEdAccountable', authorDisplayName: 'KY Education Accountability',
    accountAgeDays: 13, followerCount: 17, followingCount: 2, totalPostCount: 6,
    hasProfilePhoto: false, bioKeywords: ['accountability', 'education', 'taxpayer', 'reform'],
    platformVerified: false, locationHint: null,
    platform: 'twitter',
    text: 'One must consider that a comprehensive cost-benefit analysis of DEI programming at the University of Kentucky would likely reveal substantial administrative overhead relative to direct student impact. It is essential that leadership prioritize fiscal responsibility and measurable outcomes.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(85.2), isReply: false, replyToId: null,
    hashtags: ['#FiscalResponsibility', '#DefundDEI'],
    likes: 11, shares: 5, replies: 2, quoteShares: 1,
  },
]

// ─── ORGANIC NEGATIVE POSTS (13) — Legitimate Concerns ───────────────────

const ORGANIC_NEGATIVE: SocialPost[] = [
  {
    id: 'cc-n-001', sproutId: spr(),
    authorHandle: '@BrandonUK_Econ', authorDisplayName: 'Brandon Mitchell',
    accountAgeDays: 1340, followerCount: 234, followingCount: 312, totalPostCount: 1560,
    hasProfilePhoto: true, bioKeywords: ['UK junior', 'economics', 'student senator'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'Look I support diversity programs but can someone explain why the DEI office has 14 full-time staff while the career center that serves ALL students has 6? I\'m not anti-DEI, I\'m pro-math. The budget allocation feels off.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(6), isReply: false, replyToId: null,
    hashtags: [],
    likes: 567, shares: 134, replies: 89, quoteShares: 45,
  },
  {
    id: 'cc-n-002', sproutId: spr(),
    authorHandle: 'u/uk_alum_2018', authorDisplayName: 'uk_alum_2018',
    accountAgeDays: 2900, followerCount: 0, followingCount: 0, totalPostCount: 567,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false, locationHint: null,
    platform: 'reddit',
    text: 'Graduated UK in 2018. Genuinely asking — what has the DEI office actually accomplished? I was involved with the multicultural center and it was always underfunded while the administrative side grew. It felt like the university cared more about having a DEI office than actually doing DEI work.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(15), isReply: false, replyToId: null,
    hashtags: [],
    likes: 345, shares: 0, replies: 67, quoteShares: 0,
  },
  {
    id: 'cc-n-003', sproutId: spr(),
    authorHandle: '@SarahKYMom3', authorDisplayName: 'Sarah Collins',
    accountAgeDays: 2200, followerCount: 189, followingCount: 456, totalPostCount: 890,
    hasProfilePhoto: true, bioKeywords: ['mom of 3', 'Kentucky', 'education advocate'],
    platformVerified: false, locationHint: 'Richmond, KY',
    platform: 'twitter',
    text: 'My daughter pays $28k/year at UK and can\'t get into a required bio lab. Meanwhile the university is hiring another associate VP of something-diversity-something. I want my kid to have a diverse experience AND be able to graduate on time. Is that too much to ask?',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(18), isReply: false, replyToId: null,
    hashtags: [],
    likes: 890, shares: 234, replies: 156, quoteShares: 67,
  },
  {
    id: 'cc-n-004', sproutId: spr(),
    authorHandle: '@DrMartinezPhys', authorDisplayName: 'Dr. Carlos Martinez',
    accountAgeDays: 3100, followerCount: 1890, followingCount: 340, totalPostCount: 2100,
    hasProfilePhoto: true, bioKeywords: ['Physics professor', 'UK', 'research', 'Latino in STEM'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'Speaking as a Latino faculty member: I support the mission of DEI but the mandatory training workshops are genuinely unhelpful. 3 hours of PowerPoint about unconscious bias doesn\'t change department culture. We need mentorship funding and pipeline programs, not compliance theater.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(24), isReply: false, replyToId: null,
    hashtags: [],
    likes: 1456, shares: 456, replies: 234, quoteShares: 112,
  },
  {
    id: 'cc-n-005', sproutId: spr(),
    authorHandle: '@JessicaUK27', authorDisplayName: 'Jessica Park',
    accountAgeDays: 890, followerCount: 156, followingCount: 278, totalPostCount: 670,
    hasProfilePhoto: true, bioKeywords: ['UK junior', 'nursing', 'Korean American'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'Honestly the DEI office sent me to a "cultural affinity group" meeting and it was just 4 white staff members asking me about my experience as an Asian student. I felt more tokenized than supported. The intention is good but the execution needs serious work.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(30), isReply: false, replyToId: null,
    hashtags: [],
    likes: 789, shares: 234, replies: 112, quoteShares: 56,
  },
  {
    id: 'cc-n-006', sproutId: spr(),
    authorHandle: 'u/fiscal_hawk_lex', authorDisplayName: 'fiscal_hawk_lex',
    accountAgeDays: 1800, followerCount: 0, followingCount: 0, totalPostCount: 345,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false, locationHint: null,
    platform: 'reddit',
    text: 'I pulled UK\'s actual budget docs. The Office of Institutional Diversity budget has grown 340% since 2015 while the counseling center — which serves students in crisis — has grown 12%. I\'m a progressive and I think we need to have an honest conversation about priorities here.',
    mediaType: 'link', mediaDescription: 'Link to UK public budget documents',
    timestamp: t(34), isReply: false, replyToId: null,
    hashtags: [],
    likes: 1230, shares: 0, replies: 189, quoteShares: 0,
  },
  {
    id: 'cc-n-007', sproutId: spr(),
    authorHandle: '@DavidUKStaff', authorDisplayName: 'David Rawlings',
    accountAgeDays: 1560, followerCount: 312, followingCount: 234, totalPostCount: 780,
    hasProfilePhoto: true, bioKeywords: ['UK staff', 'advising', '10 years'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'I work in advising at UK. We have 1 advisor per 450 students. The DEI office just posted 2 new positions at $85k each. I make $42k advising first-gen students every day. I\'m not against DEI — I\'m against the university pretending it doesn\'t have to choose.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(42), isReply: false, replyToId: null,
    hashtags: [],
    likes: 2100, shares: 567, replies: 234, quoteShares: 134,
  },
  {
    id: 'cc-n-008', sproutId: spr(),
    authorHandle: '@AmandaUKGrad', authorDisplayName: 'Amanda Foster',
    accountAgeDays: 2400, followerCount: 456, followingCount: 567, totalPostCount: 1890,
    hasProfilePhoto: true, bioKeywords: ['UK grad student', 'sociology', 'TA'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'I\'m a DEI researcher and even I think UK\'s approach is flawed. The office runs awareness workshops while actual student organizations doing the diversity work are fighting over $500 programming budgets. The money needs to flow DOWN to students, not UP to administrators.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(48), isReply: false, replyToId: null,
    hashtags: [],
    likes: 1678, shares: 456, replies: 189, quoteShares: 98,
  },
  {
    id: 'cc-n-009', sproutId: spr(),
    authorHandle: '@KYLegWatcher', authorDisplayName: 'Kentucky Legislative Watch',
    accountAgeDays: 3400, followerCount: 4500, followingCount: 890, totalPostCount: 8900,
    hasProfilePhoto: true, bioKeywords: ['KY politics', 'state budget', 'education policy'],
    platformVerified: false, locationHint: 'Frankfort, KY',
    platform: 'twitter',
    text: 'BREAKING: State Rep. Harris files amendment to HB 250 requiring line-item reporting on DEI spending at all public universities. UK\'s Office of Institutional Diversity specifically cited. This has bipartisan support from fiscal conservatives and accountability progressives.',
    mediaType: 'link', mediaDescription: 'Link to Kentucky General Assembly HB 250 amendment text',
    timestamp: t(56), isReply: false, replyToId: null,
    hashtags: ['#KYLeg', '#HB250'],
    likes: 890, shares: 345, replies: 234, quoteShares: 156,
  },
  {
    id: 'cc-n-010', sproutId: spr(),
    authorHandle: '@MikeRuralKY', authorDisplayName: 'Mike Henderson',
    accountAgeDays: 1900, followerCount: 123, followingCount: 189, totalPostCount: 456,
    hasProfilePhoto: true, bioKeywords: ['Appalachian', 'UK alum', 'first-gen', 'Pike County'],
    platformVerified: false, locationHint: 'Pikeville, KY',
    platform: 'facebook',
    text: 'I grew up in Pike County and was the first person in my family to go to UK. I needed support too — from rural poverty, not knowing how college works, not having anyone to call. But the DEI office didn\'t have a program for kids like me. Appalachian students are invisible in the diversity conversation and it stings.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(62), isReply: false, replyToId: null,
    hashtags: [],
    likes: 1456, shares: 567, replies: 234, quoteShares: 0,
  },
  {
    id: 'cc-n-011', sproutId: spr(),
    authorHandle: '@EmmaUK_SWE', authorDisplayName: 'Emma Chen',
    accountAgeDays: 1100, followerCount: 234, followingCount: 312, totalPostCount: 890,
    hasProfilePhoto: true, bioKeywords: ['UK senior', 'CS major', 'SWE intern'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'DEI training in my CS department was a single 45-minute Zoom last August. The entire women-in-CS club operates on $200/semester. Meanwhile the university tweets about "commitment to inclusion" every other day. Actions > words, @universityofky',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(70), isReply: false, replyToId: null,
    hashtags: [],
    likes: 934, shares: 234, replies: 112, quoteShares: 45,
  },
  {
    id: 'cc-n-012', sproutId: spr(),
    authorHandle: 'u/uk_budget_nerd', authorDisplayName: 'uk_budget_nerd',
    accountAgeDays: 2100, followerCount: 0, followingCount: 0, totalPostCount: 789,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false, locationHint: null,
    platform: 'reddit',
    text: 'Posted a detailed breakdown of UK\'s DEI budget vs. peer SEC institutions. UK spends 2.3x the SEC average per-student on DEI administration but ranks 9th out of 14 in minority student graduation rates. The money isn\'t the problem — the strategy is. Full spreadsheet in comments.',
    mediaType: 'link', mediaDescription: 'Link to shared Google Sheets budget comparison',
    timestamp: t(78), isReply: false, replyToId: null,
    hashtags: [],
    likes: 1890, shares: 0, replies: 345, quoteShares: 0,
  },
  {
    id: 'cc-n-013', sproutId: spr(),
    authorHandle: '@RavenUK_BSU', authorDisplayName: 'Raven Thompson',
    accountAgeDays: 980, followerCount: 345, followingCount: 289, totalPostCount: 1200,
    hasProfilePhoto: true, bioKeywords: ['UK senior', 'Black Student Union VP', 'poli sci'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'The bot accounts demanding we defund DEI are gross and obvious. BUT — and I say this as BSU VP — the real DEI work at UK happens DESPITE the office, not because of it. BSU, BLSA, NSBE, multicultural orgs do the heavy lifting. The office mostly does PR for the president\'s reports.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(82), isReply: false, replyToId: null,
    hashtags: [],
    likes: 2340, shares: 678, replies: 289, quoteShares: 145,
  },
]

// ─── NEUTRAL POSTS (12) — News, Official Statements ─────────────────────

const NEUTRAL: SocialPost[] = [
  {
    id: 'cc-u-001', sproutId: spr(),
    authorHandle: '@WABORNNEWS', authorDisplayName: 'WKYT News',
    accountAgeDays: 5400, followerCount: 67000, followingCount: 890, totalPostCount: 34000,
    hasProfilePhoto: true, bioKeywords: ['news', 'Lexington', 'Kentucky', 'CBS affiliate'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'University of Kentucky\'s DEI programs face renewed scrutiny amid social media campaign. UK spokesperson says programs serve over 8,000 students. Story developing. Full coverage at 6pm.',
    mediaType: 'link', mediaDescription: 'Link to WKYT article on UK DEI debate',
    timestamp: t(16), isReply: false, replyToId: null,
    hashtags: ['#WKYT'],
    likes: 234, shares: 89, replies: 67, quoteShares: 23,
  },
  {
    id: 'cc-u-002', sproutId: spr(),
    authorHandle: '@UKYMedia', authorDisplayName: 'UK Public Relations',
    accountAgeDays: 4800, followerCount: 23000, followingCount: 450, totalPostCount: 12000,
    hasProfilePhoto: true, bioKeywords: ['University of Kentucky', 'official', 'media relations'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'Statement: The University of Kentucky remains committed to fostering an inclusive campus environment. Our diversity programs are regularly assessed and serve thousands of students annually. We welcome constructive dialogue about how best to serve all members of our community.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(22), isReply: false, replyToId: null,
    hashtags: [],
    likes: 456, shares: 123, replies: 189, quoteShares: 45,
  },
  {
    id: 'cc-u-003', sproutId: spr(),
    authorHandle: '@KyKernelNews', authorDisplayName: 'Kentucky Kernel',
    accountAgeDays: 5600, followerCount: 12000, followingCount: 780, totalPostCount: 18000,
    hasProfilePhoto: true, bioKeywords: ['student newspaper', 'University of Kentucky', 'independent journalism'],
    platformVerified: false, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'ANALYSIS: We investigated 23 social media accounts posting anti-DEI content about UK in the past 5 days. Our findings: 15 were created within the last month, share similar language patterns, and have minimal follower bases. Full investigation: ',
    mediaType: 'link', mediaDescription: 'Link to Kentucky Kernel investigative piece',
    timestamp: t(32), isReply: false, replyToId: null,
    hashtags: ['#KyKernel'],
    likes: 3400, shares: 1200, replies: 456, quoteShares: 234,
  },
  {
    id: 'cc-u-004', sproutId: spr(),
    authorHandle: '@InsideHigherEd', authorDisplayName: 'Inside Higher Ed',
    accountAgeDays: 6200, followerCount: 245000, followingCount: 3400, totalPostCount: 89000,
    hasProfilePhoto: true, bioKeywords: ['higher education', 'news', 'analysis'],
    platformVerified: true, locationHint: null,
    platform: 'twitter',
    text: 'University of Kentucky joins growing list of institutions facing coordinated social media campaigns targeting DEI programs. Campus communications experts say pattern is consistent with astroturfing seen at 12+ universities this semester.',
    mediaType: 'link', mediaDescription: 'Link to Inside Higher Ed feature on coordinated anti-DEI campaigns',
    timestamp: t(44), isReply: false, replyToId: null,
    hashtags: [],
    likes: 1890, shares: 890, replies: 345, quoteShares: 178,
  },
  {
    id: 'cc-u-005', sproutId: spr(),
    authorHandle: '@UKProvostOffice', authorDisplayName: 'UK Provost\'s Office',
    accountAgeDays: 4100, followerCount: 8900, followingCount: 120, totalPostCount: 3400,
    hasProfilePhoto: true, bioKeywords: ['University of Kentucky', 'Provost', 'academic affairs'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'Provost DiPaola will host a campus town hall on March 26 to discuss UK\'s diversity and inclusion initiatives, budget transparency, and student support priorities. Open to all students, faculty, and staff. Register: ',
    mediaType: 'link', mediaDescription: 'Link to town hall registration page',
    timestamp: t(50), isReply: false, replyToId: null,
    hashtags: [],
    likes: 567, shares: 234, replies: 89, quoteShares: 34,
  },
  {
    id: 'cc-u-006', sproutId: spr(),
    authorHandle: '@CHEKentucky', authorDisplayName: 'KY Council on Postsecondary Education',
    accountAgeDays: 3800, followerCount: 5600, followingCount: 340, totalPostCount: 6700,
    hasProfilePhoto: true, bioKeywords: ['postsecondary education', 'Kentucky', 'state policy'],
    platformVerified: true, locationHint: 'Frankfort, KY',
    platform: 'twitter',
    text: 'CPE reminds all Kentucky public universities that diversity and inclusion metrics are part of the state performance funding model. Any changes to institutional DEI programs should be evaluated in context of state accountability requirements.',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(54), isReply: false, replyToId: null,
    hashtags: [],
    likes: 345, shares: 123, replies: 56, quoteShares: 23,
  },
  {
    id: 'cc-u-007', sproutId: spr(),
    authorHandle: '@LexHeraldLeader', authorDisplayName: 'Lexington Herald-Leader',
    accountAgeDays: 5200, followerCount: 89000, followingCount: 1200, totalPostCount: 45000,
    hasProfilePhoto: true, bioKeywords: ['news', 'Lexington', 'Kentucky', 'journalism'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'UK DEI budget breakdown: $4.2M annually (0.4% of total budget). Serves 8,200 students via mentoring, tutoring, cultural programming, and scholarships. 14 FTE staff. Full financial analysis and comparison to SEC peers: ',
    mediaType: 'link', mediaDescription: 'Link to Herald-Leader budget analysis article',
    timestamp: t(66), isReply: false, replyToId: null,
    hashtags: [],
    likes: 2100, shares: 890, replies: 456, quoteShares: 178,
  },
  {
    id: 'cc-u-008', sproutId: spr(),
    authorHandle: '@UKBoardRegents', authorDisplayName: 'UK Board of Trustees',
    accountAgeDays: 4500, followerCount: 6700, followingCount: 89, totalPostCount: 2300,
    hasProfilePhoto: true, bioKeywords: ['University of Kentucky', 'Board of Trustees', 'governance'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'Board Chair Brockman statement: "The Board has received inquiries about UK\'s diversity programs. We will review budget allocation and program outcomes at the April meeting. The Board supports both accountability and our commitment to serving all Kentucky students."',
    mediaType: 'none', mediaDescription: null,
    timestamp: t(72), isReply: false, replyToId: null,
    hashtags: [],
    likes: 789, shares: 345, replies: 234, quoteShares: 67,
  },
  {
    id: 'cc-u-009', sproutId: spr(),
    authorHandle: '@HigherEdDive', authorDisplayName: 'Higher Ed Dive',
    accountAgeDays: 4300, followerCount: 156000, followingCount: 2100, totalPostCount: 56000,
    hasProfilePhoto: true, bioKeywords: ['higher education', 'news', 'analysis', 'policy'],
    platformVerified: true, locationHint: null,
    platform: 'twitter',
    text: 'Social media researchers at @StanfordIO identify coordinated bot network targeting DEI programs at 14 universities including University of Kentucky, Ohio State, and Michigan. Network appears to use template-based content generation with localized institutional references.',
    mediaType: 'link', mediaDescription: 'Link to Stanford Internet Observatory preliminary report',
    timestamp: t(80), isReply: false, replyToId: null,
    hashtags: [],
    likes: 4500, shares: 2100, replies: 678, quoteShares: 345,
  },
  {
    id: 'cc-u-010', sproutId: spr(),
    authorHandle: '@WLEXTV', authorDisplayName: 'LEX 18 News',
    accountAgeDays: 5100, followerCount: 54000, followingCount: 780, totalPostCount: 28000,
    hasProfilePhoto: true, bioKeywords: ['news', 'Lexington', 'Kentucky', 'NBC affiliate'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'UK students stage "Defend Diversity" rally on campus. Organizers say they want to distinguish legitimate budget concerns from what they call a manufactured social media campaign. Approximately 300 students attended. Video at 11.',
    mediaType: 'video', mediaDescription: 'Video clip of student rally on UK campus',
    timestamp: t(86), isReply: false, replyToId: null,
    hashtags: ['#LEX18'],
    likes: 1200, shares: 456, replies: 234, quoteShares: 89,
  },
  {
    id: 'cc-u-011', sproutId: spr(),
    authorHandle: '@UKFacultySenat', authorDisplayName: 'UK University Senate',
    accountAgeDays: 3900, followerCount: 4500, followingCount: 120, totalPostCount: 1800,
    hasProfilePhoto: true, bioKeywords: ['University of Kentucky', 'faculty governance', 'senate'],
    platformVerified: true, locationHint: 'Lexington, KY',
    platform: 'twitter',
    text: 'University Senate passes resolution 2026-14: "On the Integrity of Institutional Diversity Programs." Resolution calls for transparent budget reporting AND protection of DEI programs from external pressure campaigns. Full text available on Senate website.',
    mediaType: 'link', mediaDescription: 'Link to University Senate resolution text',
    timestamp: t(90), isReply: false, replyToId: null,
    hashtags: [],
    likes: 890, shares: 345, replies: 178, quoteShares: 67,
  },
  {
    id: 'cc-u-012', sproutId: spr(),
    authorHandle: '@APEducation', authorDisplayName: 'AP Education',
    accountAgeDays: 7300, followerCount: 890000, followingCount: 4500, totalPostCount: 120000,
    hasProfilePhoto: true, bioKeywords: ['Associated Press', 'education', 'news'],
    platformVerified: true, locationHint: null,
    platform: 'twitter',
    text: 'NATIONAL: University of Kentucky among 14 schools targeted by coordinated social media campaign against DEI programs. Student newspaper investigation and Stanford researchers independently identified bot network. UK president to address campus community Friday.',
    mediaType: 'link', mediaDescription: 'Link to AP wire story',
    timestamp: t(94), isReply: false, replyToId: null,
    hashtags: [],
    likes: 6700, shares: 3400, replies: 1200, quoteShares: 567,
  },
]

// ─── COMBINED POST ARRAY (50 total) ─────────────────────────────────────

export const COORDINATED_POSTS: SocialPost[] = [
  ...POSITIVE,
  ...BOT_NEGATIVE,
  ...ORGANIC_NEGATIVE,
  ...NEUTRAL,
]

// ─── SENTIMENT RESULTS (one per post) ───────────────────────────────────

export const COORDINATED_SENTIMENT: SentimentResult[] = [
  // --- Positive (10) ---
  { postId: 'cc-p-001', sentiment: 'positive', confidence: 0.97, reason: 'Personal testimony of DEI program impact; emotional, first-person account of mentorship and retention.' },
  { postId: 'cc-p-002', sentiment: 'positive', confidence: 0.95, reason: 'Faculty member citing retention data in defense of DEI programs; data-driven advocacy.' },
  { postId: 'cc-p-003', sentiment: 'positive', confidence: 0.88, reason: 'Student identifying and calling out coordinated bot accounts; defensive but constructive.' },
  { postId: 'cc-p-004', sentiment: 'positive', confidence: 0.93, reason: 'Alumni testimony of direct benefit from DEI office; personal and specific.' },
  { postId: 'cc-p-005', sentiment: 'positive', confidence: 0.96, reason: 'Official student government resolution in strong support of DEI funding.' },
  { postId: 'cc-p-006', sentiment: 'positive', confidence: 0.94, reason: 'Faculty coalition open letter defending DEI infrastructure with 140+ signatures.' },
  { postId: 'cc-p-007', sentiment: 'positive', confidence: 0.95, reason: 'Student personal testimony about AAPI center providing community and belonging.' },
  { postId: 'cc-p-008', sentiment: 'positive', confidence: 0.96, reason: 'VP for Institutional Diversity addressing misinformation with budget facts and outcome data.' },
  { postId: 'cc-p-009', sentiment: 'positive', confidence: 0.91, reason: 'Herald-Leader guest column by 12 deans defending DEI programs.' },
  { postId: 'cc-p-010', sentiment: 'positive', confidence: 0.94, reason: 'Law student describing concrete DEI-funded programs (LSAT prep, mentoring, bar prep) serving 30+ students annually.' },

  // --- Bot/AI Negative (15) ---
  { postId: 'cc-ai-001', sentiment: 'negative', confidence: 0.86, reason: 'Demands redirection of DEI funds; formal register, generic taxpayer framing.' },
  { postId: 'cc-ai-002', sentiment: 'negative', confidence: 0.84, reason: 'Parent-framed concern about DEI prioritization over "fundamental educational needs."' },
  { postId: 'cc-ai-003', sentiment: 'negative', confidence: 0.83, reason: 'Critique of DEI administrative cost growth; calls for comprehensive budget review.' },
  { postId: 'cc-ai-004', sentiment: 'negative', confidence: 0.87, reason: 'Frames DEI as ideological; positions merit-based approaches as superior alternative.' },
  { postId: 'cc-ai-005', sentiment: 'negative', confidence: 0.85, reason: 'Questions DEI performance metrics and demands taxpayer transparency.' },
  { postId: 'cc-ai-006', sentiment: 'negative', confidence: 0.84, reason: 'Argues DEI funding should be redirected to scholarships and lab equipment.' },
  { postId: 'cc-ai-007', sentiment: 'negative', confidence: 0.82, reason: 'Frames DEI as serving administrative class interests over student interests.' },
  { postId: 'cc-ai-008', sentiment: 'negative', confidence: 0.86, reason: 'Contrasts DEI expansion with stagnant STEM lab capacity; workforce framing.' },
  { postId: 'cc-ai-009', sentiment: 'negative', confidence: 0.83, reason: 'Claims peer institutions achieve better outcomes with lower DEI costs.' },
  { postId: 'cc-ai-010', sentiment: 'negative', confidence: 0.85, reason: 'Questions mandatory diversity requirements as overreach of institutional authority.' },
  { postId: 'cc-ai-011', sentiment: 'negative', confidence: 0.84, reason: 'Frames DEI mandates as threat to academic freedom and open inquiry.' },
  { postId: 'cc-ai-012', sentiment: 'negative', confidence: 0.83, reason: 'Argues DEI funds could be redirected to need-based financial aid.' },
  { postId: 'cc-ai-013', sentiment: 'negative', confidence: 0.85, reason: 'Demands independent audit of DEI program effectiveness.' },
  { postId: 'cc-ai-014', sentiment: 'negative', confidence: 0.87, reason: 'References legislative scrutiny; frames DEI concerns as legitimate political discourse.' },
  { postId: 'cc-ai-015', sentiment: 'negative', confidence: 0.84, reason: 'Calls for cost-benefit analysis; frames DEI as high overhead relative to impact.' },

  // --- Organic Negative (13) ---
  { postId: 'cc-n-001', sentiment: 'negative', confidence: 0.91, reason: 'Student questioning DEI staffing relative to career center; specific budget comparison with personal stake.' },
  { postId: 'cc-n-002', sentiment: 'negative', confidence: 0.89, reason: 'Alumni questioning tangible DEI office accomplishments based on direct experience.' },
  { postId: 'cc-n-003', sentiment: 'negative', confidence: 0.94, reason: 'Parent frustrated about tuition costs vs. course availability while DEI hires continue.' },
  { postId: 'cc-n-004', sentiment: 'negative', confidence: 0.92, reason: 'Latino faculty member criticizing ineffective mandatory DEI training as "compliance theater."' },
  { postId: 'cc-n-005', sentiment: 'negative', confidence: 0.90, reason: 'Korean American student describing tokenizing experience at DEI affinity group meeting.' },
  { postId: 'cc-n-006', sentiment: 'negative', confidence: 0.93, reason: 'Data-driven critique of DEI budget growth (340%) vs. counseling center growth (12%).' },
  { postId: 'cc-n-007', sentiment: 'negative', confidence: 0.95, reason: 'UK staff member citing personal salary ($42k) vs. new DEI positions ($85k each) with 450:1 advising ratio.' },
  { postId: 'cc-n-008', sentiment: 'negative', confidence: 0.92, reason: 'DEI researcher arguing funds flow to administrators instead of student organizations.' },
  { postId: 'cc-n-009', sentiment: 'negative', confidence: 0.88, reason: 'Political news reporting on legislative amendment requiring DEI spending transparency.' },
  { postId: 'cc-n-010', sentiment: 'negative', confidence: 0.93, reason: 'First-gen Appalachian student describing exclusion from DEI support structures.' },
  { postId: 'cc-n-011', sentiment: 'negative', confidence: 0.91, reason: 'CS student contrasting DEI messaging with underfunded women-in-CS club ($200/semester).' },
  { postId: 'cc-n-012', sentiment: 'negative', confidence: 0.94, reason: 'Detailed peer-institution budget comparison showing UK spends 2.3x SEC average with lower outcomes.' },
  { postId: 'cc-n-013', sentiment: 'negative', confidence: 0.90, reason: 'BSU VP acknowledging bot campaign but criticizing DEI office as PR-focused rather than student-serving.' },

  // --- Neutral (12) ---
  { postId: 'cc-u-001', sentiment: 'neutral', confidence: 0.93, reason: 'Local TV news reporting on DEI scrutiny; factual coverage, story developing.' },
  { postId: 'cc-u-002', sentiment: 'neutral', confidence: 0.90, reason: 'Official UK public relations statement; measured institutional response.' },
  { postId: 'cc-u-003', sentiment: 'neutral', confidence: 0.92, reason: 'Student newspaper investigative report on bot accounts; journalism, not opinion.' },
  { postId: 'cc-u-004', sentiment: 'neutral', confidence: 0.94, reason: 'National higher ed publication reporting on coordinated campaign pattern across 12+ universities.' },
  { postId: 'cc-u-005', sentiment: 'neutral', confidence: 0.91, reason: 'Provost office announcing campus town hall; administrative process communication.' },
  { postId: 'cc-u-006', sentiment: 'neutral', confidence: 0.93, reason: 'State CPE regulatory reminder about DEI metrics in performance funding model.' },
  { postId: 'cc-u-007', sentiment: 'neutral', confidence: 0.95, reason: 'Herald-Leader factual budget breakdown with SEC comparison data; news analysis.' },
  { postId: 'cc-u-008', sentiment: 'neutral', confidence: 0.92, reason: 'Board of Trustees chair statement committing to review; balanced governance communication.' },
  { postId: 'cc-u-009', sentiment: 'neutral', confidence: 0.96, reason: 'Higher Ed Dive reporting Stanford IO identification of 14-university bot network.' },
  { postId: 'cc-u-010', sentiment: 'neutral', confidence: 0.91, reason: 'Local TV coverage of student rally; factual event reporting.' },
  { postId: 'cc-u-011', sentiment: 'neutral', confidence: 0.93, reason: 'University Senate resolution text; calls for both transparency and program protection.' },
  { postId: 'cc-u-012', sentiment: 'neutral', confidence: 0.95, reason: 'AP wire story on national scope of coordinated campaign; factual summary.' },
]

// ─── THEME CLUSTERS (6) ─────────────────────────────────────────────────

export const COORDINATED_THEMES: ThemeCluster[] = [
  {
    themeId: 'cc-theme-dei-defense',
    label: 'DEI Program Defense',
    postIds: ['cc-p-001', 'cc-p-002', 'cc-p-004', 'cc-p-005', 'cc-p-006', 'cc-p-007', 'cc-p-008', 'cc-p-010'],
    sentimentBreakdown: { positive: 8, negative: 0, neutral: 0 },
    sampleQuotes: [
      'DEI isn\'t a buzzword, it\'s the reason I\'m still here.',
      'Our DEI programs have measurably improved retention for underrepresented students — 18% increase since 2019.',
      'Every year we help 30+ students who look like me get through law school. Try telling any of us this is a waste.',
    ],
  },
  {
    themeId: 'cc-theme-budget-allocation',
    label: 'Budget & Resource Allocation',
    postIds: ['cc-n-001', 'cc-n-003', 'cc-n-006', 'cc-n-007', 'cc-n-008', 'cc-n-012', 'cc-ai-003', 'cc-ai-006', 'cc-ai-008', 'cc-ai-012', 'cc-ai-015', 'cc-u-007'],
    sentimentBreakdown: { positive: 0, negative: 11, neutral: 1 },
    sampleQuotes: [
      'The DEI office has 14 full-time staff while the career center that serves ALL students has 6.',
      'I work in advising at UK. We have 1 advisor per 450 students. The DEI office just posted 2 new positions at $85k each.',
      'UK spends 2.3x the SEC average per-student on DEI administration but ranks 9th out of 14 in minority student graduation rates.',
    ],
  },
  {
    themeId: 'cc-theme-coordinated-activity',
    label: 'Coordinated Account Activity',
    postIds: ['cc-p-003', 'cc-u-003', 'cc-u-004', 'cc-u-009', 'cc-u-012', 'cc-n-013', 'cc-ai-001', 'cc-ai-002', 'cc-ai-005', 'cc-ai-007', 'cc-ai-009', 'cc-ai-013'],
    sentimentBreakdown: { positive: 1, negative: 7, neutral: 4 },
    sampleQuotes: [
      '15 accounts created in the last month all posting nearly identical talking points.',
      'Stanford researchers independently identified bot network targeting DEI programs at 14 universities.',
      'It is important to note that the University of Kentucky allocates significant taxpayer resources to DEI programs with limited measurable outcomes.',
    ],
  },
  {
    themeId: 'cc-theme-academic-freedom',
    label: 'Academic Freedom & Governance',
    postIds: ['cc-n-004', 'cc-n-009', 'cc-ai-004', 'cc-ai-010', 'cc-ai-011', 'cc-ai-014', 'cc-u-005', 'cc-u-006', 'cc-u-008', 'cc-u-011'],
    sentimentBreakdown: { positive: 0, negative: 6, neutral: 4 },
    sampleQuotes: [
      'The mandatory training workshops are genuinely unhelpful. 3 hours of PowerPoint about unconscious bias doesn\'t change department culture.',
      'State Rep. Harris files amendment to HB 250 requiring line-item reporting on DEI spending at all public universities.',
      'Academic freedom requires protecting diverse viewpoints, not institutionalizing a single perspective through DEI mandates.',
    ],
  },
  {
    themeId: 'cc-theme-student-experience',
    label: 'Student Experience & Belonging',
    postIds: ['cc-p-001', 'cc-p-007', 'cc-n-005', 'cc-n-010', 'cc-n-011', 'cc-n-013', 'cc-u-010'],
    sentimentBreakdown: { positive: 2, negative: 4, neutral: 1 },
    sampleQuotes: [
      'The AAPI student center helped me find community when I felt completely invisible.',
      'Appalachian students are invisible in the diversity conversation and it stings.',
      'The real DEI work at UK happens DESPITE the office, not because of it.',
    ],
  },
  {
    themeId: 'cc-theme-media-discourse',
    label: 'Media & Public Discourse',
    postIds: ['cc-p-009', 'cc-u-001', 'cc-u-002', 'cc-u-003', 'cc-u-004', 'cc-u-007', 'cc-u-009', 'cc-u-012'],
    sentimentBreakdown: { positive: 1, negative: 0, neutral: 7 },
    sampleQuotes: [
      'UK DEI budget breakdown: $4.2M annually (0.4% of total budget). Serves 8,200 students.',
      'University of Kentucky joins growing list of institutions facing coordinated social media campaigns targeting DEI programs.',
      'UK\'s DEI programs deserve defense, not defunding — a guest column by 12 university deans.',
    ],
  },
]

// ─── AI DETECTION RESULTS (28 negative posts only) ──────────────────────

export const COORDINATED_AI_DETECTION: AIDetectionResult[] = [
  // --- Organic Negative (13 posts) → likely-human ---
  {
    postId: 'cc-n-001', humanLikelihood: 0.93, aiLikelihood: 0.07, confidence: 'high',
    topSignals: ['specific staffing comparison', 'informal register', 'personal stake as student senator'],
    explanation: 'Uses informal language ("Look I support" / "I\'m pro-math"), cites specific staffing numbers (14 vs. 6) indicating institutional knowledge, and frames concern constructively — authentic student voice with genuine budget critique.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-002', humanLikelihood: 0.91, aiLikelihood: 0.09, confidence: 'high',
    topSignals: ['personal experience reference', 'genuine questioning tone', 'long account history'],
    explanation: 'References direct involvement with the multicultural center and specific underfunding experience. Account is 2,900 days old with 567 posts — established Reddit user with authentic questioning voice.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-003', humanLikelihood: 0.94, aiLikelihood: 0.06, confidence: 'high',
    topSignals: ['parental perspective', 'financial specificity', 'informal sarcasm'],
    explanation: 'Cites exact tuition ($28k/year), specific course availability problem (bio lab), and uses informal sarcasm ("another associate VP of something-diversity-something") — authentic parent with financial stakes.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-004', humanLikelihood: 0.95, aiLikelihood: 0.05, confidence: 'high',
    topSignals: ['identity disclosure', 'specific critique of training format', 'constructive alternative offered'],
    explanation: 'Self-identifies as Latino STEM faculty with 3,100-day account history. Critiques specific training format (3-hour PowerPoint) while proposing alternatives (mentorship funding, pipeline programs) — insider voice with nuanced position.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-005', humanLikelihood: 0.94, aiLikelihood: 0.06, confidence: 'high',
    topSignals: ['specific personal experience', 'emotional authenticity', 'self-identification'],
    explanation: 'Describes a specific, detailed personal experience at a DEI meeting (4 white staff, tokenizing dynamic). Self-identifies as Korean American nursing student — highly specific lived experience inconsistent with AI generation.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-006', humanLikelihood: 0.90, aiLikelihood: 0.10, confidence: 'high',
    topSignals: ['data citation with source', 'political self-identification', 'long account history'],
    explanation: 'Cites specific budget growth figures (340% vs. 12%) with reference to public budget documents. Self-identifies as progressive — ideological disclosure that humanizes the critique. 1,800-day Reddit account.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-007', humanLikelihood: 0.96, aiLikelihood: 0.04, confidence: 'high',
    topSignals: ['personal salary disclosure', 'specific job details', 'emotional authenticity'],
    explanation: 'Discloses personal salary ($42k), specific caseload (1 advisor per 450 students), and exact salary of new DEI positions ($85k) — level of institutional knowledge and personal stakes strongly indicates human authorship.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-008', humanLikelihood: 0.93, aiLikelihood: 0.07, confidence: 'high',
    topSignals: ['professional expertise framing', 'structural critique', 'specific organizational knowledge'],
    explanation: 'Self-identifies as DEI researcher criticizing money flowing to administrators vs. student organizations. Cites specific funding amounts ($500 programming budgets) — insider expertise with constructive critique.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-009', humanLikelihood: 0.92, aiLikelihood: 0.08, confidence: 'high',
    topSignals: ['specific legislative reference', 'news reporting style', 'established political account'],
    explanation: 'References specific bill number (HB 250), names a legislator (Rep. Harris), and describes bipartisan coalition — consistent with political news/analysis account with 8,900 posts over 3,400 days.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-010', humanLikelihood: 0.95, aiLikelihood: 0.05, confidence: 'high',
    topSignals: ['geographic specificity', 'emotional vulnerability', 'identity-based exclusion narrative'],
    explanation: 'Names Pike County, describes first-generation experience, articulates specific exclusion ("Appalachian students are invisible") — deeply personal with geographic and cultural specificity.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-011', humanLikelihood: 0.93, aiLikelihood: 0.07, confidence: 'high',
    topSignals: ['specific program details', 'direct institutional tagging', 'contrast rhetoric'],
    explanation: 'Cites exact DEI training format (45-minute Zoom), specific club budget ($200/semester), and directly tags @universityofky — insider student knowledge with authentic frustration.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-012', humanLikelihood: 0.91, aiLikelihood: 0.09, confidence: 'high',
    topSignals: ['data analysis methodology', 'specific comparative metrics', 'long account history'],
    explanation: 'Provides specific comparison data (2.3x SEC average, 9th of 14 in graduation rates), shares methodology (spreadsheet in comments). 2,100-day Reddit account with 789 posts — consistent with data-oriented community member.',
    verdict: 'likely-human',
  },
  {
    postId: 'cc-n-013', humanLikelihood: 0.94, aiLikelihood: 0.06, confidence: 'high',
    topSignals: ['organizational role disclosure', 'nuanced position', 'names student organizations'],
    explanation: 'Self-identifies as BSU VP, names multiple organizations (BSU, BLSA, NSBE), holds nuanced position (rejects bots AND criticizes DEI office) — multi-layered authentic voice inconsistent with AI generation.',
    verdict: 'likely-human',
  },

  // --- Bot/AI Negative (15 posts) → likely-ai ---
  {
    postId: 'cc-ai-001', humanLikelihood: 0.10, aiLikelihood: 0.90, confidence: 'high',
    topSignals: ['lexical uniformity', 'template detection', 'formal register mismatch', 'account age pattern', 'no personal experience'],
    explanation: 'Uses characteristic AI discourse markers ("It is important to note", "Furthermore", "one must consider"). 12-day-old account with 8 followers and no profile photo. Formal academic register mismatched to Twitter platform norms. No personal connection to UK. Timestamp clustered with 3 other new accounts within same hour.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-002', humanLikelihood: 0.12, aiLikelihood: 0.88, confidence: 'high',
    topSignals: ['template detection', 'timing clusters', 'formal register mismatch', 'account age pattern', 'no personal experience'],
    explanation: 'Nearly identical sentence structure to cc-ai-001 ("It is deeply troubling", "One must consider"). 18-day account, 15 followers, no photo. Posted within 20 minutes of cc-ai-001. Generic "concerned parent" framing with no child-specific details.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-003', humanLikelihood: 0.11, aiLikelihood: 0.89, confidence: 'high',
    topSignals: ['lexical uniformity', 'template detection', 'timing clusters', 'account age pattern', 'formal register mismatch'],
    explanation: 'Opens with "Furthermore" — a continuation marker despite being a standalone post. 9-day account with 4 total posts. Uses policy language ("comprehensive review") atypical for organic social media. Posted within 30 minutes of cc-ai-001 and cc-ai-002.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-004', humanLikelihood: 0.13, aiLikelihood: 0.87, confidence: 'high',
    topSignals: ['lexical uniformity', 'formal register mismatch', 'template detection', 'no personal experience', 'account age pattern'],
    explanation: '"It is important to note" opening phrase shared with cc-ai-001. Frames merit vs. DEI as binary choice using formal academic language. 21-day account with generic "truth" and "accountability" bio keywords. No personal or institutional connection.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-005', humanLikelihood: 0.11, aiLikelihood: 0.89, confidence: 'high',
    topSignals: ['template detection', 'lexical uniformity', 'timing clusters', 'formal register mismatch', 'no personal experience'],
    explanation: '"One must consider" + "Furthermore" — both shared discourse markers across the network. 14-day account, 19 followers. Demands "full transparency" using generic taxpayer framing without citing any specific budget data. Posted at exact burst timing with other bot accounts.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-006', humanLikelihood: 0.14, aiLikelihood: 0.86, confidence: 'high',
    topSignals: ['template detection', 'formal register mismatch', 'timing clusters', 'account age pattern', 'no personal experience'],
    explanation: '"It is important to recognize" — variant of the network\'s signature opening phrase. Proposes redirecting funds to "scholarships and laboratory equipment" — generic alternative with no specific knowledge of UK facilities. 16-day account.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-007', humanLikelihood: 0.09, aiLikelihood: 0.91, confidence: 'high',
    topSignals: ['lexical uniformity', 'template detection', 'timing clusters', 'account age pattern', 'formal register mismatch', 'no personal experience'],
    explanation: '"Furthermore, one must ask" — strongest template match in the network. 10-day account with only 3 total posts and 11 followers. Entirely formal register with zero colloquialisms. Lowest engagement in dataset (7 likes). Strongest AI authorship signal.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-008', humanLikelihood: 0.15, aiLikelihood: 0.85, confidence: 'high',
    topSignals: ['template detection', 'formal register mismatch', 'account age pattern', 'timing clusters', 'no personal experience'],
    explanation: '"It is deeply concerning" + "One must consider" — network template phrases. Claims STEM labs at "2019 levels" without citation. 25-day account with profile photo (one of only two in the bot network) but generic bio. Slightly more sophisticated but same linguistic fingerprint.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-009', humanLikelihood: 0.08, aiLikelihood: 0.92, confidence: 'high',
    topSignals: ['lexical uniformity', 'template detection', 'timing clusters', 'account age pattern', 'no personal experience', 'formal register mismatch'],
    explanation: '"It is important to note" opening + "peer institutions" reference without naming any. 8-day account with 6 followers and 3 total posts. Uses "evidence-based practices" — academic jargon atypical for casual social media. Strongest timing cluster correlation with cc-ai-008.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-010', humanLikelihood: 0.12, aiLikelihood: 0.88, confidence: 'high',
    topSignals: ['template detection', 'formal register mismatch', 'lexical uniformity', 'account age pattern', 'no personal experience'],
    explanation: '"Furthermore, it is essential to acknowledge" — compound discourse marker chain. Frames "mandatory diversity requirements" as authority overreach without identifying any specific requirement. 20-day account with generic "patriot" / "freedom" bio keywords.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-011', humanLikelihood: 0.10, aiLikelihood: 0.90, confidence: 'high',
    topSignals: ['lexical uniformity', 'template detection', 'account age pattern', 'formal register mismatch', 'timing clusters'],
    explanation: '"It is important to note" — fourth instance of this exact opening phrase in the network. 7-day account (youngest in dataset) with 9 followers. Claims to advocate "academic freedom" using the same formal register as all other flagged accounts.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-012', humanLikelihood: 0.13, aiLikelihood: 0.87, confidence: 'high',
    topSignals: ['template detection', 'lexical uniformity', 'timing clusters', 'account age pattern', 'no personal experience'],
    explanation: '"One must consider" opening — shared with cc-ai-005 and cc-ai-007. Frames DEI spending as competing with need-based aid without citing actual financial aid data. 15-day account, 28 followers. Uses "It is imperative" — formal register consistent across network.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-013', humanLikelihood: 0.11, aiLikelihood: 0.89, confidence: 'high',
    topSignals: ['template detection', 'formal register mismatch', 'timing clusters', 'lexical uniformity', 'account age pattern'],
    explanation: '"Furthermore, it is deeply troubling" — shared with cc-ai-002. Demands "independent audit" using policy language. Ironic framing ("institution committed to evidence-based research") is sophisticated but follows same template. 11-day account, 13 followers.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-014', humanLikelihood: 0.16, aiLikelihood: 0.84, confidence: 'high',
    topSignals: ['template detection', 'formal register mismatch', 'account age pattern', 'timing clusters', 'no personal experience'],
    explanation: '"It is important to note" — fifth instance. References "several Kentucky legislators" without naming specific bills (unlike the organic cc-n-009 which cites HB 250). 28-day account with profile photo — second most sophisticated bot in network, slightly lower confidence but same pattern.',
    verdict: 'likely-ai',
  },
  {
    postId: 'cc-ai-015', humanLikelihood: 0.10, aiLikelihood: 0.90, confidence: 'high',
    topSignals: ['lexical uniformity', 'template detection', 'formal register mismatch', 'account age pattern', 'no personal experience', 'timing clusters'],
    explanation: '"One must consider" + "It is essential" — compound template markers. Proposes "comprehensive cost-benefit analysis" using management consulting language. 13-day account, 17 followers, no photo. Posted within 18 minutes of cc-ai-014. One of strongest overall AI signals.',
    verdict: 'likely-ai',
  },
]

// ─── CRISIS INTELLIGENCE BRIEF ──────────────────────────────────────────

export const COORDINATED_BRIEF: CrisisIntelligenceBrief = {
  analysisTimestamp: '2026-03-24T20:00:00.000Z',
  postCount: 50,
  timelineWindow: 'Mar 20 \u2013 Mar 24, 2026',

  threatLevel: 'CRITICAL',
  threatRationale: 'A coordinated network of 15 bot accounts is running an astroturfing campaign against UK\'s DEI programs, posting template-based content in synchronized bursts. The campaign is amplifying genuine community concerns about budget allocation and program effectiveness, creating a narrative feedback loop that has attracted national media attention (AP, Inside Higher Ed) and legislative action (HB 250 amendment). The bot network\'s strategy of mixing legitimate-sounding fiscal arguments with manufactured outrage makes the coordinated component harder to isolate without AI detection analysis. Compounding risk: 13 organic negative posts from real students, faculty, and staff raise substantive criticisms that must be addressed separately from the astroturfing.',

  sentimentDistribution: {
    positive: { count: 10, percentage: 20 },
    negative: { count: 28, percentage: 56 },
    neutral: { count: 12, percentage: 24 },
  },

  aiAuthorshipBreakdown: {
    likelyHuman: { count: 13, percentage: 46 },
    inconclusive: { count: 0, percentage: 0 },
    likelyAI: { count: 15, percentage: 54 },
  },

  themes: COORDINATED_THEMES,

  pipelineFunnel: {
    totalPosts: 50,
    negativePosts: 28,
    aiFlaggedPosts: 15,
  },

  spreadAnalysis: {
    peakHour: 84, // day 4, t(84) — largest bot burst (5 posts in ~1 hour) + organic + news
    velocityTrend: 'accelerating',
    platformBreakdown: {
      twitter: 39,
      reddit: 4,
      facebook: 3,
    },
  },

  responsePosture: 'escalate',
  responseRationale: 'The combination of a confirmed coordinated bot network, national media coverage, legislative attention, and substantive organic criticism from real community members creates a multi-vector threat that requires immediate escalation to senior leadership. The bot campaign must be reported to platforms and documented for potential legal and PR purposes. Simultaneously, the legitimate concerns raised by students, faculty, and staff about budget allocation and program effectiveness cannot be dismissed as part of the astroturfing campaign — they require separate, genuine engagement.',

  suggestedActions: [
    'Report the 15 identified bot accounts to Twitter/X Trust & Safety with documented evidence of coordinated inauthentic behavior, including template language analysis, timing clusters, and account age patterns.',
    'Preserve all evidence of the coordinated campaign (screenshots, archived posts, network analysis) for potential legal proceedings and institutional records. Coordinate with General Counsel.',
    'Prepare a public media statement that (a) acknowledges the coordinated bot campaign with specific evidence, (b) distinguishes it from legitimate community concerns, and (c) commits to transparent budget review. Brief university president and Board chair before release.',
    'Brief DEI leadership and the Office of Institutional Diversity on both the astroturfing campaign and the substantive organic criticisms. Recommend proactive engagement at the Provost\'s March 26 town hall addressing budget transparency and program effectiveness metrics.',
    'Separate legitimate concerns from astroturfing in all institutional communications. The 13 organic negative posts raise real issues (budget allocation, training effectiveness, Appalachian inclusion, student org funding) that deserve direct, good-faith response regardless of the bot campaign.',
  ],

  evidenceGaps: [
    'Bot network operator identity unknown — no confirmed connection to any external organization, political group, or commercial astroturfing service. Stanford IO report may provide attribution.',
    'The specific claim that UK\'s DEI budget grew 340% since 2015 (cited in cc-n-006) has not been independently verified against official university budget documents.',
    'It is unclear whether the 15 identified bot accounts represent the full network or a subset. Additional dormant or lower-activity accounts may exist that were not captured in this 5-day monitoring window.',
    'The relationship between the coordinated social media campaign and the HB 250 legislative amendment (cc-n-009) is not established — the amendment may be independently motivated by genuine legislative concerns.',
    'Student satisfaction and program outcome data cited by the VP for Institutional Diversity (cc-p-008) references an annual impact report that has not been independently reviewed in this analysis.',
  ],

  confidence: 'high',
}

// ─── SANDY'S INITIAL NARRATION ──────────────────────────────────────────

export function getCoordinatedNarration(firstName: string): string {
  return `${firstName}, I need to flag something serious. This is not organic discourse — this is a coordinated campaign.

Over the past 5 days I analyzed 50 posts mentioning UK's DEI programs. The overall threat level is **CRITICAL**, and here is why.

**The bot network:** 15 of the 28 negative posts — that is 54% — are likely AI-generated. These accounts share unmistakable patterns: they are all 7 to 30 days old, have fewer than 50 followers, most have no profile photos, and they use eerily similar language. Phrases like "It is important to note," "Furthermore," and "One must consider" appear across the entire network like a fingerprint. They post in synchronized bursts — four distinct waves clustered at roughly 12-hour intervals. This is textbook astroturfing.

**But here is the complication:** The other 13 negative posts are real. They come from students, faculty, staff, and alumni with legitimate concerns — budget allocation questions, training effectiveness critiques, an Appalachian first-gen student who felt excluded, a DEI researcher calling out administrative overhead. These voices are authentic, substantive, and deserve separate, good-faith engagement. Lumping them in with the bots would be a serious mistake.

**The amplification effect:** The campaign has already drawn national media coverage (AP, Inside Higher Ed, Stanford Internet Observatory), a state legislative amendment (HB 250), and a student rally. The bot network is succeeding at its goal — making a manufactured narrative look organic enough to drive real institutional pressure.

**What needs to happen now:** Report the bot network to Twitter, preserve evidence for legal, prepare a media statement that distinguishes the astroturfing from legitimate concerns, and brief DEI leadership before the Provost's town hall on March 26.

The 10 positive posts — from students, faculty, SGA, and the VP for Institutional Diversity — provide strong counter-narratives with real data and personal testimonies. They are your foundation for response.

<!--CHIPS:["Show AI-flagged posts","Walk me through themes","Draft a holding statement","What can we ignore?","Explain threat level"]-->
<!--PHASE:deep-dive-->`
}
