/**
 * Sprout Social-style 7-day monitoring data
 *
 * 50 posts across Mar 18–25 2026, all referencing University of Kentucky.
 * Distribution: ~20 positive, ~18 negative (4-6 intentionally AI-sounding), ~12 neutral.
 * Platforms: Twitter/X, Reddit, Facebook, Instagram, TikTok, news-comment.
 */

import type { SocialPost } from '../types'

const DAY_0 = '2026-03-18T08:00:00Z'

/** Helper: offset from day 0 in hours */
function t(hoursAfter: number): string {
  return new Date(new Date(DAY_0).getTime() + hoursAfter * 3_600_000).toISOString()
}

let sproutSeq = 900000

function spr(): string {
  return `spr_${++sproutSeq}`
}

// ─── POSITIVE POSTS (~20) ────────────────────────────────────────────────

const POSITIVE: SocialPost[] = [
  {
    id: 'sp-001', sproutId: spr(),
    authorHandle: '@BBNforever_21', authorDisplayName: 'Marcus Johnson',
    accountAgeDays: 1456, followerCount: 387, followingCount: 290, totalPostCount: 2840,
    hasProfilePhoto: true, bioKeywords: ['UK', 'BBN', 'class of 2027'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Rupp Arena was ELECTRIC last night 🔥 This team is something special. #BBN #WeAreUK', mediaType: 'image', mediaDescription: 'Photo of Rupp Arena crowd in blue',
    timestamp: t(2), isReply: false, replyToId: null, hashtags: ['#BBN', '#WeAreUK'],
    likes: 342, shares: 89, replies: 23, quoteShares: 12,
  },
  {
    id: 'sp-002', sproutId: spr(),
    authorHandle: '@WildcatChemist', authorDisplayName: 'Dr. Rachel Kim',
    accountAgeDays: 2100, followerCount: 1245, followingCount: 320, totalPostCount: 890,
    hasProfilePhoto: true, bioKeywords: ['Chemistry professor', 'UK', 'research'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'So proud of my lab — our paper on polymer nanostructures just got accepted in JACS! UK research punching above its weight 💪 #UKResearch', mediaType: 'link', mediaDescription: 'Link to JACS paper abstract',
    timestamp: t(14), isReply: false, replyToId: null, hashtags: ['#UKResearch'],
    likes: 567, shares: 123, replies: 45, quoteShares: 34,
  },
  {
    id: 'sp-003', sproutId: spr(),
    authorHandle: '@lexington_eats', authorDisplayName: 'Lexington Foodie',
    accountAgeDays: 980, followerCount: 4500, followingCount: 612, totalPostCount: 3200,
    hasProfilePhoto: true, bioKeywords: ['food', 'Lexington', 'restaurants'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'instagram', text: 'The new coffee bar at WT Young Library is actually amazing?? Cold brew + studying = perfect combo ☕📚 #UKY #LexingtonKY', mediaType: 'image', mediaDescription: 'Photo of coffee bar inside library',
    timestamp: t(26), isReply: false, replyToId: null, hashtags: ['#UKY', '#LexingtonKY'],
    likes: 891, shares: 56, replies: 34, quoteShares: 0,
  },
  {
    id: 'sp-004', sproutId: spr(),
    authorHandle: '@SarahGrad2026', authorDisplayName: 'Sarah Mitchell',
    accountAgeDays: 1600, followerCount: 210, followingCount: 345, totalPostCount: 1200,
    hasProfilePhoto: true, bioKeywords: ['UK senior', 'nursing', 'first gen'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'I JUST GOT INTO UK\'S DNP PROGRAM!! First in my family to go to grad school. I\'m literally crying in the parking lot at Good Sam rn 😭🎉 #GoBigBlue', mediaType: 'none', mediaDescription: null,
    timestamp: t(38), isReply: false, replyToId: null, hashtags: ['#GoBigBlue'],
    likes: 1245, shares: 198, replies: 87, quoteShares: 45,
  },
  {
    id: 'sp-005', sproutId: spr(),
    authorHandle: 'u/wildcat_alumni_04', authorDisplayName: 'wildcat_alumni_04',
    accountAgeDays: 3400, followerCount: 0, followingCount: 0, totalPostCount: 456,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false,
    locationHint: null,
    platform: 'reddit', text: 'Drove through campus this weekend for the first time in years. The new science building is incredible. UK has really transformed since I graduated. Makes me proud to be an alum.', mediaType: 'none', mediaDescription: null,
    timestamp: t(50), isReply: false, replyToId: null, hashtags: [],
    likes: 89, shares: 0, replies: 23, quoteShares: 0,
  },
  {
    id: 'sp-006', sproutId: spr(),
    authorHandle: '@UKDanceBlue', authorDisplayName: 'DanceBlue Official',
    accountAgeDays: 4500, followerCount: 12300, followingCount: 890, totalPostCount: 6700,
    hasProfilePhoto: true, bioKeywords: ['DanceBlue', 'UK', 'pediatric cancer'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: '24 HOURS COMPLETE!! $1.8 million raised for the Golden Matrix Fund! You did it, Wildcats! Every dollar fights pediatric cancer. #DanceBlue #FTK', mediaType: 'image', mediaDescription: 'DanceBlue final total reveal',
    timestamp: t(62), isReply: false, replyToId: null, hashtags: ['#DanceBlue', '#FTK'],
    likes: 3456, shares: 1200, replies: 234, quoteShares: 189,
  },
  {
    id: 'sp-007', sproutId: spr(),
    authorHandle: '@CATSAIlab', authorDisplayName: 'CATS-AI Lab',
    accountAgeDays: 600, followerCount: 890, followingCount: 120, totalPostCount: 340,
    hasProfilePhoto: true, bioKeywords: ['AI', 'education', 'UK', 'innovation'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Our AI-powered student tools just hit 10,000 active sessions this semester. Proud of what this team is building for UK students. 🧠✨', mediaType: 'none', mediaDescription: null,
    timestamp: t(74), isReply: false, replyToId: null, hashtags: [],
    likes: 234, shares: 67, replies: 18, quoteShares: 9,
  },
  {
    id: 'sp-008', sproutId: spr(),
    authorHandle: '@LexHeraldLeader', authorDisplayName: 'Lexington Herald-Leader',
    accountAgeDays: 5200, followerCount: 89000, followingCount: 1200, totalPostCount: 45000,
    hasProfilePhoto: true, bioKeywords: ['news', 'Lexington', 'Kentucky'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'UK\'s Markey Cancer Center receives $45M NIH grant for Appalachian cancer research — the largest in the center\'s history.', mediaType: 'link', mediaDescription: 'Herald-Leader article link',
    timestamp: t(86), isReply: false, replyToId: null, hashtags: [],
    likes: 1890, shares: 456, replies: 67, quoteShares: 123,
  },
  {
    id: 'sp-009', sproutId: spr(),
    authorHandle: '@BluegrassBarista', authorDisplayName: 'Jess Morales',
    accountAgeDays: 780, followerCount: 156, followingCount: 289, totalPostCount: 920,
    hasProfilePhoto: true, bioKeywords: ['UK sophomore', 'barista', 'art history'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'instagram', text: 'The arboretum in spring is genuinely one of the most beautiful places in Kentucky 🌸 Grateful to go to school here every single day', mediaType: 'image', mediaDescription: 'Cherry blossoms at UK Arboretum',
    timestamp: t(98), isReply: false, replyToId: null, hashtags: [],
    likes: 456, shares: 34, replies: 12, quoteShares: 0,
  },
  {
    id: 'sp-010', sproutId: spr(),
    authorHandle: '@CoachAshley_UK', authorDisplayName: 'Ashley Martin',
    accountAgeDays: 1900, followerCount: 3400, followingCount: 450, totalPostCount: 2100,
    hasProfilePhoto: true, bioKeywords: ['UK Softball', 'coach', 'SEC'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'SERIES SWEEP! These ladies just keep competing. So proud of this group. See y\'all at John Cropp next weekend! #BBN 🥎', mediaType: 'none', mediaDescription: null,
    timestamp: t(110), isReply: false, replyToId: null, hashtags: ['#BBN'],
    likes: 567, shares: 98, replies: 34, quoteShares: 23,
  },
  {
    id: 'sp-011', sproutId: spr(),
    authorHandle: '@PreMedPanic', authorDisplayName: 'Diya Patel',
    accountAgeDays: 1100, followerCount: 198, followingCount: 267, totalPostCount: 1560,
    hasProfilePhoto: true, bioKeywords: ['UK', 'pre-med', 'bio major'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Shoutout to Dr. Hammond for the most fire organic chemistry review session. Finally understand mechanisms. UK has some genuinely great professors', mediaType: 'none', mediaDescription: null,
    timestamp: t(122), isReply: false, replyToId: null, hashtags: [],
    likes: 123, shares: 12, replies: 8, quoteShares: 3,
  },
  {
    id: 'sp-012', sproutId: spr(),
    authorHandle: '@UKAlumniAssoc', authorDisplayName: 'UK Alumni Association',
    accountAgeDays: 5000, followerCount: 34000, followingCount: 2100, totalPostCount: 12000,
    hasProfilePhoto: true, bioKeywords: ['UK', 'alumni', 'Wildcats'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'facebook', text: 'Wildcats helping Wildcats! Our alumni mentorship program just matched its 5,000th pair. Current students: sign up at ukalumni.net/mentor to get connected with a mentor in your field.', mediaType: 'link', mediaDescription: 'Alumni mentorship signup page',
    timestamp: t(134), isReply: false, replyToId: null, hashtags: [],
    likes: 234, shares: 89, replies: 23, quoteShares: 0,
  },
  {
    id: 'sp-013', sproutId: spr(),
    authorHandle: '@tiktok_wildcats', authorDisplayName: 'UK Campus Life',
    accountAgeDays: 400, followerCount: 18000, followingCount: 120, totalPostCount: 340,
    hasProfilePhoto: true, bioKeywords: ['UK', 'campus life', 'student org'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'tiktok', text: 'POV: It\'s 2am at WT Young and the whole 4th floor is studying for orgo together 😭💀 This is community #UKY #StudyTok #CollegeLife', mediaType: 'video', mediaDescription: 'TikTok of students studying in library',
    timestamp: t(140), isReply: false, replyToId: null, hashtags: ['#UKY', '#StudyTok', '#CollegeLife'],
    likes: 23000, shares: 4500, replies: 890, quoteShares: 0,
  },
  {
    id: 'sp-014', sproutId: spr(),
    authorHandle: '@UKEntomology', authorDisplayName: 'UK Entomology Dept',
    accountAgeDays: 3200, followerCount: 5600, followingCount: 890, totalPostCount: 4500,
    hasProfilePhoto: true, bioKeywords: ['entomology', 'UK', 'bugs', 'research'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Our annual Insect Fair is this Saturday! 🐛 Free admission, live insect petting zoo, and taste-testing of cricket cookies. Bring the whole family to the Ag North building 10am-3pm', mediaType: 'image', mediaDescription: 'Insect Fair flyer',
    timestamp: t(146), isReply: false, replyToId: null, hashtags: [],
    likes: 345, shares: 123, replies: 34, quoteShares: 12,
  },
  {
    id: 'sp-015', sproutId: spr(),
    authorHandle: '@KYProud_Mom', authorDisplayName: 'Linda Baker',
    accountAgeDays: 2800, followerCount: 167, followingCount: 390, totalPostCount: 2300,
    hasProfilePhoto: true, bioKeywords: ['mom', 'Kentucky', 'UK parent'], platformVerified: false,
    locationHint: 'Louisville, KY',
    platform: 'facebook', text: 'Just left UK\'s admitted students day with my son. The campus tour guide was phenomenal and the engineering facilities blew us away. He\'s definitely going to be a Wildcat! 💙🤍', mediaType: 'image', mediaDescription: 'Photo of mom and son on campus',
    timestamp: t(152), isReply: false, replyToId: null, hashtags: [],
    likes: 456, shares: 23, replies: 67, quoteShares: 0,
  },
  {
    id: 'sp-016', sproutId: spr(),
    authorHandle: 'u/uk_band_nerd', authorDisplayName: 'uk_band_nerd',
    accountAgeDays: 890, followerCount: 0, followingCount: 0, totalPostCount: 234,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false,
    locationHint: null,
    platform: 'reddit', text: 'Wildcat Marching Band spring concert was unreal tonight. The Sinfonía Nº 1 arrangement gave me chills. If you missed it, they\'re doing an encore show next Friday. Seriously, go.', mediaType: 'none', mediaDescription: null,
    timestamp: t(155), isReply: false, replyToId: null, hashtags: [],
    likes: 67, shares: 0, replies: 12, quoteShares: 0,
  },
  {
    id: 'sp-017', sproutId: spr(),
    authorHandle: '@ChandlerMD_UK', authorDisplayName: 'Dr. Mike Chandler',
    accountAgeDays: 4200, followerCount: 2300, followingCount: 780, totalPostCount: 1800,
    hasProfilePhoto: true, bioKeywords: ['UK College of Medicine', 'physician', 'education'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Match Day results are in — 97% of our graduating class matched into their top 3 choices! UK College of Medicine students, you make us proud every year 🩺 #MatchDay2026', mediaType: 'none', mediaDescription: null,
    timestamp: t(158), isReply: false, replyToId: null, hashtags: ['#MatchDay2026'],
    likes: 890, shares: 234, replies: 56, quoteShares: 45,
  },
  {
    id: 'sp-018', sproutId: spr(),
    authorHandle: '@EquestrianCat', authorDisplayName: 'Megan O\'Brien',
    accountAgeDays: 1300, followerCount: 890, followingCount: 345, totalPostCount: 2100,
    hasProfilePhoto: true, bioKeywords: ['UK equestrian', 'horses', 'SEC'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'instagram', text: 'This team 🤝 SEC Championship trophy. Not bad for a Tuesday. #BBN #UKEquestrian #HorseCapital', mediaType: 'image', mediaDescription: 'Team photo with SEC trophy',
    timestamp: t(160), isReply: false, replyToId: null, hashtags: ['#BBN', '#UKEquestrian', '#HorseCapital'],
    likes: 2340, shares: 456, replies: 89, quoteShares: 0,
  },
]

// ─── NEGATIVE POSTS (~18, including 5 AI-sounding) ──────────────────────

const NEGATIVE: SocialPost[] = [
  // --- Organic negative (13 posts) ---
  {
    id: 'sn-001', sproutId: spr(),
    authorHandle: '@ParkingLotRage', authorDisplayName: 'Tyler Brooks',
    accountAgeDays: 1200, followerCount: 134, followingCount: 278, totalPostCount: 1890,
    hasProfilePhoto: true, bioKeywords: ['UK junior', 'accounting'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Got my THIRD parking ticket this month at UK. I have an E permit. I parked in an E lot. The sign was covered by a bush. This is a SCAM.', mediaType: 'image', mediaDescription: 'Photo of parking ticket on windshield',
    timestamp: t(5), isReply: false, replyToId: null, hashtags: [],
    likes: 456, shares: 123, replies: 67, quoteShares: 34,
  },
  {
    id: 'sn-002', sproutId: spr(),
    authorHandle: '@hangry_wildcat', authorDisplayName: 'Zoe Nguyen',
    accountAgeDays: 890, followerCount: 210, followingCount: 345, totalPostCount: 1200,
    hasProfilePhoto: true, bioKeywords: ['UK', 'biochem', 'foodie'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Champion\'s Kitchen served something they called "chicken parmesan" today and I genuinely cannot identify what animal it came from. UK dining is a war crime 💀', mediaType: 'image', mediaDescription: 'Photo of unidentifiable cafeteria food',
    timestamp: t(18), isReply: false, replyToId: null, hashtags: [],
    likes: 890, shares: 234, replies: 112, quoteShares: 56,
  },
  {
    id: 'sn-003', sproutId: spr(),
    authorHandle: 'u/uk_housing_nightmare', authorDisplayName: 'uk_housing_nightmare',
    accountAgeDays: 45, followerCount: 0, followingCount: 0, totalPostCount: 3,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false,
    locationHint: null,
    platform: 'reddit', text: 'Mold. In my dorm. For the FOURTH time this year. Blanding Tower room 614. I\'ve submitted maintenance requests, emailed housing, called the front desk. Nothing. I have asthma and I\'m sleeping in a room with black mold. This is not okay.', mediaType: 'none', mediaDescription: null,
    timestamp: t(30), isReply: false, replyToId: null, hashtags: [],
    likes: 567, shares: 0, replies: 89, quoteShares: 0,
  },
  {
    id: 'sn-004', sproutId: spr(),
    authorHandle: '@FirstGenStruggles', authorDisplayName: 'Aisha Williams',
    accountAgeDays: 670, followerCount: 98, followingCount: 230, totalPostCount: 780,
    hasProfilePhoto: true, bioKeywords: ['first gen', 'UK', 'social work'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Tuition going up AGAIN next year??? Some of us are already working 3 jobs. UK admin living in a different reality fr. #UKY', mediaType: 'none', mediaDescription: null,
    timestamp: t(42), isReply: false, replyToId: null, hashtags: ['#UKY'],
    likes: 1234, shares: 456, replies: 189, quoteShares: 78,
  },
  {
    id: 'sn-005', sproutId: spr(),
    authorHandle: '@WilsonCountyDad', authorDisplayName: 'Greg Patterson',
    accountAgeDays: 3400, followerCount: 234, followingCount: 567, totalPostCount: 4500,
    hasProfilePhoto: true, bioKeywords: ['dad', 'taxpayer', 'Kentucky'], platformVerified: false,
    locationHint: 'Lebanon, KY',
    platform: 'facebook', text: 'My daughter can\'t get into any of her required classes because UK oversold enrollment AGAIN. She\'ll be here an extra semester now at MY expense. When does the Board of Trustees start answering for this?', mediaType: 'none', mediaDescription: null,
    timestamp: t(54), isReply: false, replyToId: null, hashtags: [],
    likes: 345, shares: 123, replies: 89, quoteShares: 0,
  },
  {
    id: 'sn-006', sproutId: spr(),
    authorHandle: '@NightOwlUK', authorDisplayName: 'Chris Reeves',
    accountAgeDays: 1400, followerCount: 156, followingCount: 234, totalPostCount: 2100,
    hasProfilePhoto: true, bioKeywords: ['UK grad student', 'history'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Walking back from the library at 11pm and the path between Whitehall and the chemistry building has ZERO lighting. I\'ve reported this twice. Someone is going to get hurt. @UKPolice', mediaType: 'none', mediaDescription: null,
    timestamp: t(67), isReply: false, replyToId: null, hashtags: [],
    likes: 678, shares: 234, replies: 56, quoteShares: 23,
  },
  {
    id: 'sn-007', sproutId: spr(),
    authorHandle: '@DisappointedAlum88', authorDisplayName: 'Robert Caldwell',
    accountAgeDays: 2800, followerCount: 345, followingCount: 456, totalPostCount: 3400,
    hasProfilePhoto: true, bioKeywords: ['UK class of 1988', 'business owner'], platformVerified: false,
    locationHint: 'Frankfort, KY',
    platform: 'facebook', text: 'UK just sent me ANOTHER fundraising email while my son\'s advisor hasn\'t returned his email in 3 weeks. Maybe redirect some of that development office energy toward actually advising students.', mediaType: 'none', mediaDescription: null,
    timestamp: t(80), isReply: false, replyToId: null, hashtags: [],
    likes: 567, shares: 178, replies: 89, quoteShares: 0,
  },
  {
    id: 'sn-008', sproutId: spr(),
    authorHandle: '@LexSafeStreets', authorDisplayName: 'Lex Safe Streets Coalition',
    accountAgeDays: 890, followerCount: 2300, followingCount: 456, totalPostCount: 1200,
    hasProfilePhoto: true, bioKeywords: ['safety', 'Lexington', 'pedestrian'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Another student struck by a car on Winslow St near campus. Third incident this semester. @UnivKentucky when will you work with @lexaboreal to fix this intersection? Data shows 14 near-misses this year alone.', mediaType: 'link', mediaDescription: 'Link to incident report',
    timestamp: t(92), isReply: false, replyToId: null, hashtags: [],
    likes: 890, shares: 345, replies: 67, quoteShares: 56,
  },
  {
    id: 'sn-009', sproutId: spr(),
    authorHandle: '@UK_Adjunct_Life', authorDisplayName: 'Anonymous Adjunct',
    accountAgeDays: 200, followerCount: 89, followingCount: 120, totalPostCount: 340,
    hasProfilePhoto: false, bioKeywords: ['adjunct', 'higher ed', 'UK'], platformVerified: false,
    locationHint: null,
    platform: 'twitter', text: 'Teaching 4 sections at UK for $12k/semester with no benefits while the football coach makes $8M. I love my students but this institution does not value teaching.', mediaType: 'none', mediaDescription: null,
    timestamp: t(105), isReply: false, replyToId: null, hashtags: [],
    likes: 2340, shares: 890, replies: 234, quoteShares: 123,
  },
  {
    id: 'sn-010', sproutId: spr(),
    authorHandle: '@CampusCritter', authorDisplayName: 'Dylan Hart',
    accountAgeDays: 670, followerCount: 145, followingCount: 267, totalPostCount: 890,
    hasProfilePhoto: true, bioKeywords: ['UK sophomore', 'wildlife bio'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'UK just paved over the pollinator garden behind the Ag building for MORE parking. This was a teaching garden used by 3 departments. Nobody was consulted. admin only cares about $$', mediaType: 'image', mediaDescription: 'Before/after photos of paved garden',
    timestamp: t(118), isReply: false, replyToId: null, hashtags: [],
    likes: 1456, shares: 567, replies: 189, quoteShares: 89,
  },
  {
    id: 'sn-011', sproutId: spr(),
    authorHandle: '@GradWorkerUnion', authorDisplayName: 'UK Graduate Workers United',
    accountAgeDays: 340, followerCount: 1200, followingCount: 345, totalPostCount: 560,
    hasProfilePhoto: true, bioKeywords: ['grad workers', 'UK', 'labor'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'UK grad workers make 40% below the living wage for Fayette County. We filed our petition today. 87% of eligible workers signed cards. The university can\'t ignore us anymore. #GradWorkersUnite', mediaType: 'image', mediaDescription: 'Photo of petition delivery',
    timestamp: t(130), isReply: false, replyToId: null, hashtags: ['#GradWorkersUnite'],
    likes: 1890, shares: 678, replies: 234, quoteShares: 123,
  },
  {
    id: 'sn-012', sproutId: spr(),
    authorHandle: '@TiredTA_UK', authorDisplayName: 'Exhausted TA',
    accountAgeDays: 560, followerCount: 78, followingCount: 189, totalPostCount: 450,
    hasProfilePhoto: true, bioKeywords: ['TA', 'UK', 'english dept'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Just spent my weekend grading 120 essays for $800/month. My students deserve better feedback and I deserve a living wage. Something has to give. @UnivKentucky', mediaType: 'none', mediaDescription: null,
    timestamp: t(142), isReply: false, replyToId: null, hashtags: [],
    likes: 890, shares: 345, replies: 67, quoteShares: 45,
  },
  {
    id: 'sn-013', sproutId: spr(),
    authorHandle: '@AccessibilityNow', authorDisplayName: 'UK Disability Alliance',
    accountAgeDays: 560, followerCount: 890, followingCount: 234, totalPostCount: 780,
    hasProfilePhoto: true, bioKeywords: ['disability', 'accessibility', 'UK'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'The elevator in Patterson Office Tower has been broken for 6 WEEKS. Students in wheelchairs can\'t access their professors\' offices on floors 8-18. We\'ve contacted facilities, provost, and ADA office. Nothing. #AccessibilityMatters', mediaType: 'none', mediaDescription: null,
    timestamp: t(150), isReply: false, replyToId: null, hashtags: ['#AccessibilityMatters'],
    likes: 2100, shares: 890, replies: 234, quoteShares: 145,
  },

  // --- AI-sounding negative posts (5 posts) ---
  {
    id: 'sn-ai-001', sproutId: spr(),
    authorHandle: '@ConcernedKentuckian_', authorDisplayName: 'Concerned Citizen',
    accountAgeDays: 34, followerCount: 12, followingCount: 2, totalPostCount: 8,
    hasProfilePhoto: false, bioKeywords: ['concerned', 'taxpayer', 'Kentucky'], platformVerified: false,
    locationHint: null,
    platform: 'twitter', text: 'It is deeply concerning that the University of Kentucky continues to raise tuition while simultaneously failing to address fundamental issues of campus infrastructure and student safety. The administration must be held accountable for these systematic failures that disproportionately impact vulnerable student populations. Transparency and accountability should be the cornerstone of any public institution.', mediaType: 'none', mediaDescription: null,
    timestamp: t(44), isReply: false, replyToId: null, hashtags: [],
    likes: 23, shares: 8, replies: 2, quoteShares: 1,
  },
  {
    id: 'sn-ai-002', sproutId: spr(),
    authorHandle: '@EducationWatch_KY', authorDisplayName: 'KY Education Watch',
    accountAgeDays: 21, followerCount: 45, followingCount: 3, totalPostCount: 12,
    hasProfilePhoto: true, bioKeywords: ['education', 'accountability', 'Kentucky'], platformVerified: false,
    locationHint: null,
    platform: 'twitter', text: 'While the University of Kentucky allocates millions to athletic programs, it is important to note that academic departments face significant budget constraints. Furthermore, the growing disparity between administrative salaries and adjunct compensation raises serious questions about institutional priorities. Students and taxpayers deserve better.', mediaType: 'none', mediaDescription: null,
    timestamp: t(56), isReply: false, replyToId: null, hashtags: [],
    likes: 34, shares: 12, replies: 3, quoteShares: 2,
  },
  {
    id: 'sn-ai-003', sproutId: spr(),
    authorHandle: '@HigherEdReform21', authorDisplayName: 'Higher Ed Reformer',
    accountAgeDays: 15, followerCount: 28, followingCount: 5, totalPostCount: 6,
    hasProfilePhoto: false, bioKeywords: ['reform', 'higher education'], platformVerified: false,
    locationHint: null,
    platform: 'twitter', text: 'The University of Kentucky\'s approach to campus safety represents a broader pattern of institutional negligence across American higher education. While many perspectives exist on this issue, the data clearly demonstrates that universities must prioritize the physical wellbeing of their students over revenue-generating activities. Additionally, the lack of transparent reporting mechanisms further erodes public trust.', mediaType: 'none', mediaDescription: null,
    timestamp: t(70), isReply: false, replyToId: null, hashtags: [],
    likes: 15, shares: 6, replies: 1, quoteShares: 0,
  },
  {
    id: 'sn-ai-004', sproutId: spr(),
    authorHandle: '@TaxpayerVoice502', authorDisplayName: 'Kentucky Taxpayer Voice',
    accountAgeDays: 28, followerCount: 19, followingCount: 4, totalPostCount: 9,
    hasProfilePhoto: false, bioKeywords: ['taxpayer', 'accountability'], platformVerified: false,
    locationHint: null,
    platform: 'facebook', text: 'As a Kentucky taxpayer, I find it deeply troubling that the University of Kentucky has increased administrative spending by 23% over the past five years while student outcomes have remained stagnant. Moreover, the university\'s housing conditions, as reported by numerous students, raise significant concerns about the institution\'s commitment to student welfare. It is imperative that the Board of Trustees conducts a comprehensive review of spending priorities.', mediaType: 'none', mediaDescription: null,
    timestamp: t(95), isReply: false, replyToId: null, hashtags: [],
    likes: 45, shares: 18, replies: 5, quoteShares: 0,
  },
  {
    id: 'sn-ai-005', sproutId: spr(),
    authorHandle: '@SafeCampusNow_', authorDisplayName: 'Campus Safety Alliance',
    accountAgeDays: 7, followerCount: 8, followingCount: 1, totalPostCount: 4,
    hasProfilePhoto: false, bioKeywords: ['safety', 'campus', 'advocacy'], platformVerified: false,
    locationHint: null,
    platform: 'twitter', text: 'The recent series of safety incidents near the University of Kentucky campus underscores the urgent need for comprehensive infrastructure improvements. It is worth noting that peer institutions have implemented evidence-based lighting and surveillance solutions that have demonstrably reduced campus crime. The University of Kentucky should follow these best practices and allocate appropriate resources to ensure student safety remains a top priority.', mediaType: 'none', mediaDescription: null,
    timestamp: t(136), isReply: false, replyToId: null, hashtags: [],
    likes: 11, shares: 4, replies: 1, quoteShares: 0,
  },
]

// ─── NEUTRAL POSTS (~12) ────────────────────────────────────────────────

const NEUTRAL: SocialPost[] = [
  {
    id: 'su-001', sproutId: spr(),
    authorHandle: '@NewCat2026', authorDisplayName: 'Emma Davis',
    accountAgeDays: 120, followerCount: 67, followingCount: 189, totalPostCount: 234,
    hasProfilePhoto: true, bioKeywords: ['incoming freshman', 'UK'], platformVerified: false,
    locationHint: 'Louisville, KY',
    platform: 'twitter', text: 'Does anyone know what time WT Young Library closes on Fridays? Google says 6pm but a friend said midnight?', mediaType: 'none', mediaDescription: null,
    timestamp: t(10), isReply: false, replyToId: null, hashtags: [],
    likes: 12, shares: 2, replies: 8, quoteShares: 0,
  },
  {
    id: 'su-002', sproutId: spr(),
    authorHandle: 'u/transfer_to_uk', authorDisplayName: 'transfer_to_uk',
    accountAgeDays: 30, followerCount: 0, followingCount: 0, totalPostCount: 5,
    hasProfilePhoto: false, bioKeywords: [], platformVerified: false,
    locationHint: null,
    platform: 'reddit', text: 'Transferring from EKU to UK this fall for computer science. Anyone have experience with the transfer credit process? How long did it take to get your credits evaluated?', mediaType: 'none', mediaDescription: null,
    timestamp: t(22), isReply: false, replyToId: null, hashtags: [],
    likes: 23, shares: 0, replies: 15, quoteShares: 0,
  },
  {
    id: 'su-003', sproutId: spr(),
    authorHandle: '@LexWeather', authorDisplayName: 'Lexington Weather',
    accountAgeDays: 4500, followerCount: 23000, followingCount: 345, totalPostCount: 18000,
    hasProfilePhoto: true, bioKeywords: ['weather', 'Lexington', 'Kentucky'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Ice advisory for Fayette County tonight through 6am. UK has not yet announced any closures. Check @UnivKentucky for updates.', mediaType: 'none', mediaDescription: null,
    timestamp: t(35), isReply: false, replyToId: null, hashtags: [],
    likes: 345, shares: 189, replies: 34, quoteShares: 12,
  },
  {
    id: 'su-004', sproutId: spr(),
    authorHandle: '@UKBookstore', authorDisplayName: 'UK Bookstore',
    accountAgeDays: 3800, followerCount: 5600, followingCount: 890, totalPostCount: 3400,
    hasProfilePhoto: true, bioKeywords: ['UK', 'bookstore', 'Wildcats'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'instagram', text: 'Spring merch drop is here! New UK x Vineyard Vines collab in store and online. Open until 7pm tonight.', mediaType: 'image', mediaDescription: 'New UK branded clothing display',
    timestamp: t(48), isReply: false, replyToId: null, hashtags: [],
    likes: 234, shares: 23, replies: 12, quoteShares: 0,
  },
  {
    id: 'su-005', sproutId: spr(),
    authorHandle: '@CommuteCat', authorDisplayName: 'Jake Morales',
    accountAgeDays: 890, followerCount: 78, followingCount: 156, totalPostCount: 567,
    hasProfilePhoto: true, bioKeywords: ['UK', 'commuter', 'richmond ky'], platformVerified: false,
    locationHint: 'Richmond, KY',
    platform: 'twitter', text: 'Is the South Limestone construction ever going to end? My commute from Richmond has added 20 minutes. Does anyone know the expected completion date?', mediaType: 'none', mediaDescription: null,
    timestamp: t(60), isReply: false, replyToId: null, hashtags: [],
    likes: 89, shares: 12, replies: 23, quoteShares: 3,
  },
  {
    id: 'su-006', sproutId: spr(),
    authorHandle: '@UKLibraries', authorDisplayName: 'UK Libraries',
    accountAgeDays: 5000, followerCount: 8900, followingCount: 1200, totalPostCount: 5600,
    hasProfilePhoto: true, bioKeywords: ['UK', 'library', 'research'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Reminder: Extended hours begin next week for finals prep. WT Young will be open 24/7 from April 21–May 2. Study rooms can be reserved at lib.uky.edu/rooms', mediaType: 'none', mediaDescription: null,
    timestamp: t(75), isReply: false, replyToId: null, hashtags: [],
    likes: 456, shares: 234, replies: 12, quoteShares: 8,
  },
  {
    id: 'su-007', sproutId: spr(),
    authorHandle: '@BBN_Radio', authorDisplayName: 'BBN Radio Network',
    accountAgeDays: 4200, followerCount: 45000, followingCount: 560, totalPostCount: 23000,
    hasProfilePhoto: true, bioKeywords: ['UK athletics', 'radio', 'BBN'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'SCHEDULE ALERT: UK football spring game moved from April 12 to April 19 due to facility upgrades at Kroger Field. Kickoff still 1pm. Free admission.', mediaType: 'none', mediaDescription: null,
    timestamp: t(88), isReply: false, replyToId: null, hashtags: [],
    likes: 234, shares: 89, replies: 23, quoteShares: 12,
  },
  {
    id: 'su-008', sproutId: spr(),
    authorHandle: '@UKParking', authorDisplayName: 'UK Parking & Transportation',
    accountAgeDays: 3600, followerCount: 6700, followingCount: 123, totalPostCount: 4500,
    hasProfilePhoto: true, bioKeywords: ['UK', 'parking', 'transportation'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Lot R2 will be closed March 22–24 for repaving. Overflow available at the Press Ave garage. Shuttle service running every 10 minutes from 7am–6pm.', mediaType: 'none', mediaDescription: null,
    timestamp: t(100), isReply: false, replyToId: null, hashtags: [],
    likes: 67, shares: 34, replies: 12, quoteShares: 2,
  },
  {
    id: 'su-009', sproutId: spr(),
    authorHandle: '@PreLawUK', authorDisplayName: 'UK Pre-Law Society',
    accountAgeDays: 1200, followerCount: 890, followingCount: 345, totalPostCount: 670,
    hasProfilePhoto: true, bioKeywords: ['pre-law', 'UK', 'student org'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'instagram', text: 'LSAT prep workshop this Thursday 6-8pm in Whitehall 210. Open to all majors. Bringing pizza and practice tests. RSVP link in bio!', mediaType: 'image', mediaDescription: 'LSAT workshop flyer',
    timestamp: t(115), isReply: false, replyToId: null, hashtags: [],
    likes: 123, shares: 34, replies: 8, quoteShares: 0,
  },
  {
    id: 'su-010', sproutId: spr(),
    authorHandle: '@CampusDining_UK', authorDisplayName: 'UK Campus Dining',
    accountAgeDays: 3200, followerCount: 7800, followingCount: 234, totalPostCount: 5600,
    hasProfilePhoto: true, bioKeywords: ['UK', 'dining', 'food'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Spring menu rotation starts Monday! New additions at The 90: Nashville hot tofu bowl, Mediterranean grain bowl, and rotating local chef features every Wednesday.', mediaType: 'image', mediaDescription: 'New menu items photo',
    timestamp: t(128), isReply: false, replyToId: null, hashtags: [],
    likes: 189, shares: 45, replies: 23, quoteShares: 5,
  },
  {
    id: 'su-011', sproutId: spr(),
    authorHandle: '@LexTransit', authorDisplayName: 'Lextran',
    accountAgeDays: 4000, followerCount: 5600, followingCount: 345, totalPostCount: 8900,
    hasProfilePhoto: true, bioKeywords: ['transit', 'Lexington', 'bus'], platformVerified: true,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Route 5 (UK/Nicholasville Rd) will be on a modified schedule tomorrow due to road work on S. Limestone. Check lextran.com/alerts for detour info.', mediaType: 'none', mediaDescription: null,
    timestamp: t(145), isReply: false, replyToId: null, hashtags: [],
    likes: 45, shares: 23, replies: 8, quoteShares: 2,
  },
  {
    id: 'su-012', sproutId: spr(),
    authorHandle: '@WildcatWX', authorDisplayName: 'UK Meteorology Club',
    accountAgeDays: 890, followerCount: 2300, followingCount: 234, totalPostCount: 1200,
    hasProfilePhoto: true, bioKeywords: ['weather', 'UK', 'meteorology'], platformVerified: false,
    locationHint: 'Lexington, KY',
    platform: 'twitter', text: 'Our forecast: Partly cloudy through Thursday, highs near 68°F. Slight chance of scattered showers Friday. Perfect week for outdoor studying on the lawn! Full forecast at our site.', mediaType: 'none', mediaDescription: null,
    timestamp: t(157), isReply: false, replyToId: null, hashtags: [],
    likes: 89, shares: 12, replies: 5, quoteShares: 0,
  },
]

// ─── Export combined dataset ─────────────────────────────────────────────

export const SPROUT_7DAY_POSTS: SocialPost[] = [
  ...POSITIVE,
  ...NEGATIVE,
  ...NEUTRAL,
]
