import type { LucideIcon } from 'lucide-react'
import {
  Trophy, Heart, Brain, BookOpen,
  Gavel, Zap, Briefcase, Scale, GraduationCap,
  Newspaper, Compass, FileText, ClipboardList,
  CalendarClock, Mail, CheckSquare, Moon, HeartPulse,
  FlaskConical, Microscope, Cpu, FlaskRound, Pill,
  Mic, ShieldAlert, Stethoscope,
  Activity, HelpCircle, Map, Sparkles,
  FileUser, Users, MessageCircle, FolderSync, DoorOpen,
  Lightbulb, Rocket, PenTool, BarChart3, Presentation,
  ScrollText, ListChecks, Forward, Image,
  UserCircle, Clock, FileSearch, Database,
  MapPin, Calendar, BookMarked, Coins,
  Megaphone, ClipboardCheck,
  BarChart2, LineChart, Building2,
  StickyNote, AppWindow,
  Radio, Landmark, Shield, Sunrise,
  Code2, MessagesSquare, Target,
  Headphones,
} from 'lucide-react'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ShowcaseTool {
  id: string
  label: string
  hook: string
  route: string
  icon: LucideIcon
  gradient: string
  emoji?: string
}

export interface SwimLane {
  id: string
  title: string
  tools: ShowcaseTool[]
  visibleTo: ('STUDENT' | 'EDUCATOR' | 'ADMIN' | 'STAFF')[]
  elevated?: boolean
}

export interface HeroConfig {
  role: 'STUDENT' | 'EDUCATOR' | 'ADMIN' | 'STAFF'
  tool: ShowcaseTool
}

// ─── Heroes ───────────────────────────────────────────────────────────────────

export const HEROES: HeroConfig[] = [
  {
    role: 'ADMIN',
    tool: {
      id: 'hero-bracket',
      label: 'The Bracket',
      hook: 'NCAA March Madness — live picks, leaderboard, campus-wide competition',
      route: '/bracket',
      icon: Trophy,
      gradient: 'from-amber-500 to-orange-600',
      emoji: '🏆',
    },
  },
  {
    role: 'STUDENT',
    tool: {
      id: 'hero-cardiac-sim',
      label: 'Cardiac Arrest Simulator',
      hook: 'Clinical decision-making simulation with real-time AI coaching',
      route: '/playground?template=cardiac-arrest&warm=true',
      icon: Heart,
      gradient: 'from-red-500 to-rose-700',
      emoji: '🏥',
    },
  },
  {
    role: 'EDUCATOR',
    tool: {
      id: 'hero-ai-literacy',
      label: 'AI Literacy Hub',
      hook: '8-module training ecosystem — stance assessment, policy builder, assignment redesign',
      route: '/ai-literacy',
      icon: Brain,
      gradient: 'from-violet-500 to-indigo-700',
      emoji: '🧠',
    },
  },
  {
    role: 'STAFF',
    tool: {
      id: 'hero-tasks',
      label: 'Tasks & Action Center',
      hook: 'Your daily task queue with Sandy-powered smart prioritization',
      route: '/tasks',
      icon: ListChecks,
      gradient: 'from-blue-500 to-indigo-700',
      emoji: '✅',
    },
  },
]

// ─── Featured Tools (3 hero cards, role-adaptive) ────────────────────────────

export interface FeaturedTool {
  tool: ShowcaseTool
  tagline: string
}

/** Hand-picked tools rendered at 2x size in a featured row. */
export const FEATURED_TOOLS: Record<'STUDENT' | 'EDUCATOR' | 'ADMIN' | 'STAFF', FeaturedTool[]> = {
  STUDENT: [
    {
      tool: {
        id: 'study-buddy-hero',
        label: 'Study Buddy',
        hook: '7 AI study modes with persistent memory — tutor, quiz, flashcards, Socratic, teach-back, debate, essay coach',
        route: '/study',
        icon: Brain,
        gradient: 'from-[#0033A0] to-indigo-700',
        emoji: '🧠',
      },
      tagline: 'Your AI-powered study partner',
    },
    {
      tool: {
        id: 'the-commons',
        label: 'Sandcastle Live',
        hook: 'Real-time collaborative rooms — challenges, debates, simulations, study sessions, and 10 more interactive formats',
        route: '/sandcastle/new',
        icon: Users,
        gradient: 'from-cyan-500 to-blue-700',
        emoji: '🏛️',
      },
      tagline: 'Best for in-class engagement',
    },
    {
      tool: {
        id: 'ai-office-hours',
        label: 'AI Office Hours',
        hook: 'On-demand tutoring powered by your course materials — ask anything, anytime',
        route: '/office-hours',
        icon: HelpCircle,
        gradient: 'from-indigo-500 to-blue-600',
        emoji: '💡',
      },
      tagline: 'Most used by students',
    },
  ],
  EDUCATOR: [
    {
      tool: {
        id: 'ada-compliance-tool',
        label: 'ADA Compliance Tool',
        hook: 'Drop in any document — get it scanned, scored, and auto-fixed for WCAG 2.1 AA accessibility in one step',
        route: '/ada-tool',
        icon: Shield,
        gradient: 'from-blue-600 to-indigo-700',
        emoji: '♿',
      },
      tagline: 'Make every document accessible',
    },
    {
      tool: {
        id: 'the-commons',
        label: 'Sandcastle Live',
        hook: 'Real-time collaborative rooms — challenges, debates, simulations, study sessions, and 10 more interactive formats',
        route: '/sandcastle/new',
        icon: Users,
        gradient: 'from-cyan-500 to-blue-700',
        emoji: '🏛️',
      },
      tagline: 'Best for in-class engagement',
    },
    {
      tool: {
        id: 'crisis-spokesperson-trainer',
        label: 'Crisis Spokesperson Trainer',
        hook: 'Hot-seat media training with an AI reporter who escalates pressure and scores your response',
        route: '/crisis-comms/spokesperson-trainer',
        icon: Mic,
        gradient: 'from-red-500 to-orange-700',
        emoji: '🎙️',
      },
      tagline: 'Most unique experience on the platform',
    },
  ],
  ADMIN: [
    {
      tool: {
        id: 'ada-compliance-tool',
        label: 'ADA Compliance Tool',
        hook: 'Drop in any document — get it scanned, scored, and auto-fixed for WCAG 2.1 AA accessibility in one step',
        route: '/ada-tool',
        icon: Shield,
        gradient: 'from-blue-600 to-indigo-700',
        emoji: '♿',
      },
      tagline: 'Make every document accessible',
    },
    {
      tool: {
        id: 'the-commons',
        label: 'Sandcastle Live',
        hook: 'Real-time collaborative rooms — challenges, debates, simulations, study sessions, and 10 more interactive formats',
        route: '/sandcastle/new',
        icon: Users,
        gradient: 'from-cyan-500 to-blue-700',
        emoji: '🏛️',
      },
      tagline: 'Best for in-class engagement',
    },
    {
      tool: {
        id: 'registrar-command-center',
        label: 'Registrar Command Center',
        hook: 'Graduation clearance, enrollment heat maps, student 360, holds, petitions, and Sandy triage',
        route: '/registrar',
        icon: Landmark,
        gradient: 'from-indigo-600 to-blue-800',
        emoji: '🏛️',
      },
      tagline: 'Full institutional intelligence',
    },
  ],
  STAFF: [
    {
      tool: {
        id: 'ada-compliance-tool',
        label: 'ADA Compliance Tool',
        hook: 'Drop in any document — get it scanned, scored, and auto-fixed for WCAG 2.1 AA accessibility in one step',
        route: '/ada-tool',
        icon: Shield,
        gradient: 'from-blue-600 to-indigo-700',
        emoji: '♿',
      },
      tagline: 'Make every document accessible',
    },
    {
      tool: {
        id: 'the-commons',
        label: 'Sandcastle Live',
        hook: 'Real-time collaborative rooms — challenges, debates, simulations, study sessions, and 10 more interactive formats',
        route: '/sandcastle/new',
        icon: Users,
        gradient: 'from-cyan-500 to-blue-700',
        emoji: '🏛️',
      },
      tagline: 'Best for in-class engagement',
    },
    {
      tool: {
        id: 'staff-action-center',
        label: 'Action Center',
        hook: 'Your daily action queue — approvals, overdue items, and Sandy-prioritized tasks',
        route: '/staff/actions',
        icon: Zap,
        gradient: 'from-rose-500 to-red-700',
        emoji: '⚡',
      },
      tagline: 'Start your day here',
    },
  ],
}

// Maximum tools shown per swim lane before "See all" link
export const LANE_TOOL_CAP = 5

// ─── Swim Lanes ───────────────────────────────────────────────────────────────

export const SWIM_LANES: SwimLane[] = [
  // ── Crisis Comms ──────────────────────────────────────────────────────────
  {
    id: 'crisis-comms',
    title: 'Crisis Comms',
    visibleTo: ['EDUCATOR', 'ADMIN', 'STAFF'],
    tools: [
      {
        id: 'crisis-spokesperson-trainer',
        label: 'Crisis Spokesperson Trainer',
        hook: 'Hot-seat media training with an AI reporter who escalates pressure and scores your response',
        route: '/crisis-comms/spokesperson-trainer',
        icon: Mic,
        gradient: 'from-red-500 to-orange-700',
        emoji: '🎙️',
      },
      {
        id: 'reputation-pulse',
        label: 'Reputation Pulse',
        hook: 'Analyze social media posts for authenticity, coordination patterns, and AI-generated content during a crisis',
        route: '/crisis-comms/reputation-pulse',
        icon: ShieldAlert,
        gradient: 'from-slate-600 to-red-700',
        emoji: '🚨',
      },
      {
        id: 'crisis-command-center',
        label: 'Crisis Command Center',
        hook: 'Report an incident, get an AI severity assessment, and generate coordinated response documents in real time',
        route: '/crisis-comms/command-center',
        icon: Radio,
        gradient: 'from-red-600 to-rose-800',
        emoji: '📡',
      },
    ],
  },

  // ── Study Tools ───────────────────────────────────────────────────────────
  {
    id: 'study-tools',
    title: 'Study Tools',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'study-buddy',
        label: 'Study Buddy',
        hook: '7 AI study modes — tutor, quiz, flashcards, Socratic, teach-back, debate, essay coach — with persistent memory',
        route: '/study',
        icon: Brain,
        gradient: 'from-[#0033A0] to-indigo-700',
        emoji: '🧠',
      },
      {
        id: 'study-skills-coach',
        label: 'Study Skills Coach',
        hook: 'Diagnose study problems and match you with evidence-based techniques',
        route: '/tools/tool-study-skills-coach',
        icon: Target,
        gradient: 'from-amber-500 to-orange-600',
        emoji: '☀️',
      },
      {
        id: 'exam-forge-study',
        label: 'Exam Forge',
        hook: 'AI-generated practice exams tailored to your course material',
        route: '/exam-forge',
        icon: GraduationCap,
        gradient: 'from-violet-500 to-purple-700',
        emoji: '📝',
      },
      {
        id: 'teach-it-back-study',
        label: 'Teach It Back',
        hook: 'Explain concepts to Sandy and get scored on your understanding',
        route: '/teach-back',
        icon: BookOpen,
        gradient: 'from-rose-500 to-pink-700',
        emoji: '🎓',
      },
      {
        id: 'ai-office-hours-study',
        label: 'AI Office Hours',
        hook: 'On-demand tutoring powered by your course materials',
        route: '/office-hours',
        icon: HelpCircle,
        gradient: 'from-indigo-500 to-blue-600',
        emoji: '💡',
      },
    ],
  },

  // ── AI Teaches ────────────────────────────────────────────────────────────
  {
    id: 'ai-teaches',
    title: 'AI Teaches',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'exam-forge',
        label: 'Exam Forge',
        hook: 'AI-generated practice exams tailored to your course material',
        route: '/exam-forge',
        icon: Brain,
        gradient: 'from-violet-500 to-purple-700',
        emoji: '🧠',
      },
      {
        id: 'teach-it-back',
        label: 'Teach It Back',
        hook: 'Explain concepts to Sandy and get scored on your understanding',
        route: '/teach-back',
        icon: BookOpen,
        gradient: 'from-violet-600 to-indigo-700',
        emoji: '🎓',
      },
      {
        id: 'prereq-unpacker',
        label: 'Prereq Unpacker',
        hook: 'Trace weak concepts back to their foundational prerequisites',
        route: '/constellation',
        icon: Sparkles,
        gradient: 'from-purple-500 to-fuchsia-600',
        emoji: '✨',
      },
      {
        id: 'ai-office-hours',
        label: 'AI Office Hours',
        hook: 'On-demand tutoring powered by your course materials',
        route: '/office-hours',
        icon: HelpCircle,
        gradient: 'from-indigo-500 to-blue-600',
        emoji: '💡',
      },
      {
        id: 'avatar-creator',
        label: 'Avatar Creator',
        hook: 'Upload course materials and Sandy creates a personalized teaching assistant',
        route: '/avatar',
        icon: UserCircle,
        gradient: 'from-blue-500 to-indigo-700',
        emoji: '🤖',
      },
      {
        id: 'ear-training',
        label: 'Ear Training Lab',
        hook: 'Web Audio-powered interval, chord, and progression identification with a CSS piano keyboard',
        route: '/playground?template=ear-training&warm=true',
        icon: BookOpen,
        gradient: 'from-emerald-500 to-teal-700',
        emoji: '🎵',
      },
      {
        id: 'poetry-meter',
        label: 'Poetry Meter Analyzer',
        hook: 'See stressed/unstressed syllables, meter identification, rhyme scheme, and literary device detection',
        route: '/playground?template=poetry-meter&warm=true',
        icon: BookOpen,
        gradient: 'from-purple-400 to-violet-600',
        emoji: '✒️',
      },
      {
        id: 'statute-annotator',
        label: 'Statute Annotator',
        hook: 'Highlight and annotate statutory text with color-coded argument types and margin notes',
        route: '/playground?template=statute-annotator&warm=true',
        icon: BookOpen,
        gradient: 'from-amber-500 to-orange-700',
        emoji: '📜',
      },
      {
        id: 'playground',
        label: 'Playground',
        hook: 'Code sandbox — build interactive HTML/React apps with AI assistance and live preview',
        route: '/playground',
        icon: Code2,
        gradient: 'from-green-500 to-emerald-700',
        emoji: '🛝',
      },
    ],
  },

  // ── AI Simulates ──────────────────────────────────────────────────────────
  {
    id: 'ai-simulates',
    title: 'AI Simulates',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'cardiac-arrest-sim',
        label: 'Cardiac Arrest Sim',
        hook: 'ACLS clinical decision-making with real-time AI coaching',
        route: '/playground?template=cardiac-arrest&warm=true',
        icon: Heart,
        gradient: 'from-red-500 to-rose-700',
        emoji: '🏥',
      },
      {
        id: 'clinical-trial-matcher',
        label: 'Clinical Trial Matcher',
        hook: 'Search ClinicalTrials.gov and score eligibility with AI',
        route: '/clinical-trial-matcher',
        icon: Stethoscope,
        gradient: 'from-teal-500 to-emerald-700',
        emoji: '🔬',
      },
      {
        id: 'pediatric-sepsis',
        label: 'Pediatric Sepsis Triage',
        hook: 'Golden-hour sepsis management with animated vitals and Surviving Sepsis Campaign bundle scoring',
        route: '/playground?template=pediatric-sepsis&warm=true',
        icon: Heart,
        gradient: 'from-rose-500 to-red-700',
        emoji: '🩺',
      },
      {
        id: 'moot-court',
        label: 'Moot Court',
        hook: 'Appellate oral argument practice with AI judges',
        route: '/playground?template=moot-court&warm=true',
        icon: Scale,
        gradient: 'from-indigo-500 to-violet-700',
        emoji: '⚖️',
      },
      {
        id: 'molecular-viewer',
        label: 'Molecular Viewer',
        hook: '3D molecular structures you can rotate and explore',
        route: '/playground?template=molecular-viewer&warm=true',
        icon: Microscope,
        gradient: 'from-teal-500 to-cyan-700',
        emoji: '🧬',
      },
      {
        id: 'circuit-simulator',
        label: 'Circuit Simulator',
        hook: 'Build and test circuits with live voltage readouts',
        route: '/playground?template=circuit-simulator&warm=true',
        icon: Cpu,
        gradient: 'from-orange-500 to-amber-700',
        emoji: '⚡',
      },
      {
        id: 'lab-safety-sim',
        label: 'Lab Safety Sim',
        hook: 'Chemistry lab safety walkthrough with AI scenarios',
        route: '/playground?template=lab-safety&warm=true',
        icon: FlaskRound,
        gradient: 'from-lime-500 to-green-700',
        emoji: '🧪',
      },
      {
        id: 'drug-interaction-sim',
        label: 'Drug Interaction Checker',
        hook: 'Visualize interactions with severity matrix and clinical recommendations',
        route: '/playground?template=drug-interaction&warm=true',
        icon: Pill,
        gradient: 'from-pink-500 to-rose-700',
        emoji: '💊',
      },
      {
        id: 'physics-sandbox',
        label: 'Physics Sandbox',
        hook: 'Projectile motion, pendulum, and spring-mass simulations with real-time graphs',
        route: '/playground?template=physics-sandbox&warm=true',
        icon: FlaskConical,
        gradient: 'from-sky-500 to-blue-700',
        emoji: '🎯',
      },
      {
        id: 'supply-chain',
        label: 'Supply Chain Visualizer',
        hook: 'Interactive network graph — simulate disruptions and watch cascade effects',
        route: '/playground?template=supply-chain&warm=true',
        icon: Compass,
        gradient: 'from-slate-500 to-gray-700',
        emoji: '🔗',
      },
      {
        id: 'vitals-dashboard',
        label: 'Patient Vitals Dashboard',
        hook: 'Realistic patient monitor with animated ECG, SpO2, respiration, and BP waveforms',
        route: '/playground?template=vitals-dashboard&warm=true',
        icon: Activity,
        gradient: 'from-red-400 to-rose-600',
        emoji: '🫀',
      },
    ],
  },

  // ── Virtual Clinic ────────────────────────────────────────────────────────
  {
    id: 'virtual-clinic',
    title: 'Virtual Clinic',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'virtual-clinic-encounter',
        label: 'Patient Encounters',
        hook: 'Conduct AI patient interviews, build differentials, and get OSCE-scored feedback',
        route: '/virtual-clinic',
        icon: Stethoscope,
        gradient: 'from-teal-500 to-emerald-700',
        emoji: '🩺',
      },
      {
        id: 'virtual-clinic-author',
        label: 'Case Author',
        hook: 'Educators: design clinical cases with patient data, exam findings, and scoring rubrics',
        route: '/virtual-clinic/author',
        icon: FileText,
        gradient: 'from-blue-500 to-indigo-700',
        emoji: '📋',
      },
    ],
  },

  // ── Live & Interactive ────────────────────────────────────────────────────
  {
    id: 'live-interactive',
    title: 'Live & Interactive',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'debate-arena',
        label: 'Debate Arena',
        hook: 'Structured debates with AI verdicts and scoring',
        route: '/debate',
        icon: Gavel,
        gradient: 'from-blue-600 to-indigo-800',
        emoji: '🎤',
      },
      {
        id: 'quiz-bowl-blitz',
        label: 'Quiz Bowl Blitz',
        hook: 'AI-generated live quizzes — compete in real time',
        route: '/quiz-bowl',
        icon: Zap,
        gradient: 'from-yellow-500 to-amber-600',
        emoji: '⚡',
      },
      {
        id: 'case-pitch',
        label: 'Case Pitch',
        hook: 'Business pitch practice with AI judge feedback',
        route: '/pitch',
        icon: Briefcase,
        gradient: 'from-emerald-500 to-green-700',
        emoji: '💼',
      },
      {
        id: 'the-bracket',
        label: 'The Bracket',
        hook: 'NCAA March Madness — picks, leaderboard, campus competition',
        route: '/bracket',
        icon: Trophy,
        gradient: 'from-amber-500 to-orange-600',
        emoji: '🏆',
      },
      {
        id: 'study-match',
        label: 'Study Match',
        hook: 'Find study partners by course, availability, and study style',
        route: '/study-match',
        icon: Users,
        gradient: 'from-purple-500 to-indigo-600',
        emoji: '🤝',
      },
      {
        id: 'bounties',
        label: 'Bounties',
        hook: 'Post or claim paid campus tasks — research, writing, tutoring',
        route: '/bounties',
        icon: Coins,
        gradient: 'from-amber-500 to-yellow-600',
        emoji: '💰',
      },
      {
        id: 'the-commons',
        label: 'The Commons',
        hook: 'Start live sessions — challenges, debates, simulations, study rooms, and 10 more room types',
        route: '/sandcastle/new',
        icon: Users,
        gradient: 'from-cyan-500 to-blue-700',
        emoji: '🏛️',
      },
    ],
  },

  // ── Writing Studio (Write Room collection) ────────────────────────────────
  {
    id: 'writing-studio',
    title: 'Writing Studio',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN', 'STAFF'],
    elevated: true,
    tools: [
      {
        id: 'resume-builder',
        label: 'Resume Builder',
        hook: 'Sandy-guided resume crafting with smart preloading',
        route: '/write-room/resume-builder',
        icon: FileText,
        gradient: 'from-slate-500 to-gray-700',
        emoji: '📄',
      },
      {
        id: 'cover-letter',
        label: 'Cover Letter',
        hook: 'Tailored cover letters guided by Sandy interview',
        route: '/write-room/cover-letter',
        icon: Mail,
        gradient: 'from-teal-500 to-emerald-600',
        emoji: '✉️',
      },
      {
        id: 'email-rewriter',
        label: 'Email Rewriter',
        hook: 'Paste an email draft, pick a tone — Sandy rewrites it for you',
        route: '/write-room/email-rewriter',
        icon: PenTool,
        gradient: 'from-blue-500 to-sky-600',
        emoji: '✏️',
      },
      {
        id: 'linkedin-optimizer',
        label: 'LinkedIn Optimizer',
        hook: 'Sandy interviews you and optimizes your headline, about section, and experience bullets',
        route: '/write-room/linkedin-optimizer',
        icon: FileUser,
        gradient: 'from-blue-600 to-indigo-700',
        emoji: '💼',
      },
      {
        id: 'institutional-resume',
        label: 'Institutional Resume',
        hook: 'Sandy builds your resume from your institutional footprint — email, committees, awards',
        route: '/write-room/institutional-resume',
        icon: FileUser,
        gradient: 'from-blue-500 to-indigo-700',
        emoji: '📋',
      },
      {
        id: 'contract-drafter',
        label: 'Contract Drafter',
        hook: 'Sandy drafts university contracts with compliance flags and legal review markers',
        route: '/write-room/contract-drafter',
        icon: ScrollText,
        gradient: 'from-slate-600 to-gray-800',
        emoji: '📝',
      },
      {
        id: 'ai-policy-builder',
        label: 'AI Policy Builder',
        hook: 'Build AI use policies for your course with Sandy\'s guided framework',
        route: '/write-room/ai-policy-builder',
        icon: Scale,
        gradient: 'from-indigo-500 to-violet-700',
        emoji: '📜',
      },
    ],
  },

  // ── Data & Analysis (Data Desk collection) ────────────────────────────────
  {
    id: 'data-analysis',
    title: 'Data & Analysis',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN', 'STAFF'],
    elevated: true,
    tools: [
      {
        id: 'survey-analyzer',
        label: 'Survey Analyzer',
        hook: 'Upload survey data and get AI-powered insights',
        route: '/data-desk/survey-analyzer',
        icon: ClipboardList,
        gradient: 'from-orange-500 to-red-600',
        emoji: '📊',
      },
      {
        id: 'chart-explainer',
        label: 'Chart Explainer',
        hook: 'Upload a chart image and Sandy explains trends, outliers, and takeaways',
        route: '/data-desk/chart-explainer',
        icon: Image,
        gradient: 'from-cyan-500 to-blue-600',
        emoji: '📈',
      },
      {
        id: 'report-summarizer',
        label: 'Report Summarizer',
        hook: 'Paste a report and Sandy extracts key findings, KPIs, and action items',
        route: '/data-desk/report-summarizer',
        icon: FileSearch,
        gradient: 'from-emerald-500 to-teal-700',
        emoji: '📑',
      },
      {
        id: 'presentation-outliner',
        label: 'Presentation Outliner',
        hook: 'Sandy interviews you and builds a structured presentation with talking points',
        route: '/data-desk/presentation-outliner',
        icon: Presentation,
        gradient: 'from-violet-500 to-purple-700',
        emoji: '🎬',
      },
      {
        id: 'team-analyzer',
        label: 'Team Structure Analyzer',
        hook: 'Map what your team actually does — not what the org chart says',
        route: '/data-desk/team-analyzer',
        icon: Users,
        gradient: 'from-purple-500 to-violet-700',
        emoji: '👥',
      },
      {
        id: 'sentiment-analyzer',
        label: 'Sentiment Analyzer',
        hook: 'Analyze social media posts, campus conversations, and transcripts — Sandy maps sentiment with actionable talking points',
        route: '/data-desk/sentiment-analyzer',
        icon: MessageCircle,
        gradient: 'from-rose-500 to-red-700',
        emoji: '📊',
      },
    ],
  },

  // ── Meetings & Collaboration (Meeting Machine collection) ─────────────────
  {
    id: 'meetings',
    title: 'Meetings & Collaboration',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN', 'STAFF'],
    elevated: true,
    tools: [
      {
        id: 'agenda-builder',
        label: 'Agenda Builder',
        hook: 'Turn meeting goals into structured agendas',
        route: '/meeting-machine/agenda-builder',
        icon: CalendarClock,
        gradient: 'from-blue-500 to-indigo-600',
        emoji: '📋',
      },
      {
        id: 'minutes-taker',
        label: 'Minutes Taker',
        hook: 'Paste meeting notes and Sandy generates formatted minutes with decisions and action items',
        route: '/meeting-machine/minutes-taker',
        icon: ClipboardList,
        gradient: 'from-slate-500 to-gray-700',
        emoji: '📝',
      },
      {
        id: 'action-items',
        label: 'Action Items',
        hook: 'Extract, assign, and prioritize action items from any meeting notes',
        route: '/meeting-machine/action-items',
        icon: ListChecks,
        gradient: 'from-emerald-500 to-green-700',
        emoji: '✅',
      },
      {
        id: 'follow-up-drafter',
        label: 'Follow-up Drafter',
        hook: 'Sandy drafts follow-up emails with decisions, next steps, and action items',
        route: '/meeting-machine/follow-up-drafter',
        icon: Forward,
        gradient: 'from-sky-500 to-blue-600',
        emoji: '📧',
      },
    ],
  },

  // ── Faculty Intelligence ──────────────────────────────────────────────────
  {
    id: 'faculty-intelligence',
    title: 'Faculty Intelligence',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'lecture-debrief',
        label: 'Lecture Debrief',
        hook: 'AI-powered post-lecture reflection and improvement insights',
        route: '/lecture-debrief',
        icon: BookOpen,
        gradient: 'from-sky-600 to-blue-800',
        emoji: '📝',
      },
      {
        id: 'research-hub',
        label: 'Research Hub',
        hook: 'Literature search, citation help, and methodology review',
        route: '/research-hub',
        icon: FlaskConical,
        gradient: 'from-cyan-600 to-teal-800',
        emoji: '🔬',
      },
      {
        id: 'syllabus-architect',
        label: 'Syllabus Architect',
        hook: 'AI-powered syllabus parsing, objectives, and Bloom\'s alignment',
        route: '/courses',
        icon: FileText,
        gradient: 'from-slate-600 to-gray-800',
        emoji: '📑',
      },
      {
        id: 'ai-literacy-hub',
        label: 'AI Literacy Hub',
        hook: '8 modules — stance assessment, policy builder, assignment redesign, and more',
        route: '/ai-literacy',
        icon: Brain,
        gradient: 'from-violet-500 to-indigo-700',
        emoji: '🧠',
      },
      {
        id: 'prompt-lab',
        label: 'Prompt Lab',
        hook: 'Practice rewriting vague prompts — 5 levels, side-by-side comparison, AI scoring',
        route: '/ai-literacy/prompt-lab',
        icon: PenTool,
        gradient: 'from-blue-500 to-indigo-700',
        emoji: '✍️',
      },
      {
        id: 'output-evaluator',
        label: 'Output Evaluator',
        hook: 'Spot AI errors, hallucinations, and bias — highlight and justify, 3 difficulty tiers',
        route: '/ai-literacy/output-eval',
        icon: FileSearch,
        gradient: 'from-red-500 to-orange-700',
        emoji: '🔍',
      },
      {
        id: 'learning-timeline',
        label: 'Learning Timeline',
        hook: 'Visualize mastery jumps, misconceptions overcome, and study milestones',
        route: '/timeline',
        icon: Clock,
        gradient: 'from-indigo-500 to-purple-700',
        emoji: '📊',
      },
      {
        id: 'datasets-gallery',
        label: 'Datasets',
        hook: 'Browse curated institutional datasets — financial aid, course catalog, admissions FAQ',
        route: '/datasets',
        icon: Database,
        gradient: 'from-teal-500 to-cyan-700',
        emoji: '🗃️',
      },
      {
        id: 'faculty-analytics',
        label: 'Faculty Analytics',
        hook: 'Course health, engagement trends, Bloom\'s distribution, and cohort analysis',
        route: '/analytics/faculty',
        icon: BarChart2,
        gradient: 'from-blue-600 to-indigo-800',
        emoji: '📊',
      },
      {
        id: 'student-analytics',
        label: 'Student Analytics',
        hook: 'Your learning dashboard — mastery trends, study habits, spaced repetition forecast',
        route: '/analytics/student',
        icon: LineChart,
        gradient: 'from-emerald-500 to-teal-700',
        emoji: '📈',
      },
      {
        id: 'evaluator',
        label: 'Evaluator',
        hook: '18-phase AI tool evaluation framework — test, compare, and score tools side by side',
        route: '/evaluate',
        icon: ClipboardCheck,
        gradient: 'from-orange-500 to-red-600',
        emoji: '🔍',
      },
      {
        id: 'ada-compliance-tool',
        label: 'ADA Compliance Tool',
        hook: 'Drop in any document — scan, score, and auto-fix for WCAG 2.1 AA accessibility',
        route: '/ada-tool',
        icon: Shield,
        gradient: 'from-blue-600 to-indigo-700',
      },
    ],
  },

  // ── Campus Life ───────────────────────────────────────────────────────────
  {
    id: 'campus-life',
    title: 'Campus Life',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'ask-sandy',
        label: 'Ask Sandy',
        hook: 'AI academic advisor matched to your college',
        route: '/student-services/academic-advisor',
        icon: GraduationCap,
        gradient: 'from-purple-500 to-violet-700',
        emoji: '🎓',
      },
      {
        id: 'degree-planner',
        label: 'Degree Planner',
        hook: 'Map your path to graduation with AI-optimized scheduling',
        route: '/degree-plan',
        icon: Map,
        gradient: 'from-indigo-500 to-purple-700',
        emoji: '🗺️',
      },
      {
        id: 'uknow',
        label: 'UKNow',
        hook: '14K+ campus articles with AI-powered search',
        route: '/uknow',
        icon: Newspaper,
        gradient: 'from-sky-500 to-blue-600',
        emoji: '📰',
      },
      {
        id: 'campus-navigator',
        label: 'Campus Navigator',
        hook: 'Find buildings, services, and resources across campus',
        route: '/campus-navigator',
        icon: Compass,
        gradient: 'from-green-500 to-emerald-700',
        emoji: '🧭',
      },
      {
        id: 'campus-map',
        label: 'Campus Map',
        hook: 'Interactive map of UK campus — explore buildings, find directions, locate services',
        route: '/campus-map',
        icon: MapPin,
        gradient: 'from-blue-500 to-sky-600',
        emoji: '📍',
      },
      {
        id: 'campus-life-events',
        label: 'Campus Events',
        hook: 'Browse organizations, events, and club meetings — RSVP and connect',
        route: '/campus-life',
        icon: Calendar,
        gradient: 'from-orange-500 to-amber-600',
        emoji: '🎉',
      },
      {
        id: 'book-recommender',
        label: 'Book Recommender',
        hook: 'Tell Sandy what you\'ve read and loved — get personalized reading recommendations',
        route: '/tools/book-recommender',
        icon: BookMarked,
        gradient: 'from-amber-500 to-orange-700',
        emoji: '📚',
      },
      {
        id: 'library',
        label: 'Study Library',
        hook: 'Your personal library of saved study guides, resources, and tools',
        route: '/library',
        icon: BookOpen,
        gradient: 'from-emerald-500 to-teal-600',
        emoji: '📖',
      },
      {
        id: 'explore-majors',
        label: 'Explore Majors',
        hook: 'Browse programs, run what-if degree audits, and compare graduation timelines',
        route: '/explore-majors',
        icon: Sunrise,
        gradient: 'from-amber-500 to-orange-600',
        emoji: '🌅',
      },
      {
        id: 'community-pulse',
        label: 'The Commons',
        hook: 'See who\'s studying, active challenge rooms, trending topics, and campus stats',
        route: '/community',
        icon: Radio,
        gradient: 'from-purple-500 to-violet-600',
        emoji: '📡',
      },
      {
        id: 'messages',
        label: 'Messages',
        hook: 'Discord-style group messaging with The Commons, slash commands, and Sandy integration',
        route: '/messages',
        icon: MessagesSquare,
        gradient: 'from-blue-500 to-indigo-600',
        emoji: '💬',
      },
    ],
  },

  // ── Productivity & Planning ───────────────────────────────────────────────
  {
    id: 'assessment-lab',
    title: 'Assessment Lab',
    visibleTo: ['EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'assessment-canvas',
        label: 'Assessment Canvas',
        hook: 'Design multi-modal assessment mixes across traditional, process, authentic, and mastery evidence',
        route: '/courses',
        icon: Compass,
        gradient: 'from-amber-500 to-orange-600',
        emoji: '🧭',
      },
      {
        id: 'mastery-gates',
        label: 'Mastery Gates',
        hook: 'Build adaptive mastery checkpoints and let students prove readiness when they are ready',
        route: '/assessment/mastery',
        icon: GraduationCap,
        gradient: 'from-[#0033A0] to-indigo-700',
        emoji: '🎯',
      },
      {
        id: 'competency-dashboard',
        label: 'Competency Dashboard',
        hook: 'See cross-course competency evidence and class-level distributions',
        route: '/assessment/portfolio',
        icon: BarChart3,
        gradient: 'from-emerald-500 to-teal-700',
        emoji: '📊',
      },
    ],
  },

  {
    id: 'productivity',
    title: 'Productivity & Planning',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN', 'STAFF'],
    tools: [
      {
        id: 'tasks',
        label: 'Tasks',
        hook: 'Personal task manager with Sandy-powered smart prioritization',
        route: '/tasks',
        icon: ListChecks,
        gradient: 'from-blue-500 to-indigo-600',
        emoji: '✅',
      },
      {
        id: 'case-brief-builder',
        label: 'Case Brief Builder',
        hook: 'Structured IRAC case brief builder with auto-formatting and PDF-ready export',
        route: '/playground?template=case-brief-builder&warm=true',
        icon: FileText,
        gradient: 'from-violet-500 to-indigo-700',
        emoji: '📋',
      },
      {
        id: 'budget-allocation',
        label: 'Budget Allocation Challenge',
        hook: 'Multi-round budget simulator with KPI tracking, radar charts, and crisis scenarios',
        route: '/playground?template=budget-allocation&warm=true',
        icon: BarChart3,
        gradient: 'from-sky-500 to-blue-700',
        emoji: '📊',
      },
      {
        id: 'startup-financial-model',
        label: 'Startup Financial Model',
        hook: 'Interactive P&L projector with revenue growth, burn rate, and runway charts',
        route: '/playground?template=startup-financial-model&warm=true',
        icon: BarChart3,
        gradient: 'from-emerald-500 to-green-700',
        emoji: '📈',
      },
      {
        id: 'timeline-builder',
        label: 'Timeline Builder',
        hook: 'Create visual timelines with draggable events, zoom, and color-coded themes',
        route: '/playground?template=timeline-builder&warm=true',
        icon: CalendarClock,
        gradient: 'from-amber-500 to-orange-600',
        emoji: '📅',
      },
      {
        id: 'event-budget-planner',
        label: 'Event Budget Planner',
        hook: 'Plan event budgets with line items, auto-totals, and spending breakdown charts',
        route: '/playground?template=event-budget-planner&warm=true',
        icon: Coins,
        gradient: 'from-pink-500 to-rose-600',
        emoji: '🎉',
      },
      {
        id: 'notes',
        label: 'Notes',
        hook: 'Your personal notes — Sandy-saved insights, pinned messages, and quick captures',
        route: '/notes',
        icon: StickyNote,
        gradient: 'from-yellow-400 to-amber-600',
        emoji: '📝',
      },
      {
        id: 'portfolio',
        label: 'Portfolio',
        hook: 'Build and showcase your digital portfolio — projects, achievements, and skills',
        route: '/portfolio',
        icon: Briefcase,
        gradient: 'from-slate-500 to-gray-700',
        emoji: '💼',
      },
      {
        id: 'my-apps',
        label: 'My Apps',
        hook: 'Your imported apps dashboard — manage and launch your deployed web apps',
        route: '/my-apps',
        icon: AppWindow,
        gradient: 'from-purple-500 to-violet-600',
        emoji: '📱',
      },
    ],
  },

  // ── Staff & Operations ────────────────────────────────────────────────────
  {
    id: 'staff-tools',
    title: 'Staff & Operations',
    visibleTo: ['STAFF', 'STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'file-cleaner',
        label: 'File & Folder Cleaner',
        hook: 'Paste messy file names, get a clean rename map with scripts',
        route: '/tools/file-cleaner',
        icon: FolderSync,
        gradient: 'from-amber-500 to-orange-600',
        emoji: '🗂️',
      },
      {
        id: 'room-reservation',
        label: 'Room Reservation',
        hook: 'Tell Sandy what you need — she finds the perfect room on campus',
        route: '/rooms',
        icon: DoorOpen,
        gradient: 'from-emerald-500 to-teal-700',
        emoji: '🏛️',
      },
      {
        id: 'documents',
        label: 'Document Library',
        hook: 'Upload, organize, and share documents with department visibility and version history',
        route: '/documents',
        icon: FileText,
        gradient: 'from-blue-500 to-indigo-600',
        emoji: '📂',
      },
      {
        id: 'ferpa-training',
        label: 'FERPA Training',
        hook: 'AI-generated FERPA compliance quiz — test your knowledge of student privacy regulations',
        route: '/ferpa-training',
        icon: ShieldAlert,
        gradient: 'from-red-500 to-orange-600',
        emoji: '🔒',
      },
      {
        id: 'registrar-flashcards',
        label: 'Registrar Flashcards',
        hook: 'Interactive flashcard quiz on university registrar processes and rules',
        route: '/tools/ai-registrar-flashcards',
        icon: GraduationCap,
        gradient: 'from-indigo-500 to-blue-700',
        emoji: '🎓',
      },
      {
        id: 'transfer-credit',
        label: 'Transfer Credit Articulator',
        hook: 'Review external course syllabi and auto-evaluate against UK equivalents with AI scoring',
        route: '/tools/transfer-credit-articulator',
        icon: FolderSync,
        gradient: 'from-teal-500 to-emerald-700',
        emoji: '🔄',
      },
      {
        id: 'policy-navigator',
        label: 'Policy Navigator',
        hook: '94 real UK policies from regs.uky.edu — AI-powered search and plain-language summaries',
        route: '/staff/policies',
        icon: ScrollText,
        gradient: 'from-slate-500 to-gray-700',
        emoji: '📜',
      },
      {
        id: 'communications-center',
        label: 'Communications Center',
        hook: 'Draft announcements with templates, tone control, and audience targeting',
        route: '/staff/communications',
        icon: Megaphone,
        gradient: 'from-blue-500 to-sky-700',
        emoji: '📢',
      },
      {
        id: 'committees',
        label: 'Committee Minutes',
        hook: 'Track committee meetings, generate minutes, and manage action items',
        route: '/staff/committees',
        icon: Users,
        gradient: 'from-violet-500 to-purple-700',
        emoji: '👥',
      },
      {
        id: 'survey-intelligence',
        label: 'Survey Intelligence',
        hook: 'AI-powered survey analysis — upload responses, get themes, trends, and actionable insights',
        route: '/staff/survey-intelligence',
        icon: ClipboardCheck,
        gradient: 'from-orange-500 to-amber-700',
        emoji: '📋',
      },
      {
        id: 'staff-action-center',
        label: 'Action Center',
        hook: 'Your daily action queue — approvals, overdue items, and Sandy-prioritized tasks',
        route: '/staff/actions',
        icon: Zap,
        gradient: 'from-rose-500 to-red-700',
        emoji: '⚡',
      },
      {
        id: 'university-systems',
        label: 'University Systems Hub',
        hook: '7 campus integrations — rooms, attendance, grades, travel, reviews, all in one dashboard',
        route: '/university-systems',
        icon: Building2,
        gradient: 'from-indigo-500 to-blue-700',
        emoji: '🏛️',
      },
    ],
  },

  // ── Registrar & Compliance ────────────────────────────────────────────────
  {
    id: 'registrar-compliance',
    title: 'Registrar & Compliance',
    visibleTo: ['ADMIN', 'STAFF'],
    tools: [
      {
        id: 'registrar-command-center',
        label: 'Registrar Command Center',
        hook: 'Graduation clearance, enrollment heat maps, student 360, holds, petitions, and Sandy triage',
        route: '/registrar',
        icon: Landmark,
        gradient: 'from-indigo-600 to-blue-800',
        emoji: '🏛️',
      },
      {
        id: 'compliance-portal',
        label: 'Compliance Portal',
        hook: 'FERPA, SACSCOC, IPEDS — compliance calendar, readiness scores, maturity model, and exports',
        route: '/admin/compliance-portal',
        icon: Shield,
        gradient: 'from-red-500 to-rose-700',
        emoji: '🛡️',
      },
      {
        id: 'academic-standing',
        label: 'Academic Standing',
        hook: 'End-of-term GPA batch review — probation, suspension, dean\'s list, and dismissal processing',
        route: '/registrar/academic-standing',
        icon: GraduationCap,
        gradient: 'from-amber-500 to-orange-700',
        emoji: '🎓',
      },
      {
        id: 'degree-audit',
        label: 'Degree Audit',
        hook: '6-stage graduation clearance pipeline — track students from application to cleared',
        route: '/registrar/degree-audit',
        icon: ClipboardCheck,
        gradient: 'from-emerald-500 to-green-700',
        emoji: '✅',
      },
      {
        id: 'holds-management',
        label: 'Holds Management',
        hook: '6 hold types — financial, academic, advising — with bulk release and Sandy insights',
        route: '/registrar/holds',
        icon: ShieldAlert,
        gradient: 'from-rose-500 to-red-700',
        emoji: '🚫',
      },
      {
        id: 'petitions',
        label: 'Petitions',
        hook: 'Grade appeals and academic petitions — review, approve, and track with AI assistance',
        route: '/registrar/petitions',
        icon: FileText,
        gradient: 'from-violet-500 to-purple-700',
        emoji: '📝',
      },
    ],
  },

  // ── Innovation & IP ───────────────────────────────────────────────────────
  {
    id: 'innovation',
    title: 'Innovation & IP',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'idea-to-launch',
        label: 'Idea to Launch',
        hook: 'Turn your idea into a protected venture — IP assessment, market sizing, pitch, and action plan',
        route: '/innovation-lab/idea-to-launch',
        icon: Rocket,
        gradient: 'from-amber-500 to-orange-600',
        emoji: '🚀',
      },
      {
        id: 'innovation-lab',
        label: 'Innovation Lab',
        hook: 'Patent primers, market sizing, prior art scouting — all your IP tools in one place',
        route: '/innovation-lab',
        icon: Lightbulb,
        gradient: 'from-yellow-500 to-amber-600',
        emoji: '💡',
      },
      {
        id: 'grant-writer',
        label: 'Grant Writer',
        hook: 'Upload your CV and an RFP — Sandy drafts a grant proposal with collaborative editing',
        route: '/workshop/grant-writer',
        icon: FileText,
        gradient: 'from-green-500 to-emerald-700',
        emoji: '💵',
      },
      {
        id: 'apps-gallery',
        label: 'Apps Gallery',
        hook: 'Browse and launch published student and faculty apps and portfolio projects',
        route: '/hub/browse?type=portfolio',
        icon: Rocket,
        gradient: 'from-purple-500 to-violet-600',
        emoji: '🚀',
      },
    ],
  },

  // ── Greek Life & Outreach ──────────────────────────────────────────────────
  {
    id: 'greek-life',
    title: 'Greek Life & Outreach',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    tools: [
      {
        id: 'philanthropy-assistant',
        label: 'AXO Philanthropy Assistant',
        hook: 'Find local donors, generate phone scripts and outreach emails for Greek life philanthropy campaigns',
        route: '/philanthropy-assistant',
        icon: Heart,
        gradient: 'from-rose-500 to-red-700',
        emoji: '💝',
      },
    ],
  },

  // ── Community Projects ─────────────────────────────────────────────────────
  {
    id: 'community-projects',
    title: 'Community Projects',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN', 'STAFF'],
    tools: [
      {
        id: 'community-cardiac-arrest',
        label: 'ACLS Cardiac Arrest Sim',
        hook: 'Student-built clinical decision simulator for ACLS training',
        route: '/playground?template=cardiac-arrest&warm=true',
        icon: Heart,
        gradient: 'from-red-500 to-rose-700',
        emoji: '🏥',
      },
      {
        id: 'community-moot-court',
        label: 'Moot Court Simulator',
        hook: 'Practice constitutional law arguments with AI judges',
        route: '/playground?template=moot-court&warm=true',
        icon: Gavel,
        gradient: 'from-amber-600 to-orange-700',
        emoji: '⚖️',
      },
      {
        id: 'community-lab-safety',
        label: 'Lab Safety Walkthrough',
        hook: 'Interactive chemistry lab safety training',
        route: '/playground?template=lab-safety&warm=true',
        icon: FlaskRound,
        gradient: 'from-emerald-500 to-green-700',
        emoji: '🧪',
      },
      {
        id: 'community-budget-allocation',
        label: 'Budget Allocation Sim',
        hook: 'Simulate university budget decisions with real tradeoffs',
        route: '/playground?template=budget-allocation&warm=true',
        icon: Coins,
        gradient: 'from-blue-500 to-indigo-700',
        emoji: '💰',
      },
    ],
  },

  // ── Wellness ──────────────────────────────────────────────────────────────
  {
    id: 'wellness',
    title: 'Wellness',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN'],
    elevated: true,
    tools: [
      {
        id: 'mindfulness-coach',
        label: 'Mindfulness Coach',
        hook: 'Guided breathing and mindfulness exercises',
        route: '/wellness-hub/mindfulness',
        icon: Activity,
        gradient: 'from-green-500 to-emerald-600',
        emoji: '🧘',
      },
      {
        id: 'habit-tracker',
        label: 'Habit Tracker',
        hook: 'Build and track daily wellness habits',
        route: '/wellness-hub/habits',
        icon: CheckSquare,
        gradient: 'from-lime-500 to-green-600',
        emoji: '✅',
      },
      {
        id: 'sleep-log',
        label: 'Sleep Log',
        hook: 'Track sleep patterns and get AI recommendations',
        route: '/wellness-hub/sleep',
        icon: Moon,
        gradient: 'from-indigo-400 to-violet-600',
        emoji: '🌙',
      },
      {
        id: 'symptom-journal',
        label: 'Symptom Journal',
        hook: 'Log symptoms and spot patterns over time',
        route: '/wellness-hub/journal',
        icon: HeartPulse,
        gradient: 'from-rose-400 to-pink-600',
        emoji: '💗',
      },
    ],
  },

  // ── Audio Experiences ─────────────────────────────────────────────────────
  {
    id: 'audio-experiences',
    title: 'Audio Experiences',
    visibleTo: ['STUDENT', 'EDUCATOR', 'ADMIN', 'STAFF'],
    tools: [
      {
        id: 'audio-hub',
        label: 'Audio Hub',
        hook: 'Podcasts, voice tutoring, and interactive audio experiences',
        route: '/audio',
        icon: Headphones,
        gradient: 'from-blue-500 to-indigo-600',
      },
    ],
  },
]

// ─── Role-based lane ordering ─────────────────────────────────────────────────

/**
 * Curated lanes shown on the main Explore page (max 6 per role).
 * Full catalog accessible via /hub/browse. Demoted to browse-only:
 * community-projects (duplicates), wellness, innovation.
 */
export const ROLE_LANE_ORDER: Record<'STUDENT' | 'EDUCATOR' | 'ADMIN' | 'STAFF', string[]> = {
  STUDENT: [
    'study-tools', 'ai-simulates', 'ai-teaches',
    'live-interactive', 'campus-life', 'writing-studio',
    'audio-experiences',
  ],
  EDUCATOR: [
    'crisis-comms', 'faculty-intelligence', 'assessment-lab',
    'ai-teaches', 'writing-studio', 'data-analysis',
    'audio-experiences',
  ],
  ADMIN: [
    'crisis-comms', 'faculty-intelligence', 'assessment-lab',
    'staff-tools', 'registrar-compliance', 'data-analysis',
    'audio-experiences',
  ],
  STAFF: [
    'crisis-comms', 'staff-tools', 'meetings',
    'data-analysis', 'writing-studio', 'productivity',
    'audio-experiences',
  ],
}
