'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import {
  AlertTriangle,
  Calendar,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Loader2,
  Plus,
  Trash2,
} from 'lucide-react'
import { useAuth } from '../../lib/auth-context'
import { apiFetch } from '../../lib/api-client'
import PageHeader from '../../components/PageHeader'

type CalendarEvent = {
  id: string
  title: string
  description?: string | null
  eventType: string
  dueDate: string
  completed: boolean
  completedAt?: string | null
  isAutoGenerated?: boolean
  creator?: { id: string; name: string; email: string }
  createdAt?: string
}

const EVENT_TYPE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  'dpa-expiry': { bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200' },
  'consent-renewal': { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  'audit-scheduled': { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
  'training-deadline': { bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
  'policy-review': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  'custom': { bg: 'bg-gray-50', text: 'text-gray-700', border: 'border-gray-200' },
}

const EVENT_TYPE_LABELS: Record<string, string> = {
  'dpa-expiry': 'DPA Expiry',
  'consent-renewal': 'Consent Renewal',
  'audit-scheduled': 'Audit Scheduled',
  'training-deadline': 'Training Deadline',
  'policy-review': 'Policy Review',
  'custom': 'Custom',
}

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

export default function ComplianceCalendarPage() {
  const { currentUser } = useAuth()
  const router = useRouter()

  const now = new Date()
  const [year, setYear] = useState(now.getFullYear())
  const [month, setMonth] = useState(now.getMonth() + 1)
  const [events, setEvents] = useState<CalendarEvent[]>([])
  const [autoEvents, setAutoEvents] = useState<CalendarEvent[]>([])
  const [loading, setLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  const [saving, setSaving] = useState(false)

  // Form state
  const [fTitle, setFTitle] = useState('')
  const [fDesc, setFDesc] = useState('')
  const [fType, setFType] = useState('custom')
  const [fDueDate, setFDueDate] = useState('')

  const fetchEvents = useCallback(async (signal?: AbortSignal) => {
    setLoading(true)
    try {
      const data = await apiFetch<{ events?: CalendarEvent[]; autoEvents?: CalendarEvent[] }>(
        currentUser.email,
        `/api/admin/compliance-calendar?month=${month}&year=${year}&includeAuto=true`,
        { signal },
      )
      setEvents(data.events ?? [])
      setAutoEvents(data.autoEvents ?? [])
    } catch (err) {
      if (err instanceof Error && err.name === 'AbortError') return
      console.error('Failed to fetch calendar events')
    } finally {
      setLoading(false)
    }
  }, [month, year, currentUser.email])

  useEffect(() => {
    if (currentUser.role !== 'ADMIN') {
      router.replace('/')
      return
    }
    const controller = new AbortController()
    void fetchEvents(controller.signal)
    return () => controller.abort()
  }, [currentUser.role, router, fetchEvents])

  const handleCreate = async () => {
    if (!fTitle || !fType || !fDueDate) return
    setSaving(true)
    try {
      await apiFetch(currentUser.email, '/api/admin/compliance-calendar', {
        method: 'POST',
        body: JSON.stringify({ title: fTitle, description: fDesc || undefined, eventType: fType, dueDate: fDueDate }),
      })
      setFTitle('')
      setFDesc('')
      setFType('custom')
      setFDueDate('')
      setShowForm(false)
      void fetchEvents()
    } catch {
      console.error('Failed to create event')
    } finally {
      setSaving(false)
    }
  }

  const handleComplete = async (id: string) => {
    try {
      await apiFetch(currentUser.email, `/api/admin/compliance-calendar/${id}`, {
        method: 'PATCH',
        body: JSON.stringify({ completed: true }),
      })
      void fetchEvents()
    } catch {
      console.error('Failed to complete event')
    }
  }

  const handleDelete = async (id: string) => {
    try {
      await apiFetch(currentUser.email, `/api/admin/compliance-calendar/${id}`, {
        method: 'DELETE',
      })
      void fetchEvents()
    } catch {
      console.error('Failed to delete event')
    }
  }

  const prevMonth = () => {
    if (month === 1) { setMonth(12); setYear(y => y - 1) }
    else setMonth(m => m - 1)
  }
  const nextMonth = () => {
    if (month === 12) { setMonth(1); setYear(y => y + 1) }
    else setMonth(m => m + 1)
  }

  const allEvents = [...events, ...autoEvents].sort(
    (a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime(),
  )

  const isOverdue = (d: string, completed: boolean) =>
    !completed && new Date(d) < new Date()

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-6xl px-4 py-8">
        <PageHeader
          title="Compliance Calendar"
          subtitle="Track compliance deadlines, audits, and policy reviews"
          action={
            <Link href="/admin" className="inline-flex items-center gap-1.5 text-sm font-semibold text-gray-500 hover:text-gray-700">
              <ChevronLeft className="size-4" /> Back to Admin
            </Link>
          }
        />

        {/* Month navigation */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <button type="button" onClick={prevMonth} className="rounded-lg p-2 hover:bg-gray-100">
              <ChevronLeft className="size-5 text-gray-600" />
            </button>
            <h2 className="text-lg font-extrabold text-gray-900">
              {MONTHS[month - 1]} {year}
            </h2>
            <button type="button" onClick={nextMonth} className="rounded-lg p-2 hover:bg-gray-100">
              <ChevronRight className="size-5 text-gray-600" />
            </button>
          </div>
          <button
            type="button"
            onClick={() => setShowForm(!showForm)}
            className="inline-flex items-center gap-1.5 rounded-xl px-4 py-2 text-sm font-semibold text-white"
            style={{ backgroundColor: '#0033A0' }}
          >
            <Plus className="size-4" />
            Add Event
          </button>
        </div>

        {/* Create form */}
        {showForm && (
          <div className="rounded-2xl border-2 border-gray-200 bg-white p-6 mb-6">
            <h3 className="text-sm font-bold text-gray-700 mb-4">New Calendar Event</h3>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div>
                <label className="block text-xs font-semibold text-gray-500 mb-1">Title</label>
                <input
                  type="text"
                  value={fTitle}
                  onChange={(e) => setFTitle(e.target.value)}
                  className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
                  placeholder="e.g. Annual FERPA Audit"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-gray-500 mb-1">Type</label>
                <select
                  value={fType}
                  onChange={(e) => setFType(e.target.value)}
                  className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
                >
                  {Object.entries(EVENT_TYPE_LABELS).map(([k, v]) => (
                    <option key={k} value={k}>{v}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-semibold text-gray-500 mb-1">Due Date</label>
                <input
                  type="date"
                  value={fDueDate}
                  onChange={(e) => setFDueDate(e.target.value)}
                  className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-gray-500 mb-1">Description</label>
                <input
                  type="text"
                  value={fDesc}
                  onChange={(e) => setFDesc(e.target.value)}
                  className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
                  placeholder="Optional details"
                />
              </div>
            </div>
            <div className="mt-4 flex gap-3">
              <button
                type="button"
                onClick={handleCreate}
                disabled={saving || !fTitle || !fDueDate}
                className="inline-flex items-center gap-1.5 rounded-xl px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"
                style={{ backgroundColor: '#0033A0' }}
              >
                {saving ? <Loader2 className="size-4 animate-spin" /> : <Calendar className="size-4" />}
                Create Event
              </button>
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="rounded-xl border border-gray-200 px-4 py-2 text-sm font-semibold text-gray-600 hover:bg-gray-50"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* Events list */}
        {loading ? (
          <div className="flex justify-center py-12">
            <Loader2 className="size-6 animate-spin text-gray-400" />
          </div>
        ) : allEvents.length === 0 ? (
          <div className="rounded-2xl border-2 border-gray-200 bg-white p-12 text-center">
            <Calendar className="mx-auto size-8 text-gray-300 mb-3" />
            <p className="text-sm text-gray-500">No events for {MONTHS[month - 1]} {year}</p>
          </div>
        ) : (
          <div className="space-y-3">
            {allEvents.map((evt) => {
              const colors = EVENT_TYPE_COLORS[evt.eventType] ?? EVENT_TYPE_COLORS.custom
              const overdue = isOverdue(evt.dueDate, evt.completed)
              return (
                <div
                  key={evt.id}
                  className={`rounded-2xl border-2 bg-white p-5 ${overdue ? 'border-red-300 bg-red-50/50' : evt.completed ? 'border-emerald-200 bg-emerald-50/30' : 'border-gray-200'}`}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ${colors.bg} ${colors.text}`}>
                          {EVENT_TYPE_LABELS[evt.eventType] ?? evt.eventType}
                        </span>
                        {evt.isAutoGenerated && (
                          <span className="rounded-full bg-gray-100 px-2 py-0.5 text-[10px] font-semibold text-gray-500 uppercase">
                            Auto-detected
                          </span>
                        )}
                        {overdue && (
                          <span className="inline-flex items-center gap-1 rounded-full bg-red-100 px-2 py-0.5 text-[10px] font-semibold text-red-700 uppercase">
                            <AlertTriangle className="size-3" /> Overdue
                          </span>
                        )}
                        {evt.completed && (
                          <span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-semibold text-emerald-700 uppercase">
                            <CheckCircle2 className="size-3" /> Done
                          </span>
                        )}
                      </div>
                      <h3 className="text-sm font-bold text-gray-900">{evt.title}</h3>
                      {evt.description && <p className="text-xs text-gray-500 mt-0.5">{evt.description}</p>}
                      <p className="text-xs text-gray-400 mt-1">
                        Due: {new Date(evt.dueDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                        {evt.creator && <span className="ml-2">Created by {evt.creator.name}</span>}
                      </p>
                    </div>
                    {!evt.isAutoGenerated && !evt.completed && (
                      <div className="flex items-center gap-2 shrink-0">
                        <button
                          type="button"
                          onClick={() => handleComplete(evt.id)}
                          className="rounded-lg p-1.5 hover:bg-emerald-50 text-emerald-600"
                          title="Mark complete"
                        >
                          <CheckCircle2 className="size-4" />
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDelete(evt.id)}
                          className="rounded-lg p-1.5 hover:bg-red-50 text-red-500"
                          title="Delete"
                        >
                          <Trash2 className="size-4" />
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}
