import 'dotenv/config'
import { prisma } from '../app/lib/prisma'

type BuildingInput = {
  name: string
  shortName: string | null
  slug: string
  type: 'ACADEMIC' | 'DINING' | 'RECREATION' | 'LIBRARY' | 'RESIDENCE' | 'PARKING' | 'HEALTH' | 'ADMINISTRATION' | 'ATHLETICS' | 'STUDENT_SERVICES'
  latitude: number
  longitude: number
  address: string | null
  description: string | null
  hours: string | null
  imageUrl: string | null
  amenities: string[]
  aliases: string[]
  floors: number | null
  departments: string[]
  accessibilityNotes: string | null
}

const BUILDINGS: BuildingInput[] = [
  // ── Libraries ──────────────────────────────────────────────────
  {
    name: 'William T. Young Library',
    shortName: 'YL',
    slug: 'young-library',
    type: 'LIBRARY',
    latitude: 38.0309,
    longitude: -84.5042,
    address: '401 Hilltop Ave',
    description: 'Main research library with 1.2M volumes, study spaces, and the largest chandelier in the world.',
    hours: 'M-Th 7:30am-12am, F 7:30am-9pm, Sat 10am-9pm, Sun 11am-12am',
    imageUrl: null,
    amenities: ['wifi', 'study-rooms', 'cafe', 'printing', 'group-rooms'],
    aliases: ['WTYL', 'Main Library', 'Young Library'],
    floors: 5,
    departments: ['UK Libraries', 'Special Collections', 'Research Services'],
    accessibilityNotes: 'Wheelchair accessible via main entrance on Hilltop Ave. Elevators to all floors. Accessible restrooms on every floor.',
  },
  {
    name: 'Lucille Little Fine Arts Library',
    shortName: 'FA LIB',
    slug: 'fine-arts-library',
    type: 'LIBRARY',
    latitude: 38.0380,
    longitude: -84.5053,
    address: '160 Patterson Dr',
    description: 'Specialized library for fine arts, music, and performing arts resources.',
    hours: 'M-F 8am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'study-rooms', 'listening-stations'],
    aliases: ['LLFL', 'Fine Arts Library', 'FA Library'],
    floors: 3,
    departments: ['Fine Arts Library'],
    accessibilityNotes: 'Accessible entrance on Patterson Dr side. Elevator available.',
  },
  {
    name: 'Agricultural Information Center',
    shortName: 'AG LIB',
    slug: 'ag-library',
    type: 'LIBRARY',
    latitude: 38.0292,
    longitude: -84.5075,
    address: '109 Agricultural Science Center N',
    description: 'Library serving agriculture, food science, and environmental studies.',
    hours: 'M-F 8am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'printing'],
    aliases: ['AGIC', 'Ag Library'],
    floors: 2,
    departments: ['Agricultural Information Center'],
    accessibilityNotes: 'Ground-floor entrance accessible. Located inside Ag Science Center North.',
  },

  // ── Academic Buildings ──────────────────────────────────────────
  {
    name: 'White Hall Classroom Building',
    shortName: 'WH',
    slug: 'white-hall',
    type: 'ACADEMIC',
    latitude: 38.0389,
    longitude: -84.5045,
    address: '505 Rose St',
    description: 'Large lecture and classroom building in the heart of campus.',
    hours: 'M-F 7am-10pm',
    imageUrl: null,
    amenities: ['wifi', 'elevators'],
    aliases: ['WHTL', '505 Rose', 'White Hall'],
    floors: 4,
    departments: ['General Classrooms', 'Various Departments'],
    accessibilityNotes: 'Main entrance on Rose St is wheelchair accessible. Elevators to all floors. Accessible restrooms on floors 1 and 3.',
  },
  {
    name: 'Chemistry-Physics Building',
    shortName: 'CP',
    slug: 'chem-phys',
    type: 'ACADEMIC',
    latitude: 38.0383,
    longitude: -84.5063,
    address: '505 Rose St',
    description: 'Houses Chemistry and Physics departments with labs and classrooms.',
    hours: 'M-F 7am-10pm',
    imageUrl: null,
    amenities: ['wifi', 'labs', 'elevators'],
    aliases: ['CP', 'CHEM-PHYS', 'Chem Phys'],
    floors: 6,
    departments: ['Chemistry', 'Physics & Astronomy'],
    accessibilityNotes: 'Accessible entrance on the south side. Elevators available but some older lab wings have limited access. Chemistry offices on floors 2-4, Physics on floors 4-6.',
  },
  {
    name: 'Jacobs Science Building',
    shortName: 'JSB',
    slug: 'jacobs-science',
    type: 'ACADEMIC',
    latitude: 38.0377,
    longitude: -84.5081,
    address: '249 Chemistry-Physics Bldg',
    description: 'Science research and classroom building adjacent to Chem-Phys.',
    hours: 'M-F 7am-9pm',
    imageUrl: null,
    amenities: ['wifi', 'labs'],
    aliases: ['JSB', 'Jacobs'],
    floors: 4,
    departments: ['Sciences'],
    accessibilityNotes: 'Accessible entrance from ground level. Elevator available.',
  },
  {
    name: 'Whitehall Building',
    shortName: 'WHB',
    slug: 'whitehall-building',
    type: 'ACADEMIC',
    latitude: 38.0393,
    longitude: -84.5038,
    address: '323 Rose Ln',
    description: 'Classroom and office building near the central campus corridor.',
    hours: 'M-F 7am-9pm',
    imageUrl: null,
    amenities: ['wifi'],
    aliases: ['WHB', 'Whitehall'],
    floors: 3,
    departments: [],
    accessibilityNotes: 'Main entrance accessible. No elevator — upper floors not wheelchair accessible.',
  },
  {
    name: 'Patterson Office Tower',
    shortName: 'POT',
    slug: 'patterson-office-tower',
    type: 'ACADEMIC',
    latitude: 38.0375,
    longitude: -84.5040,
    address: '535 S Limestone',
    description: '18-story tower housing humanities and social science departments.',
    hours: 'M-F 7:30am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'elevators'],
    aliases: ['POT', 'Patterson Tower'],
    floors: 18,
    departments: ['English', 'History', 'Philosophy', 'Political Science', 'Sociology', 'Psychology', 'Modern & Classical Languages'],
    accessibilityNotes: 'Main entrance on S Limestone is accessible. Two elevators serve all 18 floors. Odd floors house offices, even floors have classrooms.',
  },
  {
    name: 'Classroom Building',
    shortName: 'CB',
    slug: 'classroom-building',
    type: 'ACADEMIC',
    latitude: 38.0385,
    longitude: -84.5033,
    address: '543 S Limestone',
    description: 'Multi-story classroom facility adjacent to Patterson Office Tower.',
    hours: 'M-F 7am-10pm',
    imageUrl: null,
    amenities: ['wifi', 'elevators'],
    aliases: ['CB', 'CLB'],
    floors: 5,
    departments: ['General Classrooms'],
    accessibilityNotes: 'Connected to Patterson Office Tower. Elevators available. Accessible entrance on S Limestone.',
  },
  {
    name: 'Funkhouser Building',
    shortName: 'FH',
    slug: 'funkhouser',
    type: 'ACADEMIC',
    latitude: 38.0395,
    longitude: -84.5062,
    address: '231 Funkhouser Dr',
    description: 'Home to the Department of Earth and Environmental Sciences.',
    hours: 'M-F 7:30am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'labs'],
    aliases: ['FH', 'Funkhouser'],
    floors: 3,
    departments: ['Earth & Environmental Sciences'],
    accessibilityNotes: 'Historic building — accessible entrance on north side. Elevator to all floors.',
  },
  {
    name: 'Kastle Hall',
    shortName: 'KH',
    slug: 'kastle-hall',
    type: 'ACADEMIC',
    latitude: 38.0398,
    longitude: -84.5052,
    address: '401 Rose St',
    description: 'Academic building housing departmental offices and classrooms.',
    hours: 'M-F 7:30am-5pm',
    imageUrl: null,
    amenities: ['wifi'],
    aliases: ['KH', 'Kastle'],
    floors: 3,
    departments: ['Mathematics'],
    accessibilityNotes: 'Accessible entrance on Rose St. Elevator available.',
  },
  {
    name: 'Erikson Hall',
    shortName: 'EH',
    slug: 'erikson-hall',
    type: 'ACADEMIC',
    latitude: 38.0342,
    longitude: -84.5035,
    address: '156 Taylor Education Bldg',
    description: 'Home to the College of Education and related programs.',
    hours: 'M-F 7:30am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'elevators'],
    aliases: ['EH', 'Erikson'],
    floors: 4,
    departments: ['College of Education', 'Educational Policy Studies', 'Curriculum & Instruction'],
    accessibilityNotes: 'Accessible entrance on south side. Elevators to all floors. Connected to Taylor Education Building.',
  },
  {
    name: 'Taylor Education Building',
    shortName: 'TEB',
    slug: 'taylor-education',
    type: 'ACADEMIC',
    latitude: 38.0340,
    longitude: -84.5028,
    address: '597 S Upper St',
    description: 'Multi-purpose education building with classrooms and research offices.',
    hours: 'M-F 7:30am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'elevators'],
    aliases: ['TEB', 'Taylor Ed'],
    floors: 5,
    departments: ['College of Education', 'Educational Leadership'],
    accessibilityNotes: 'Main entrance on S Upper St is accessible. Elevators serve all floors.',
  },
  {
    name: 'Gatton College of Business and Economics',
    shortName: 'GATTON',
    slug: 'gatton-business',
    type: 'ACADEMIC',
    latitude: 38.0320,
    longitude: -84.5020,
    address: '550 S Limestone',
    description: 'College of Business and Economics with modern classrooms and finance labs.',
    hours: 'M-F 7am-10pm, Sat 8am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'study-rooms', 'cafe', 'elevators', 'computer-labs'],
    aliases: ['GATTON', 'B&E', 'Gatton Business'],
    floors: 4,
    departments: ['Finance & Quantitative Methods', 'Management', 'Marketing & Supply Chain', 'Accounting', 'Economics'],
    accessibilityNotes: 'Fully accessible modern building. Main entrance on S Limestone. Elevators and accessible restrooms on all floors. Finance lab on floor 2, computer labs on floor 3.',
  },
  {
    name: 'Law Building (J. David Rosenberg College of Law)',
    shortName: 'LAW',
    slug: 'law-building',
    type: 'ACADEMIC',
    latitude: 38.0348,
    longitude: -84.5049,
    address: '620 S Limestone',
    description: 'Home to the UK College of Law with moot courtroom and legal library.',
    hours: 'M-F 7am-11pm, Sat-Sun 8am-10pm',
    imageUrl: null,
    amenities: ['wifi', 'study-rooms', 'courtroom', 'library'],
    aliases: ['LAW', 'Rosenberg Law', 'College of Law'],
    floors: 4,
    departments: ['College of Law', 'Law Library'],
    accessibilityNotes: 'Main entrance accessible. Moot courtroom on floor 2. Law Library on floors 1-2. Elevators to all floors.',
  },
  {
    name: 'Ralph G. Anderson Building',
    shortName: 'RALPH',
    slug: 'anderson-building',
    type: 'ACADEMIC',
    latitude: 38.0362,
    longitude: -84.5095,
    address: '128 Ralph G. Anderson Bldg',
    description: 'Engineering classroom and lab building.',
    hours: 'M-F 7:30am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'labs', 'elevators'],
    aliases: ['RGAN', 'Anderson Engineering'],
    floors: 4,
    departments: ['Electrical & Computer Engineering', 'Computer Science'],
    accessibilityNotes: 'Accessible entrance on west side. Elevators available. Labs on floors 2-3.',
  },
  {
    name: 'F. Paul Anderson Tower',
    shortName: 'FPAT',
    slug: 'fp-anderson-tower',
    type: 'ACADEMIC',
    latitude: 38.0365,
    longitude: -84.5087,
    address: '127 FPAT',
    description: 'Engineering tower with offices and advanced research labs.',
    hours: 'M-F 7:30am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'labs', 'elevators'],
    aliases: ['FPAT', 'Anderson Tower'],
    floors: 8,
    departments: ['Mechanical Engineering', 'Chemical & Materials Engineering', 'Biomedical Engineering'],
    accessibilityNotes: 'Accessible entrance at ground level. Elevators to all floors. Research labs on upper floors.',
  },
  {
    name: 'Oliver H. Raymond Building',
    shortName: 'OHR',
    slug: 'raymond-building',
    type: 'ACADEMIC',
    latitude: 38.0358,
    longitude: -84.5100,
    address: '123 Raymond Bldg',
    description: 'Civil engineering building with structural testing facilities.',
    hours: 'M-F 7:30am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'labs'],
    aliases: ['OHR', 'Raymond Civil Engineering'],
    floors: 3,
    departments: ['Civil Engineering'],
    accessibilityNotes: 'Ground-floor entrance accessible. Upper floors via elevator. Structural testing lab in basement.',
  },
  {
    name: 'Davis Marksbury Building',
    shortName: 'DMB',
    slug: 'marksbury-building',
    type: 'ACADEMIC',
    latitude: 38.0370,
    longitude: -84.5103,
    address: '329 Rose St',
    description: 'Computer Science department headquarters with modern computing labs.',
    hours: 'M-F 7am-11pm, Sat-Sun 10am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'computer-labs', 'elevators', 'study-rooms'],
    aliases: ['DMB', 'Marksbury', 'CS Building'],
    floors: 4,
    departments: ['Computer Science'],
    accessibilityNotes: 'Fully accessible. Main entrance on Rose St. Elevators to all floors. CS labs on floor 1, offices on floors 2-4. Room 203 is a primary lecture hall on floor 2.',
  },
  {
    name: 'Mining and Minerals Resources Building',
    shortName: 'MMRB',
    slug: 'mining-minerals',
    type: 'ACADEMIC',
    latitude: 38.0355,
    longitude: -84.5107,
    address: '234 Mining & Mineral Resources Bldg',
    description: 'Mining engineering research and classroom facility.',
    hours: 'M-F 7:30am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'labs'],
    aliases: ['MMRB', 'Mining Building'],
    floors: 3,
    departments: ['Mining Engineering'],
    accessibilityNotes: 'Ground-floor entrance accessible. Elevator available.',
  },
  {
    name: 'Thomas Hunt Morgan Building',
    shortName: 'THM',
    slug: 'morgan-building',
    type: 'ACADEMIC',
    latitude: 38.0372,
    longitude: -84.5070,
    address: '675 Rose St',
    description: 'Biological sciences research building with advanced labs.',
    hours: 'M-F 7:30am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'labs', 'elevators'],
    aliases: ['THM', 'TH Morgan', 'Bio Sciences'],
    floors: 5,
    departments: ['Biology', 'Entomology'],
    accessibilityNotes: 'Main entrance accessible. Elevators serve all floors. Teaching labs on floors 1-2, research labs on floors 3-5.',
  },
  {
    name: 'Don & Cathy Jacobs Science Building',
    shortName: 'JSCI',
    slug: 'don-jacobs-science',
    type: 'ACADEMIC',
    latitude: 38.0378,
    longitude: -84.5076,
    address: '249 Rose St',
    description: 'Modern interdisciplinary science facility with teaching and research labs.',
    hours: 'M-F 7am-10pm',
    imageUrl: null,
    amenities: ['wifi', 'labs', 'elevators', 'study-rooms'],
    aliases: ['JSCI', 'New Science', 'Jacobs STEM'],
    floors: 5,
    departments: ['Interdisciplinary Sciences', 'Statistics'],
    accessibilityNotes: 'Fully accessible modern building. Elevators and accessible restrooms on all floors. Open atrium connects to Chem-Phys.',
  },
  {
    name: 'Seaton Center',
    shortName: 'SC',
    slug: 'seaton-center',
    type: 'ACADEMIC',
    latitude: 38.0330,
    longitude: -84.5050,
    address: '148 Seaton Center',
    description: 'Home to the Department of Kinesiology and Health Promotion.',
    hours: 'M-F 7:30am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'gym'],
    aliases: ['SEAT', 'Seaton'],
    floors: 2,
    departments: ['Kinesiology & Health Promotion'],
    accessibilityNotes: 'Ground-floor entrance accessible. Gym facilities on floor 1.',
  },
  {
    name: 'Barnhart Building',
    shortName: 'BARN',
    slug: 'barnhart',
    type: 'ACADEMIC',
    latitude: 38.0298,
    longitude: -84.5060,
    address: '203 Barnhart Bldg',
    description: 'Agriculture and related science offices and classrooms.',
    hours: 'M-F 7:30am-5pm',
    imageUrl: null,
    amenities: ['wifi'],
    aliases: ['BARN', 'Barnhart'],
    floors: 3,
    departments: ['Agriculture'],
    accessibilityNotes: 'Accessible entrance on east side.',
  },

  // ── Dining ─────────────────────────────────────────────────────
  {
    name: 'Blazer Dining Hall',
    shortName: 'BLAZER',
    slug: 'blazer-dining',
    type: 'DINING',
    latitude: 38.0335,
    longitude: -84.5005,
    address: '359 S Limestone',
    description: 'All-you-care-to-eat dining hall with rotating menus.',
    hours: 'M-F 7am-9pm, Sat-Sun 10am-8pm',
    imageUrl: null,
    amenities: ['dining', 'allergen-friendly'],
    aliases: ['BLAZ', 'Blazer'],
    floors: 1,
    departments: [],
    accessibilityNotes: 'Ground-floor accessible. Automatic door at main entrance.',
  },
  {
    name: 'The 90',
    shortName: '90',
    slug: 'the-90',
    type: 'DINING',
    latitude: 38.0405,
    longitude: -84.5040,
    address: '305 Euclid Ave',
    description: 'Popular food court-style dining near north campus.',
    hours: 'M-F 10:30am-8pm',
    imageUrl: null,
    amenities: ['dining', 'multiple-options'],
    aliases: ['THE90', 'Ninety'],
    floors: 1,
    departments: [],
    accessibilityNotes: 'Ground-floor accessible entrance on Euclid Ave.',
  },
  {
    name: 'Champions Kitchen',
    shortName: 'CK',
    slug: 'champions-kitchen',
    type: 'DINING',
    latitude: 38.0280,
    longitude: -84.5035,
    address: '360 Sports Center Dr',
    description: 'Modern dining facility near athletics complex with diverse food stations.',
    hours: 'M-F 7am-9pm, Sat-Sun 10am-8pm',
    imageUrl: null,
    amenities: ['dining', 'allergen-friendly', 'halal'],
    aliases: ['CK', 'Champs Kitchen'],
    floors: 1,
    departments: [],
    accessibilityNotes: 'Fully accessible modern facility. Automatic doors.',
  },
  {
    name: 'Fresh Food Company at The 90',
    shortName: 'FFC',
    slug: 'fresh-food-company',
    type: 'DINING',
    latitude: 38.0407,
    longitude: -84.5043,
    address: '305 Euclid Ave',
    description: 'Farm-to-table dining concept featuring locally sourced ingredients.',
    hours: 'M-F 11am-8pm',
    imageUrl: null,
    amenities: ['dining', 'locally-sourced', 'vegetarian'],
    aliases: ['FFC', 'Fresh Food'],
    floors: 1,
    departments: [],
    accessibilityNotes: 'Ground-floor accessible. Located within The 90 complex.',
  },
  {
    name: 'Starbucks (Student Center)',
    shortName: 'SBUX-SC',
    slug: 'starbucks-student-center',
    type: 'DINING',
    latitude: 38.0380,
    longitude: -84.5025,
    address: '160 Avenue of Champions',
    description: 'Starbucks coffeehouse inside the Student Center.',
    hours: 'M-F 7am-8pm, Sat-Sun 8am-6pm',
    imageUrl: null,
    amenities: ['coffee', 'wifi'],
    aliases: ['SBUX', 'Starbucks SC'],
    floors: 1,
    departments: [],
    accessibilityNotes: 'Accessible via Student Center main entrance. Ground floor.',
  },
  {
    name: 'Ovid\'s Cafe (Young Library)',
    shortName: 'OVIDS',
    slug: 'ovids-cafe',
    type: 'DINING',
    latitude: 38.0311,
    longitude: -84.5040,
    address: '401 Hilltop Ave',
    description: 'Cafe inside William T. Young Library with coffee, snacks, and light meals.',
    hours: 'M-F 7:30am-6pm',
    imageUrl: null,
    amenities: ['coffee', 'snacks', 'wifi'],
    aliases: ['OVID', 'Ovids', 'Library Cafe'],
    floors: 1,
    departments: [],
    accessibilityNotes: 'Located on ground floor of Young Library. Fully accessible.',
  },

  // ── Recreation ─────────────────────────────────────────────────
  {
    name: 'Johnson Center (Student Rec)',
    shortName: 'JC',
    slug: 'johnson-center',
    type: 'RECREATION',
    latitude: 38.0325,
    longitude: -84.5015,
    address: '536 Woodland Ave',
    description: 'Main student recreation center with gym, pool, climbing wall, and courts.',
    hours: 'M-F 6am-11pm, Sat-Sun 8am-9pm',
    imageUrl: null,
    amenities: ['gym', 'pool', 'climbing-wall', 'basketball', 'racquetball', 'locker-rooms'],
    aliases: ['JC', 'Student Rec', 'The Rec'],
    floors: 3,
    departments: ['Campus Recreation'],
    accessibilityNotes: 'Fully accessible. Main entrance on Woodland Ave. Elevators to all floors. Pool lift available. Accessible locker rooms on floor 1.',
  },
  {
    name: 'Lancaster Aquatic Center',
    shortName: 'LAC',
    slug: 'lancaster-aquatic',
    type: 'RECREATION',
    latitude: 38.0328,
    longitude: -84.5010,
    address: '536 Woodland Ave',
    description: 'Olympic-sized swimming facility and diving center.',
    hours: 'M-F 6am-8pm, Sat 10am-6pm, Sun 12pm-6pm',
    imageUrl: null,
    amenities: ['pool', 'diving', 'locker-rooms'],
    aliases: ['LAC', 'Lancaster Pool'],
    floors: 2,
    departments: ['Campus Recreation', 'UK Swimming & Diving'],
    accessibilityNotes: 'Accessible entrance. Pool lift available for aquatic access.',
  },

  // ── Student Services ────────────────────────────────────────────
  {
    name: 'Student Center',
    shortName: 'STUCTR',
    slug: 'student-center',
    type: 'STUDENT_SERVICES',
    latitude: 38.0382,
    longitude: -84.5022,
    address: '160 Avenue of Champions',
    description: 'Hub for student life, clubs, dining options, bookstore, and event space.',
    hours: 'M-F 7am-11pm, Sat-Sun 9am-9pm',
    imageUrl: null,
    amenities: ['wifi', 'dining', 'bookstore', 'meeting-rooms', 'atm'],
    aliases: ['SC', 'STCTR', 'Student Union'],
    floors: 3,
    departments: ['Student Activities', 'Student Government', 'UK Bookstore'],
    accessibilityNotes: 'Fully accessible. Multiple entrances with automatic doors. Elevators to all floors. Bookstore on floor 1, meeting rooms on floor 2, ballroom on floor 3.',
  },
  {
    name: 'Hilary J. Boone Center',
    shortName: 'BOONE',
    slug: 'boone-center',
    type: 'STUDENT_SERVICES',
    latitude: 38.0345,
    longitude: -84.5060,
    address: '500 Rose St',
    description: 'Faculty club and event center hosting university conferences and receptions.',
    hours: 'M-F 8am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'event-space', 'catering'],
    aliases: ['BOONE', 'Boone Faculty Club'],
    floors: 2,
    departments: ['Faculty Club'],
    accessibilityNotes: 'Accessible entrance on Rose St. Elevator to second floor.',
  },
  {
    name: 'Mathews Building',
    shortName: 'MATH',
    slug: 'mathews-building',
    type: 'STUDENT_SERVICES',
    latitude: 38.0352,
    longitude: -84.5028,
    address: '325 Mathews Bldg',
    description: 'Houses academic advising, career services, and student support offices.',
    hours: 'M-F 8am-5pm',
    imageUrl: null,
    amenities: ['wifi', 'advising', 'career-services'],
    aliases: ['MTWS', 'Mathews'],
    floors: 3,
    departments: ['Academic Advising', 'Career Center', 'Student Support'],
    accessibilityNotes: 'Accessible entrance. Elevator available. Career Center on floor 1, Advising on floor 2.',
  },
  {
    name: 'Frazee Hall',
    shortName: 'FRAZ',
    slug: 'frazee-hall',
    type: 'STUDENT_SERVICES',
    latitude: 38.0395,
    longitude: -84.5030,
    address: '201 Frazee Hall',
    description: 'Enrollment management and financial aid offices.',
    hours: 'M-F 8am-4:30pm',
    imageUrl: null,
    amenities: ['wifi'],
    aliases: ['FRAZ', 'Frazee', 'Financial Aid'],
    floors: 2,
    departments: ['Financial Aid', 'Enrollment Management'],
    accessibilityNotes: 'Accessible entrance on ground floor. Financial Aid office on floor 1.',
  },

  // ── Residence Halls ─────────────────────────────────────────────
  {
    name: 'Central Hall',
    shortName: 'CENT',
    slug: 'central-hall',
    type: 'RESIDENCE',
    latitude: 38.0408,
    longitude: -84.5020,
    address: '200 Euclid Ave',
    description: 'Centrally located residence hall near dining and academic buildings.',
    hours: '24/7 (residents)',
    imageUrl: null,
    amenities: ['wifi', 'laundry', 'study-rooms', 'kitchen'],
    aliases: ['CENT', 'Central'],
    floors: 5,
    departments: [],
    accessibilityNotes: 'Card-access entrance is accessible. Elevator to all floors. Accessible rooms available on floor 1.',
  },
  {
    name: 'Jewell Hall',
    shortName: 'JEW',
    slug: 'jewell-hall',
    type: 'RESIDENCE',
    latitude: 38.0412,
    longitude: -84.5030,
    address: '156 Euclid Ave',
    description: 'First-year student residence hall with community programming.',
    hours: '24/7 (residents)',
    imageUrl: null,
    amenities: ['wifi', 'laundry', 'study-rooms'],
    aliases: ['JEWL', 'Jewell'],
    floors: 5,
    departments: [],
    accessibilityNotes: 'Card-access entrance accessible. Elevator available. Accessible rooms on floor 1.',
  },
  {
    name: 'Haggin Hall',
    shortName: 'HAG',
    slug: 'haggin-hall',
    type: 'RESIDENCE',
    latitude: 38.0270,
    longitude: -84.5040,
    address: '313 Hilltop Ave',
    description: 'Suite-style residence hall near Young Library and south campus.',
    hours: '24/7 (residents)',
    imageUrl: null,
    amenities: ['wifi', 'laundry', 'study-rooms', 'kitchen'],
    aliases: ['HAG', 'Haggin'],
    floors: 6,
    departments: [],
    accessibilityNotes: 'Accessible entrance on Hilltop Ave. Elevator to all floors. Accessible suites available.',
  },
  {
    name: 'Lewis Hall',
    shortName: 'LEWIS',
    slug: 'lewis-hall',
    type: 'RESIDENCE',
    latitude: 38.0265,
    longitude: -84.5048,
    address: '319 Hilltop Ave',
    description: 'Modern suite-style residence hall on south campus.',
    hours: '24/7 (residents)',
    imageUrl: null,
    amenities: ['wifi', 'laundry', 'study-rooms'],
    aliases: ['LEW', 'Lewis'],
    floors: 6,
    departments: [],
    accessibilityNotes: 'Accessible entrance. Elevator to all floors.',
  },
  {
    name: 'Limestone Park Apartments',
    shortName: 'LPA',
    slug: 'limestone-park',
    type: 'RESIDENCE',
    latitude: 38.0330,
    longitude: -84.5000,
    address: '525 S Limestone',
    description: 'Apartment-style housing for upperclass students.',
    hours: '24/7 (residents)',
    imageUrl: null,
    amenities: ['wifi', 'laundry', 'kitchen', 'parking'],
    aliases: ['LPA', 'Limestone Apts'],
    floors: 4,
    departments: [],
    accessibilityNotes: 'Accessible entrance. Elevator available. ADA-compliant apartments on floor 1.',
  },

  // ── Health ──────────────────────────────────────────────────────
  {
    name: 'University Health Service',
    shortName: 'UHS',
    slug: 'health-service',
    type: 'HEALTH',
    latitude: 38.0350,
    longitude: -84.5070,
    address: '830 S Limestone',
    description: 'Primary care clinic for students including mental health, pharmacy, and lab services.',
    hours: 'M-F 8am-5pm',
    imageUrl: null,
    amenities: ['pharmacy', 'mental-health', 'lab', 'immunizations'],
    aliases: ['UHS', 'Health Clinic'],
    floors: 2,
    departments: ['Student Health', 'Pharmacy', 'Mental Health'],
    accessibilityNotes: 'Fully accessible. Automatic doors at main entrance. All services on accessible floors.',
  },
  {
    name: 'Counseling Center',
    shortName: 'COUNS',
    slug: 'counseling-center',
    type: 'HEALTH',
    latitude: 38.0348,
    longitude: -84.5075,
    address: '201 Frazee Hall',
    description: 'Free counseling services for enrolled students — individual, group, and crisis support.',
    hours: 'M-F 8am-5pm',
    imageUrl: null,
    amenities: ['mental-health', 'crisis-support', 'group-therapy'],
    aliases: ['COUNS', 'UKCC'],
    floors: 1,
    departments: ['Counseling Center'],
    accessibilityNotes: 'Ground-floor accessible entrance. All counseling rooms wheelchair accessible.',
  },
  {
    name: 'UK HealthCare (UK Chandler Hospital)',
    shortName: 'UKMC',
    slug: 'chandler-hospital',
    type: 'HEALTH',
    latitude: 38.0310,
    longitude: -84.5090,
    address: '800 Rose St',
    description: 'Level 1 trauma center and teaching hospital.',
    hours: '24/7',
    imageUrl: null,
    amenities: ['emergency', 'pharmacy', 'parking'],
    aliases: ['UKMC', 'Chandler', 'UK Hospital', 'Medical Center'],
    floors: 12,
    departments: ['Emergency Medicine', 'Internal Medicine', 'Surgery', 'Pharmacy'],
    accessibilityNotes: 'Fully accessible hospital. Emergency entrance on Rose St. Main entrance with valet. Elevators throughout. Patient information desk on floor 1.',
  },

  // ── Administration ──────────────────────────────────────────────
  {
    name: 'Main Building',
    shortName: 'MAIN',
    slug: 'main-building',
    type: 'ADMINISTRATION',
    latitude: 38.0402,
    longitude: -84.5045,
    address: '101 Main Bldg',
    description: 'Historic administration building and home to the President\'s office.',
    hours: 'M-F 8am-5pm',
    imageUrl: null,
    amenities: ['wifi'],
    aliases: ['MAIN', 'Administration Building'],
    floors: 3,
    departments: ['President\'s Office', 'Provost', 'University Administration'],
    accessibilityNotes: 'Historic building — accessible entrance on south side via ramp. Elevator to all floors.',
  },
  {
    name: 'Gillis Building',
    shortName: 'GILLIS',
    slug: 'gillis-building',
    type: 'ADMINISTRATION',
    latitude: 38.0400,
    longitude: -84.5035,
    address: '104 Gillis Bldg',
    description: 'Administrative offices for academic affairs.',
    hours: 'M-F 8am-4:30pm',
    imageUrl: null,
    amenities: ['wifi'],
    aliases: ['GILL', 'Gillis'],
    floors: 3,
    departments: ['Academic Affairs'],
    accessibilityNotes: 'Accessible entrance on ground floor.',
  },
  {
    name: 'Peterson Service Building',
    shortName: 'PSB',
    slug: 'peterson-service',
    type: 'ADMINISTRATION',
    latitude: 38.0290,
    longitude: -84.5095,
    address: '411 S Limestone',
    description: 'Central facilities and operations offices.',
    hours: 'M-F 7:30am-4:30pm',
    imageUrl: null,
    amenities: ['wifi', 'parking'],
    aliases: ['PSB', 'Peterson'],
    floors: 2,
    departments: ['Facilities Management', 'Physical Plant'],
    accessibilityNotes: 'Accessible entrance with parking. Ground-floor offices.',
  },

  // ── Parking ─────────────────────────────────────────────────────
  {
    name: 'PS #1 (Limestone Garage)',
    shortName: 'PS1',
    slug: 'limestone-garage',
    type: 'PARKING',
    latitude: 38.0360,
    longitude: -84.5020,
    address: '489 S Limestone',
    description: 'Multi-story parking garage on South Limestone.',
    hours: '24/7',
    imageUrl: null,
    amenities: ['parking', 'elevators'],
    aliases: ['PS1', 'Limestone Garage'],
    floors: 6,
    departments: [],
    accessibilityNotes: 'Accessible parking on floor 1. Elevators and stairwells on both ends.',
  },
  {
    name: 'PS #2 (Rose Street Garage)',
    shortName: 'PS2',
    slug: 'rose-street-garage',
    type: 'PARKING',
    latitude: 38.0345,
    longitude: -84.5090,
    address: '721 Rose St',
    description: 'Parking structure near the medical center and engineering complex.',
    hours: '24/7',
    imageUrl: null,
    amenities: ['parking', 'elevators'],
    aliases: ['PS2', 'Rose Garage'],
    floors: 5,
    departments: [],
    accessibilityNotes: 'Accessible parking on floor 1. Elevators available. Connected to hospital walkway.',
  },
  {
    name: 'PS #5 (Sports Center Garage)',
    shortName: 'PS5',
    slug: 'sports-center-garage',
    type: 'PARKING',
    latitude: 38.0275,
    longitude: -84.5025,
    address: '348 Sports Center Dr',
    description: 'Large garage near Champions Kitchen and athletics facilities.',
    hours: '24/7',
    imageUrl: null,
    amenities: ['parking', 'elevators'],
    aliases: ['PS5', 'Sports Center Garage'],
    floors: 5,
    departments: [],
    accessibilityNotes: 'Accessible parking on floor 1. Elevators on east and west ends.',
  },

  // ── Athletics ───────────────────────────────────────────────────
  {
    name: 'Kroger Field',
    shortName: 'KROGER',
    slug: 'kroger-field',
    type: 'ATHLETICS',
    latitude: 38.0225,
    longitude: -84.5050,
    address: '1540 University Dr',
    description: 'UK Wildcats football stadium (61,000 capacity).',
    hours: 'Event days only',
    imageUrl: null,
    amenities: ['concessions', 'parking', 'wifi'],
    aliases: ['KRGR', 'Commonwealth Stadium', 'Football Stadium'],
    floors: 4,
    departments: ['UK Athletics', 'Football'],
    accessibilityNotes: 'Accessible seating sections throughout. Accessible entrance at Gate 1. Elevator access to upper levels. Accessible restrooms on all concourse levels.',
  },
  {
    name: 'Rupp Arena',
    shortName: 'RUPP',
    slug: 'rupp-arena',
    type: 'ATHLETICS',
    latitude: 38.0440,
    longitude: -84.4975,
    address: '430 W Vine St',
    description: 'Legendary home of UK Wildcats basketball (23,000 capacity).',
    hours: 'Event days only',
    imageUrl: null,
    amenities: ['concessions', 'parking', 'wifi'],
    aliases: ['RUPP', 'Basketball Arena'],
    floors: 3,
    departments: ['UK Athletics', 'Basketball'],
    accessibilityNotes: 'Accessible entrance at main plaza level. Elevator access to all seating levels. Accessible seating and companion seats available.',
  },
  {
    name: 'Joe Craft Center',
    shortName: 'JCC',
    slug: 'joe-craft-center',
    type: 'ATHLETICS',
    latitude: 38.0250,
    longitude: -84.5070,
    address: '338 Lexington Ave',
    description: 'Basketball practice facility and athletics offices.',
    hours: 'M-F 7am-6pm',
    imageUrl: null,
    amenities: ['wifi'],
    aliases: ['JCC', 'Craft Center'],
    floors: 2,
    departments: ['UK Athletics'],
    accessibilityNotes: 'Accessible entrance. Not generally open to public.',
  },
  {
    name: 'Nutter Field House',
    shortName: 'NFH',
    slug: 'nutter-field-house',
    type: 'ATHLETICS',
    latitude: 38.0260,
    longitude: -84.5060,
    address: '150 Nutter Training Center',
    description: 'Indoor track and field training facility.',
    hours: 'M-F 6am-8pm',
    imageUrl: null,
    amenities: ['track', 'locker-rooms'],
    aliases: ['NFH', 'Nutter'],
    floors: 2,
    departments: ['UK Athletics', 'Track & Field'],
    accessibilityNotes: 'Ground-level entrance accessible. Track level on floor 1.',
  },

  // ── Fine Arts ───────────────────────────────────────────────────
  {
    name: 'Singletary Center for the Arts',
    shortName: 'SCA',
    slug: 'singletary-center',
    type: 'ACADEMIC',
    latitude: 38.0385,
    longitude: -84.5058,
    address: '405 Rose St',
    description: 'Performing arts venue with concert hall, recital hall, and gallery.',
    hours: 'M-F 8am-11pm, Sat-Sun 10am-6pm',
    imageUrl: null,
    amenities: ['wifi', 'concert-hall', 'gallery', 'box-office'],
    aliases: ['SCFA', 'Singletary', 'SCFA Arts'],
    floors: 3,
    departments: ['School of Music', 'Department of Theatre & Dance', 'Arts Administration'],
    accessibilityNotes: 'Accessible entrance on Rose St. Elevator to all floors. Concert Hall has wheelchair seating. Box office on floor 1.',
  },
  {
    name: 'Art Museum (UK Art Museum)',
    shortName: 'UKAM',
    slug: 'uk-art-museum',
    type: 'ACADEMIC',
    latitude: 38.0388,
    longitude: -84.5055,
    address: '405 Rose St',
    description: 'Free museum featuring rotating exhibitions and permanent collection.',
    hours: 'Tu-F 10am-5pm, Sat 12pm-5pm',
    imageUrl: null,
    amenities: ['wifi', 'gallery', 'gift-shop'],
    aliases: ['UKAM', 'Art Museum'],
    floors: 2,
    departments: ['UK Art Museum'],
    accessibilityNotes: 'Accessible entrance within Singletary Center. All galleries wheelchair accessible.',
  },
]

async function main() {
  console.log('🗺️  Seeding Campus Buildings...\n')

  let created = 0
  let updated = 0

  for (const building of BUILDINGS) {
    const result = await prisma.campusBuilding.upsert({
      where: { slug: building.slug },
      create: building,
      update: building,
    })

    const wasCreated = result.createdAt.getTime() === result.updatedAt.getTime()
    if (wasCreated) {
      created++
      console.log(`  + ${building.name} (${building.shortName ?? building.slug})`)
    } else {
      updated++
      console.log(`  ↻ ${building.name} (updated)`)
    }
  }

  console.log(`\n✅ Campus Buildings seeded: ${created} created, ${updated} updated`)
  console.log(`   Total in database: ${await prisma.campusBuilding.count()}`)
}

main()
  .catch((err) => {
    console.error('❌ Seed failed:', err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
